### ISSUE TITLE
kerl builds the wrong thing if you have ERL_TOP set

### ISSUE THREAD

**Issue by rlipscombe** [kerl/kerl#102]
I was attempting to use `kerl build git ...` to build and install Erlang; the build appeared to succeed but `kerl install ...` failed with `Couldn't install Erlang/OTP git (ei-73fc7ca) in /home/roger/erlang/ei-73fc7ca`.

It turns out that it's because I had `ERL_TOP` set (from earlier messing around with building Erlang from source), and that kerl was actually building _that_ copy of Erlang. So when it went to install from `~/.kerl/builds/ei-73fc7ca`, it wasn't actually built.

Either kerl should warn if `ERL_TOP` is already set, or it should be sure to set it correctly in `kerl build git...`.

**Comment by mrallen1** [comment]
@sanmiguel this should be a high priority to fix

**Comment by mrallen1** [comment]
My preference would be to store the previously set `ERL_TOP` somewhere in kerl, then set it blank, then before the script ends, restore the previously set value.

**Comment by rlipscombe** [comment]
> then before the script ends, restore the previously set value.

It will already do this, no? If you set an environment variable (even exported), it only persists until the end of that process (and children)...
