### ISSUE TITLE
Build OTP from git (was: Missing releases)

### ISSUE THREAD

**Issue by tuncer** [kerl/kerl#111]
Due to looking just in http://erlang.org/download/ for releases, kerl misses many official releases that weren't published as full-fledged ones (with a Windows package, etc.). One way to solve this is download tarballs for OTP* tags like, say, https://github.com/erlang/otp/archive/OTP-18.2.3.tar.gz.

This is also the reason why Travis-CI doesn't provide all official releases, because the prebuilt OTP versions are made with kerl.

The fact that doc archives are meant to be downloaded as well, and how to combine that with downloading git tag archives by default, while there are no matching doc archives, raises more questions.

**Comment by mrallen1** [comment]
Are you proposing that kerl grab point releases from github tag information?

**Comment by fenollp** [comment]
Then how about

```shell
git ls-remote --tags https://github.com/erlang/otp \
    | grep -Eo 'OTP[_-][^^{}]+' \
    | sort -u
```

which gives back 

```
OTP-17.0
OTP-17.0.1
OTP-17.0.2
OTP-17.1
OTP-17.1.1
OTP-17.1.2
OTP-17.2
OTP-17.2.1
OTP-17.2.2
OTP-17.3
OTP-17.3.1
OTP-17.3.2
OTP-17.3.3
OTP-17.3.4
OTP-17.4
OTP-17.4.1
OTP-17.5
OTP-17.5.1
OTP-17.5.2
OTP-17.5.3
OTP-17.5.4
OTP-17.5.5
OTP-17.5.6
OTP-17.5.6.1
OTP-17.5.6.2
OTP-17.5.6.3
OTP-17.5.6.4
OTP-17.5.6.5
OTP-17.5.6.6
OTP-17.5.6.7
OTP-17.5.6.8
OTP-18.0
OTP-18.0-rc1
OTP-18.0-rc2
OTP-18.0.1
OTP-18.0.2
OTP-18.0.3
OTP-18.1
OTP-18.1.1
OTP-18.1.2
OTP-18.1.3
OTP-18.1.4
OTP-18.1.5
OTP-18.2
OTP-18.2.1
OTP-18.2.2
OTP-18.2.3
OTP-18.2.4
OTP-18.2.4.1
OTP-18.3
OTP-18.3.1
OTP_17.0-rc1
OTP_17.0-rc2
OTP_R13B03
OTP_R13B04
OTP_R14A
OTP_R14B
OTP_R14B01
OTP_R14B02
OTP_R14B03
OTP_R14B04
OTP_R15A
OTP_R15B
OTP_R15B01
OTP_R15B02
OTP_R15B03
OTP_R15B03-1
OTP_R16A_RELEASE_CANDIDATE
OTP_R16B
OTP_R16B01
OTP_R16B01_RC1
OTP_R16B02
OTP_R16B03
OTP_R16B03-1
OTP_R16B03_yielding_binary_to_term
```

**Comment by tuncer** [comment]
> Are you proposing that kerl grab point releases from github tag information?

Yes.

I still don't know what to do about the fact that there's no prebuilt matching doc archives for git tags. So, we should integrate the use of git tags first and think about doc archives later or just not support it for git tag archives.

**Comment by tuncer** [comment]
> Then how about
>
> ```
> git ls-remote --tags https://github.com/erlang/otp \
>     | grep -Eo 'OTP[_-][^^{}]+' \
>     | sed 's/OTP[_-]//' \
>     | sort -u
> ```

Thanks, @fenollp, this works, and for portability:

1. run `sort|uniq` instead of `sort -u`
2. run `egrep` instead of `grep -E`

**Comment by fenollp** [comment]
kerl can already build from git, why not always build from git? kerl could fetch tagged releases from github's tar.bz URLs and we wouldn't suffer erlang.org's downtime!

**Comment by mrallen1** [comment]
Wish erlang.org would get cloud flare - the one concern I have is validating checksums of the release tar balls.  We can validate the checksums from erlang.org - it's not clear those checksums would be valid for github tar balls.

**Comment by evax** [comment]
@fenollp I second the idea of building from git (at least as an option). Rather than github's tar.bz we could extract tagged releases with `git archive`.
@mrallen1 building from the official source repository partly alleviates the need for checksums

**Comment by evax** [comment]
@tuncer for git tags we could allow building the docs

**Comment by mrallen1** [comment]
@evax I've come around on the idea for two reasons.

1. Github uses a CDN to distribute bits. That will make downloading stuff from them way faster than erlang.org (so so :snail:)
2. It solves a problem with the Ericsson tar balls preventing native lib builds because they already include some .beams in those distributions. (See #68)

I am planning to take some time this week to work on it. One drawback will be a hard dependency on a functional git installation - I suppose a fallback to tarball download is desirable if there's no git install?

**Comment by evax** [comment]
@mrallen1 sounds good. We might want to properly code some feature detection stage, that would help solve other issues with curses, readline, libssl etc

**Comment by mrallen1** [comment]
Yeah there's another ticket open (See #53) which neatly solves that (imo) by making the results of the `./configure` script output visible and would ask for a "Do you want to continue?" confirmation

**Comment by tuncer** [comment]
If you clone otp.git, it's best to do that once and then clone locally for builds after first updating the remote (incl tags).

**Comment by fenollp** [comment]
I think it is better to not clone otp but to fetch a tarball of the given tag instead. The repo is pretty big (not everyone has fibre), all deltas aren't needed, and the only dependence on git would be to fetch tag names.

And I just found a way to extract tag names without git:

```shell
curl https://api.github.com/repos/erlang/otp/git/refs/tags -s \
    | python -m json.tool \
    | egrep -o 'OTP[_-][^"]+' \
    | sort | uniq
```

**Comment by tuncer** [comment]
@fenollp, nice, but I'm afraid adding a Python dependency is too heavy for the task. I'd use grep/awk to extract it from a string like `"ref": "refs/tags/OTP_R15A"`.

**Comment by mrallen1** [comment]
Just merged #122 to address this

**Comment by mrallen1** [comment]
Please retest and open a new ticket if you have problems. Thanks!

**Comment by tuncer** [comment]
Thanks a lot, @mrallen1!
