### ISSUE TITLE
kerl can delete home directory

### ISSUE THREAD

**Issue by alexshavelev** [kerl/kerl#113]
I had something like that (kerl was in /home/user/.kerl)

r15b03-1 /home/user/project/
r15b03-1 /home/user/
....

And decided to clean some.
kerl delete installation /home/user/project/ - works good, but
kerl delete installation /home/user/ - delete all data in folder which 'testdisk' can't restore

**Comment by alexshavelev** [comment]
tried again.
it always delete not build but all files with folder. 
after 'kerl delete installation /home/user/project/' folder 'project' doesn't exists

**Comment by mrallen1** [comment]
Sounds like we need to look at the portions that handle removal to be more careful.

**Comment by alexshavelev** [comment]
@mrallen1 i think this bug is also mentioned in https://github.com/yrashk/kerl/issues/52

**Comment by mrallen1** [comment]
I think we just knocked this one out with #127. Please reopen if you find its still an issue. Thanks!
