### ISSUE TITLE
Kerl fails with "No newest valid release"

### ISSUE THREAD

**Issue by ooshlablu** [kerl/kerl#120]
Installing any (Basho at least) erlang fails when using the kerl version from HEAD with the error message: "No newest valid release". The bizarre thing is that erlang gets built and installed just fine; kerl just exits with that error no matter what happens. Kerl 0.8 works as expected.

I have reproduced with the following erlang installs from git (https://github.com/basho/otp.git):
* R16B02-basho10 (git tag: OTP_R16B02_basho10)
* R16B02-basho8 (git tag: OTP_R16B02_basho8)
* R15B01 (git tag: basho_OTP_R15B01p)

I have tested on the following (64 bit) OS's:
* Ubuntu Precise
* Ubuntu Trusty
* Debian Jessie
* Debian Wheezy
* CentOS 6
* CentOS 7

I will be working with @mrallen1 to get him set up with the environment that I used to reproduce the issue.

**Comment by sanmiguel** [comment]
FWIW I can replicate this with kerl 0.9.1 (via homebrew) on OSX 10.10.5, too. 
![screenshot 2016-04-20 01 01 02](https://cloud.githubusercontent.com/assets/2122822/14658369/88e2444c-0693-11e6-831a-f2404063e059.png)

Pretty sure this error message is related to installing docs, as none have shown up in this installation:

```bash
$ erl -man gen_fsm
No manual entry for gen_fsm
```

**Comment by lucafavatella** [comment]
Change triggering this shall be somewhere in [get_newest_valid_release](https://github.com/kerl/kerl/compare/0.8...0.9.1#diff-75743bad0452412b658dabebd6b439f4R219).

**Comment by lucafavatella** [comment]
... or for some reason [this](https://github.com/kerl/kerl/compare/0.8...0.9.1#diff-75743bad0452412b658dabebd6b439f4R144) regular expression does not support the current version of the OTP download [page](http://www.erlang.org/download).

(I am trying to install 18.3.1.)

**Comment by lucafavatella** [comment]
I get this issue running `kerl install OTP-18.3.1 MYPATH` where 18.3.1 built using `kerl build git ...` hence I focussed on get_newest_valid_release code path.

The root cause seems to be that refactoring in 0.9.1 compared to 0.8 broke the semantics of the script. I extracted two minimum code snippets for showing what looks like issue. My otp_releases file is a local one that I had but it is not relevant I believe.

## Kerl 0.8

```
$ cat kerl-0.8-get_newest_valid_release
#! /bin/sh

KERL_BASE_DIR="$HOME/.kerl"

get_newest_valid_release()
{
    #check_releases
    for rel in `cat $KERL_BASE_DIR/otp_releases | tail -1`; do
        if [ ! -z "$rel" ]; then
            echo "$rel"
            return 0
        fi
    done
    return 1
}

get_newest_valid_release || exit 2
```

```
$ ./kerl-0.8-get_newest_valid_release
18.2.1
```
Exit status 0.

## Kerl 0.9.1

```
$ cat kerl-0.9.1-get_newest_valid_release
#! /bin/sh

KERL_BASE_DIR="$HOME/.kerl"

get_newest_valid_release()
{
    #check_releases
    while read -r rel; do
        if [ ! -z "$rel" ]; then
            echo "$rel"
            return 0
        fi
    done < "$KERL_BASE_DIR"/otp_releases | tail -1
    return 1
}

get_newest_valid_release || exit 2
```

```
$ ./kerl-0.9.1-get_newest_valid_release
R10B-0
```
Exit status 2.

**Comment by lucafavatella** [comment]
The issue in get_newest_valid_release might be present in other points in the code - I did not check.

**Comment by mrallen1** [comment]
Have rewritten the function to be less stupid. Will have a PR up shortly.

**Comment by mrallen1** [comment]
@ooshlablu Will you please take #121 for a spin through the build farm? Just want to confirm my fix fixes what you're seeing.

**Comment by mrallen1** [comment]
@lucafavatella Thanks for your help on this!

**Comment by ooshlablu** [comment]
0.9.2 works fine for all versions of erlang and OS's listed above.
