### ISSUE TITLE
Documentation inconsistency around KERL_BASE_DIR

### ISSUE THREAD

**Issue by BillSmargiassi** [kerl/kerl#128]
`KERL_BASE_DIR` is mentioned only once in the README. It defaults to `$HOME/.kerl` from the code. Other mentions in the README state `$HOME/.kerl`. Wouldn't it make more sense if these all used `KERL_BASE_DIR` and then `KERL_BASE_DIR` was described in the README?

**Comment by mrallen1** [comment]
Good idea - we need to do a better job in the documentation generally about documenting what variables are and what values they have by default.

**Comment by mrallen1** [comment]
Largely addressed by #178, so I'm going to close this issue.
