### ISSUE TITLE
Version compiled with kerl is more than 50% slower due to CFLAGS

### ISSUE THREAD

**Issue by josevalim** [kerl/kerl#131]
I have noticed that the Erlang compiled via kerl is more than 50% slower than the one compiled manually or installed via homebrew. After some debugging, I found the root cause to be setting CFLAGS:

https://github.com/kerl/kerl/blob/master/kerl#L436-L446

Unless I am misunderstanding the snippet above, it will compile all Erlang versions above R14 with CFLAGS=-O0, which drastically affects the VM performance. I personally don't understand why CFLAGS is being set, specially given the latest Erlang versions work great with GCC LLVM.

**Comment by mrallen1** [comment]
Agree. I don't know the historical context but seems like it was a workaround for Lion era compiler issues?

So we might as well get rid of it. If people want or need it, they can put it back into their `.kerlrc`
