### ISSUE TITLE
kerl deploy does not work in 1.1.0 due to an error in (local?) installation directory check

### ISSUE THREAD

**Issue by tatsuya6502** [kerl/kerl#134]
I just upgraded kerl from a very old version to the recent version (1.1.0) and I noticed `kerl deploy` command no longer works.

```
/home/tatsuya% kerl list installations
r16b03-1_hipe /home/tatsuya/erlang/r16b03-1_hipe
17.5.6.9_hipe /home/tatsuya/erlang/17.5.6.9_hipe
18.3.3_hipe_ds /home/tatsuya/erlang/18.3.3_hipe_ds
19.0-rc1_hipe_ds /home/tatsuya/erlang/19.0-rc1_hipe_ds

/home/tatsuya% kerl deploy centos6-hibari2 /home/tatsuya/erlang/19.0-rc1_hipe_ds 
ERROR: /home/tatsuya/erlang/19.0-rc1_hipe_ds does not appear to be an empty directory.
```

`deploy` command is supposed to copy an existing local installation to a remote location, and I think it is complaining the *local* installation is not empty.

It seems (though I have not verified) the following enhancement is causing the problem:
https://github.com/kerl/kerl/commit/d7a6709aeb63345d1fc6d86e058df7fd6e33dd4c#diff-75743bad0452412b658dabebd6b439f4R768

```shell
is_valid_install_path()
    ...

    # if the install directory exists,
    # do not allow installs into a directory
    # that is not empty
```

I think `deploy` command needs to perform different check for local installation because it must exist.

EDIT:
My environment:
- kerl 1.1.0
- Linux x86_64 (CentOS 6)

**Comment by mrallen1** [comment]
Yes, that's definitely a problem. If you drop back to tag 1.0, the directory check won't be there.

**Comment by mrallen1** [comment]
Opened #136 to solve this.

**Comment by mrallen1** [comment]
#136 was merged, so I'm going to close this.

**Comment by tatsuya6502** [comment]
Thank you for solving this!

**Comment by mrallen1** [comment]
Thanks for the bug report. I don't use that feature myself, so I would've never known it was broken otherwise. 🍬
