### ISSUE TITLE
kerl fails to install 18.3.3

### ISSUE THREAD

**Issue by michaelklishin** [kerl/kerl#135]
I have the following exported:

```
export KERL_BUILD_BACKEND=git
```

and attempt to run

```
kerl build "18.3.3" "18.3.3"
```

after updating release list. It fails with:

```
kerl build "18.3.3" "18.3.3"
/Users/antares/bin/kerl: line 968: [: 18.3: integer expression expected
Extracting source code
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Building Erlang/OTP 18.3.3 (18.3.3), please wait...
/Users/antares/bin/kerl: line 444: cd: /Users/antares/.kerl/builds/18.3.3/otp_src_18.3.3: No such file or directory
```

I use zsh on OS X 10.11.

**Comment by mrallen1** [comment]
Sorry! 

Should be fixed in b398b49

**Comment by mrallen1** [comment]
Give it a whirl and update your ticket if you get a chance. Thanks.

**Comment by michaelklishin** [comment]
Thank you, @mrallen1. master works as expected.

**Comment by michaelklishin** [comment]
Decided to re-open because 19-rc1 still suffers from the same issue:

```
kerl build 19.0-rc1 19.0-rc1
/Users/antares/bin/kerl: line 968: [: 19rc1: integer expression expected
```

**Comment by mrallen1** [comment]
Yep. Thanks - should be fixed in 992ca54

**Comment by mrallen1** [comment]
Did you get a chance to retry this?

**Comment by michaelklishin** [comment]
@mrallen1 I now only see

```
R10B-0 R10B-10 R10B-1a […] 17.4 17.5 18.0 18.1 18.2 18.2.1 18.3
```

in `kerl list releases` (even after updating releases a few times). Should I build 18.3.3 and 19-rc1 from git?

**Comment by mrallen1** [comment]
The environment variable `KERL_BUILD_BACKEND=git` needs to be set in your shell session in order for kerl to use the tags from the OTP github repo. It looks like you have it unset or set to `tarball`

**Comment by michaelklishin** [comment]
Ah, that was it. I can build 19.0-rc1 now, thank you!
