### ISSUE TITLE
kerl install failure should return non-zero process return code

### ISSUE THREAD

**Issue by jasonletbetter** [kerl/kerl#141]
An error during kerl install is returning a zero process return code but is expected to return a non-zero process return code so that failure can be detected by the caller.

Steps to reproduce (note: in this example the error is caused by changing the ownership of otp_installations file to root)
```
$ chown root ~/.kerl/otp_installations
$ kerl build 18.2.1 r18_2_1
$ kerl install r18_2_1
Installing Erlang/OTP 18.2.1 (r18_2_1) in /opt/erlang/r18_2_1...
/usr/local/bin/kerl: line 759: /Users/jrayled/.kerl/otp_installations: Permission denied
Fetching and installing manpages...
Verifying archive checksum...
Checksum verified (31e3d01cebb8761f94defd55fbf9f5fb)
Extracting manpages
You can activate this installation running the following command:
. /opt/erlang/r18_2_1/activate
Later on, you can leave the installation typing:
kerl_deactivate
$ echo $?
0
```

**Comment by mrallen1** [comment]
The solution would be in ensuring that appending the record on [this line](https://github.com/kerl/kerl/blob/master/kerl#L892) completes successfully. The success of the append (or write) is not currently tested, but it ought to be.

Thanks for the report.

**Comment by jasonletbetter** [comment]
no problem, thanks

**Comment by mrallen1** [comment]
#142 should address this.
