### ISSUE TITLE
KERL_ENABLE_PROMPT to true breaks prompt in zsh

### ISSUE THREAD

**Issue by rjcoelho** [kerl/kerl#154]
I'm using ohmyzsh/prezto and commit 759f73f59879a40279c7b5229e40d21f2c42231e breaks the prompt. It shows buildname twice "(17.5_hipe)(17.5_hipe)"

cat ~/.kerlrc
KERL_ENABLE_PROMPT=true

**Comment by mrallen1** [comment]
Thanks for the report.

**Comment by mazenharake** [comment]
@rjcoelho If you can do this in a terminal and copypaste the results here it would be great:
* Install a build somewhere then immediately activate it press enter then deactivate it.
* Install a build and activate it twice.

**Comment by rjcoelho** [comment]
```
~ ❯❯❯ . /usr/local/opt/kerl/17.5_hipe/activate
(17.5_hipe)(17.5_hipe)kerl_deactivate
~ ❯❯❯ . /usr/local/opt/kerl/17.5_hipe/activate
(17.5_hipe)(17.5_hipe). /usr/local/opt/kerl/17.5_hipe/activate
(17.5_hipe)(17.5_hipe)
```

**Comment by rjcoelho** [comment]
@mazenharake this was working well on previous kerl release. Thanks for the help

**Comment by mrallen1** [comment]
@rjcoelho Did you get a chance to test the fix in #156?

**Comment by mazenharake** [comment]
I downloaded and installed ohmyzsh to verify it. It works.

**Comment by rjcoelho** [comment]
@mazenharake applied 35ea605 and still have the issue using https://github.com/sorin-ionescu/prezto

```
~ ❯❯❯ . /usr/local/opt/kerl/17.5_hipe/activate
(17.5_hipe)(17.5_hipe). /usr/local/opt/kerl/17.5_hipe/activate
(17.5_hipe)(17.5_hipe)
```

This was a regression from previous version (1.3.1) to current (1.3.2)

**Comment by mazenharake** [comment]
Did you do a reinstallation?

**Comment by rjcoelho** [comment]
@mazenharake, you are correct. Patching the activation script solves the issue. Thanks!!

**Comment by mrallen1** [comment]
Great. Thanks for confirming.
