### ISSUE TITLE
"Configure failed" on my Red Hat Enterprise Linux 7.2

### ISSUE THREAD

**Issue by shintaroid** [kerl/kerl#157]
Any ideas? My RHEL 7.2 is on VirtualBox, following is output of "otp_build.log"

`/home/su/.kerl/builds/r18/otp_src_18.3/configure  --cache-file=/dev/null
Ignoring the --cache-file argument since it can cause the system to be erroneously configured
Disabling caching
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ld... ld
checking for GNU make... yes (make)
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for ranlib... ranlib
checking ERTS version... 7.3
checking OTP release... 18
checking OTP version... 18.3
configure: creating ./config.status
config.status: creating Makefile
config.status: creating make/output.mk
config.status: creating make/emd2exml
configure: configuring in lib
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/configure' --prefix=/usr/local  '--cache-file=/dev/null' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib
configure: creating ./config.status
configure: configuring in snmp/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/snmp/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/snmp/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for perl... perl
configure: creating ./config.status
config.status: creating mibs/Makefile
configure: configuring in common_test/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/common_test/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/common_test/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
configure: creating ./config.status
config.status: creating priv/x86_64-unknown-linux-gnu/Makefile
configure: configuring in erl_interface/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/erl_interface/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/erl_interface/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for ld.sh... no
checking for ld... ld
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for short... yes
checking size of short... 2
checking for int... yes
checking size of int... 4
checking for long... yes
checking size of long... 8
checking for void *... yes
checking size of void *... 8
checking for long long... yes
checking size of long long... 8
checking for ar... ar
checking for a BSD-compatible install... /usr/bin/install -c
checking how to create a directory including parents... /usr/bin/install -c -d
checking for gethostbyname in -lnsl... yes
checking for getpeername in -lsocket... no
checking for ANSI C header files... (cached) yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for uid_t in sys/types.h... yes
checking for pid_t... yes
checking for size_t... yes
checking whether time.h and sys/time.h may both be included... yes
checking for socklen_t usability... yes
checking for working alloca.h... yes
checking for alloca... yes
checking whether gcc needs -traditional... no
checking for working memcmp... yes
checking for dup2... yes
checking for gethostbyaddr... yes
checking for gethostbyname... yes
checking for gethostbyaddr_r... yes
checking for gethostbyname_r... yes
checking for gethostname... yes
checking for writev... yes
checking for gethrtime... no
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for select... yes
checking for socket... yes
checking for strchr... yes
checking for strerror... yes
checking for strrchr... yes
checking for strstr... yes
checking for uname... yes
checking for res_gethostbyname... no
checking for res_gethostbyname in -lresolv... yes
checking for clock_gettime... yes
checking for mixed cygwin or msys and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking for native win32 threads... no
checking for pthread_create in -lpthread... yes
checking for getconf... getconf
checking for Native POSIX Thread Library... yes
checking nptl/pthread.h usability... no
checking nptl/pthread.h presence... no
checking for nptl/pthread.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pthread/mit/pthread.h usability... no
checking pthread/mit/pthread.h presence... no
checking for pthread/mit/pthread.h... no
checking if we can add -Werror=return-type to WERRORFLAGS (via CFLAGS)... yes
configure: creating ./config.status
config.status: creating src/x86_64-unknown-linux-gnu/Makefile
config.status: creating src/x86_64-unknown-linux-gnu/eidefs.mk
config.status: creating src/x86_64-unknown-linux-gnu/config.h
configure: configuring in gs/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/gs/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/gs/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for prebuilt tcl/tk in tcl/binaries/x86_64_linux-gnu.tar.gz... not found
configure: creating ./config.status
config.status: creating tcl/x86_64-unknown-linux-gnu/Makefile
config.status: creating tcl/win32/Makefile
configure: configuring in megaco/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/megaco/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/megaco/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for flex... flex
checking for yywrap in -lfl... no
checking for yywrap in -ll... no
checking lex output file root... lex.yy
checking whether yytext is a pointer... no
checking for reentrant capable flex... yes
checking if we can add -Werror=return-type to CFLAGS (via CFLAGS)... yes
checking for usable Dynamic Erlang Driver configuration... yes
checking for perl... perl
configure: creating ./config.status
config.status: creating examples/meas/Makefile
configure: creating ./config.status
config.status: creating examples/meas/Makefile
config.status: creating src/flex/x86_64-unknown-linux-gnu/Makefile
configure: configuring in odbc/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/odbc/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/odbc/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for mixed cygwin or msys and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking whether gmake sets $(MAKE)... yes
checking for ld.sh... no
checking for ld... ld
checking for connect... yes
checking for gethostbyname... yes
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for sql.h... yes
checking for sqlext.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for struct sockaddr_in6.sin6_addr... yes
checking for memset... yes
checking for socket... yes
checking for native win32 threads... no
checking for pthread_create in -lpthread... yes
checking for getconf... getconf
checking for Native POSIX Thread Library... yes
checking nptl/pthread.h usability... no
checking nptl/pthread.h presence... no
checking for nptl/pthread.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pthread/mit/pthread.h usability... no
checking pthread/mit/pthread.h presence... no
checking for pthread/mit/pthread.h... no
checking for void *... yes
checking size of void *... 8
checking for odbc in standard locations... -L/usr/lib64
checking for SQLAllocHandle in -lodbc... yes
checking if we can add -Werror=return-type to CFLAGS (via CFLAGS)... yes
configure: creating ./config.status
config.status: creating c_src/x86_64-unknown-linux-gnu/Makefile
configure: configuring in wx/.
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/lib/wx/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' '--cache-file=/dev/null' '--srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/lib/wx/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking how to run the C preprocessor... gcc -E
configure: Building for linux-gnu
checking for mixed cygwin or msys and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for void *... yes
checking size of void *... 8
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
checking OpenGL/gl.h usability... no
checking OpenGL/gl.h presence... no
checking for OpenGL/gl.h... no
configure: Checking for OpenGL headers in /usr/X11R6
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
configure: Checking for OpenGL headers in /usr/local
checking GL/gl.h usability... no
checking GL/gl.h presence... no
checking for GL/gl.h... no
configure: WARNING: No OpenGL headers found, wx will NOT be usable
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
checking OpenGL/glu.h usability... no
checking OpenGL/glu.h presence... no
checking for OpenGL/glu.h... no
configure: WARNING: No GLU headers found, wx will NOT be usable
/home/su/.kerl/builds/r18/otp_src_18.3/lib/wx/./configure: line 5201: wx-config: command not found
checking for debug build of wxWidgets... checking for wx-config... no
checking for standard build of wxWidgets... checking for wx-config... (cached) no
configure: WARNING:
                wxWidgets must be installed on your system.

		Please check that wx-config is in path, the directory
		where wxWidgets libraries are installed (returned by
		'wx-config --libs' or 'wx-config --static --libs' command)
		is in LD_LIBRARY_PATH or equivalent variable and
		wxWidgets version is 2.8.4 or above.
checking if we can add -Werror=return-type to CFLAGS (via CFLAGS)... yes
checking if we can add -Werror=return-type to CXXFLAGS (via CFLAGS)... yes
configure: creating x86_64-unknown-linux-gnu/config.status
config.status: creating config.mk
config.status: creating c_src/Makefile
configure: configuring in erts
configure: running /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/erts/configure' --prefix=/usr/local  '--cache-file=/dev/null' 'ERL_TOP=/home/su/.kerl/builds/r18/otp_src_18.3' --cache-file=/dev/null --srcdir=/home/su/.kerl/builds/r18/otp_src_18.3/erts
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for library containing strerror... none required
checking OTP release... 18
checking OTP version... 18.3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ANSI C... (cached) none needed
checking for mixed cygwin or msys and native VC++ environment... no
checking for mixed cygwin and native MinGW environment... no
checking if we mix cygwin with any native compiler... no
checking if we mix msys with another native compiler... no
checking for getconf... getconf
checking for large file support CFLAGS... none
checking for large file support LDFLAGS... none
checking for large file support LIBS... none
checking if we can add -Werror=return-type to WERRORFLAGS (via CFLAGS)... yes
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for void *... yes
checking size of void *... 8
checking whether compilation mode forces ARCH adjustment... no
checking if VM has to be linked with Carbon framework... no
checking if we are building a halfword emulator (32bit heap on 64bit machine)... no
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for bison... bison -y
checking for perl5... no
checking for perl... /usr/bin/perl
checking whether ln -s works... yes
checking for ar... ar
checking for rm... /bin/rm
checking for mkdir... /bin/mkdir
checking for xsltproc... xsltproc
checking for fop... no
configure: WARNING: No 'fop' command found: going to generate placeholder PDF files
checking for xmllint... xmllint
checking for a BSD-compatible install... /usr/bin/install -c
checking how to create a directory including parents... /usr/bin/install -c -d
checking for extra flags needed to export symbols... -Wl,-export-dynamic
checking for sin in -lm... yes
checking for dlopen in -ldl... yes
checking for main in -linet... no
checking for openpty in -lutil... yes
checking for native win32 threads... no
checking for pthread_create in -lpthread... yes
checking for getconf... (cached) getconf
checking for Native POSIX Thread Library... yes
checking nptl/pthread.h usability... no
checking nptl/pthread.h presence... no
checking for nptl/pthread.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pthread/mit/pthread.h usability... no
checking pthread/mit/pthread.h presence... no
checking for pthread/mit/pthread.h... no
checking for kstat_open in -lkstat... no
checking for clock_gettime(CLOCK_MONOTONIC_RAW, _)... yes
checking for clock_gettime() with custom monotonic clock type... CLOCK_MONOTONIC
checking for clock_getres... yes
checking for clock_get_attributes... no
checking for gethrtime... no
checking for mach clock_get_time() with monotonic clock type... no
checking for clock_gettime in -lrt... yes
checking if SIGUSR1 and SIGUSR2 can be used... yes
checking if sigaltstack can be used... yes
checking for pthread.h... (cached) yes
checking for pthread/mit/pthread.h... (cached) no
checking sched.h usability... yes
checking sched.h presence... yes
checking for sched.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for pthread_spin_lock... yes
checking for sched_yield... yes
checking whether sched_yield() returns an int... yes
checking for pthread_yield... yes
checking whether pthread_yield() returns an int... yes
checking for pthread_rwlock_init... yes
checking for pthread_rwlockattr_setkind_np... yes
checking for PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP... yes
checking for pthread_attr_setguardsize... yes
checking whether pthread_cond_timedwait() can use the monotonic clock CLOCK_MONOTONIC for timeout... yes
checking for Linux futexes... yes
checking for pthread_setname_np... linux
checking for pthread_getname_np... linux
checking for short... yes
checking size of short... 2
checking for int... yes
checking size of int... 4
checking for long... yes
checking size of long... 8
checking for long long... yes
checking size of long long... 8
checking for __int128_t... yes
checking size of __int128_t... 16
checking for a working __sync_synchronize()... yes
checking for 32-bit __sync_add_and_fetch()... yes
checking for 64-bit __sync_add_and_fetch()... yes
checking for 128-bit __sync_add_and_fetch()... no
checking for 32-bit __sync_fetch_and_and()... yes
checking for 64-bit __sync_fetch_and_and()... yes
checking for 128-bit __sync_fetch_and_and()... no
checking for 32-bit __sync_fetch_and_or()... yes
checking for 64-bit __sync_fetch_and_or()... yes
checking for 128-bit __sync_fetch_and_or()... no
checking for 32-bit __sync_val_compare_and_swap()... yes
checking for 64-bit __sync_val_compare_and_swap()... yes
checking for 128-bit __sync_val_compare_and_swap()... no
checking for 32-bit __atomic_store_n()... yes
checking for 64-bit __atomic_store_n()... yes
checking for 128-bit __atomic_store_n()... no
checking for 32-bit __atomic_load_n()... yes
checking for 64-bit __atomic_load_n()... yes
checking for 128-bit __atomic_load_n()... no
checking for 32-bit __atomic_add_fetch()... yes
checking for 64-bit __atomic_add_fetch()... yes
checking for 128-bit __atomic_add_fetch()... no
checking for 32-bit __atomic_fetch_and()... yes
checking for 64-bit __atomic_fetch_and()... yes
checking for 128-bit __atomic_fetch_and()... no
checking for 32-bit __atomic_fetch_or()... yes
checking for 64-bit __atomic_fetch_or()... yes
checking for 128-bit __atomic_fetch_or()... no
checking for 32-bit __atomic_compare_exchange_n()... yes
checking for 64-bit __atomic_compare_exchange_n()... yes
checking for 128-bit __atomic_compare_exchange_n()... no
checking for a usable libatomic_ops implementation... no
checking whether default stack size should be modified... no
checking for void *... (cached) yes
checking size of void *... (cached) 8
checking for int... (cached) yes
checking size of int... (cached) 4
checking for long... (cached) yes
checking size of long... (cached) 8
checking for long long... (cached) yes
checking size of long long... (cached) 8
checking for __int64... no
checking size of __int64... 0
checking for __int128_t... (cached) yes
checking size of __int128_t... (cached) 16
checking whether byte ordering is bigendian... no
checking whether double word ordering is middle-endian... no
checking for gcc cmpxchg16b plain asm support... yes
checking for gcc pic cmpxchg16b plain asm support... yes
checking whether an emulator with smp support should be built... yes
checking for posix_fadvise... yes
checking for closefrom... no
checking linux/falloc.h usability... yes
checking linux/falloc.h presence... yes
checking for linux/falloc.h... yes
checking whether fallocate() works... yes
checking whether posix_fallocate() works... yes
checking whether the emulator should use threads... yes; thread support required and therefore forced
checking whether lock checking should be enabled... no
checking whether lock counters should be enabled... no
checking whether dirty schedulers should be enabled... no
checking whether dlopen() needs to be called before first call to dlerror()... no
checking whether the child waiter thread should be enabled... yes on SMP build, but not on non-SMP build
checking for kstat_open in -lkstat... (cached) no
checking for tgetent in -ltinfo... no
checking for tgetent in -lncurses... no
checking for tgetent in -lcurses... no
checking for tgetent in -ltermcap... no
checking for tgetent in -ltermlib... no
configure: error: No curses library functions found
configure: error: /bin/sh '/home/su/.kerl/builds/r18/otp_src_18.3/erts/configure' failed for erts`

**Comment by shintaroid** [comment]
It failed even it ran as root
![screenshot from 2016-07-28 16-26-52](https://cloud.githubusercontent.com/assets/19260845/17204409/524fe33a-54e0-11e6-94c2-0cbc8e47ea12.png)

**Comment by fenollp** [comment]
You are missing a dependency.

```
configure: error: No curses library functions found
```

**Comment by mrallen1** [comment]
Yep. You need something like `sudo yum install ncurses-devel` and then try again.

**Comment by shintaroid** [comment]
Thank you guys. You are right about the dependency, but in fact there are still other necessary dependencies missing like `java complier` and `unixODBC`. I have figured it out following [this](http://imperialwicket.com/aws-install-erlang-otp-on-amazon-linux/) article. Thank you guys!

**Comment by mrallen1** [comment]
Glad you got it installed. Technically only a curses library is required - the other libraries are 100% optional. The OTP build process will disable UnixODBC and the Java stuff if you don't have it installed when it configures itself.

**Comment by oanastratila** [comment]
I have the same issue, but installing the dependencies did not solve my problem
