### ISSUE TITLE
Put Configure options into a file inside the build

### ISSUE THREAD

**Issue by sanmiguel** [kerl/kerl#162]
When building, we should save the configure options we pass to `./configure` somewhere inside the build so that we can use them later.

This would enable us to:
- 1: add tooling to show you what options an erlang was configured with
- 2: potentially check it automatically when running a build with the same name as an existing one, and flag somehow that the options are different. Related to #158

**Comment by cuyler** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2101159/19090798/f18e86d4-8a34-11e6-8b65-04a7e7600f91.gif)

**Comment by cuyler** [comment]
I got this one.

**Comment by mrallen1** [comment]
Thanks!

**Comment by mrallen1** [comment]
Hey @cuyler ping on this? Have you had a chance to work on this?

**Comment by mrallen1** [comment]
I'm going to work on this issue soon. I know you will soon have your thoughts on way more important things than kerl.
