### ISSUE TITLE
Can't deactivate on stock FreeBSD

### ISSUE THREAD

**Issue by essen** [kerl/kerl#164]
This is probably the same as #93.

```
FreeBSD 10.1-RELEASE-p6 (GENERIC) #0: Tue Feb 24 19:00:21 UTC 2015
$ . ~/erlang/OTP-19.1.3/activate
$ kerl_deactivate
${PATH/...}: Bad substitution
```

"Use bash" is not a valid solution. I will work on a patch when I get a minute.

**Comment by mrallen1** [comment]
Thanks for the PR. Going to close this issue since #165 was merged.
