### ISSUE TITLE
No curses library functions found

### ISSUE THREAD

**Issue by bryanhunter** [kerl/kerl#17]
From a fresh install of Ubuntu 11.10 kerl failed to build R14B04. The build log shows:
configure: error: No curses library functions found
configure: error: /bin/bash '/home/bryanhunter/.kerl/builds/r14b04/otp_src_R14B04/erts/configure' failed for erts

I did a "sudo apt-get update" and tried to build with kerl again and it failed in the same way. 

I then did a "sudo apt-get -y install libncurses5-dev". I tried again after that, and everything builds successfully.

Let me know if you need more info (I have a VM snapshot where I can reproduce the problem). Next week I can poke around in kerl. If I'm not too out of my depth and I manage to fix it, I'll send you a pull request.

**Comment by alexshavelev** [comment]
@kdelchev also works for me

**Comment by mrallen1** [comment]
Something like #53 will make this much more transparent and dependable.

**Comment by mrallen1** [comment]
We've just merged #148 which should warn about this problem. Please reopen if needed.

**Comment by oladipo** [comment]
installing the ncurses library fixed it for me.

        sudo apt-get install libncurses5-dev libncursesw5-dev

**Comment by kentukynitemare** [comment]
@kdelchev @bryanhunter just helped me avert a crisis. Thanks all.

**Comment by Ajinkya-M** [comment]
sudo apt-get install libncurses5-dev
sudo apt-get install libncursesw5-dev
will work.

**Comment by heavychsilencov** [comment]
> sudo apt-get install libncurses5-dev
> sudo apt-get install libncursesw5-dev
> will work.

It's work! tnx!

**Comment by olivier2001** [comment]
Me I'm also facing the same erro while installing erlang26 on CentOS. 
configure: error: No curses library functions found
ERROR: /erlang_26/erts/configure failed!

ON centos7 what can be the correspondent package list above like: libncurses5-dev, libncursesw5-dev??
thanks you for help

**Comment by swziy** [comment]
I still face this issue on macOS Ventura 13.4. Do you have any advice?

**Comment by oladipo** [comment]
Use asdf Sent from my iPhoneOn Jul 4, 2023, at 7:27 AM, Szymon Witkowski ***@***.***> wrote:﻿
I still face this issue on macOS Ventura 13.4. Do you have any advice?

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna up the macOS version we use in CI (#448), and see if that surfaces any issue (we're going from `12` to `13`).

At the same time, we should probably, in a near future add a Darwin-specific `_check_required_pkgs` -like function (like we have for Linux) to try and at least signal these issues earlier.

**Comment by paulo-ferraz-oliveira** [comment]
All checks in that pull request seem Ok, with just up'ing the pull request version, and we're not doing any special curses inclusion I can see (at least in CI).

@swziy, do you have any options (e.g. from env. variables) specified that we don't see in the post (i.e. what's the output for `env | grep ^KERL_`)? At the same time, does it happen for a more recent Erlang/OTP version? We do mention we only support (explicitly) "current - 2", so that would be, at this moment, 26, 25 and 24.

**Comment by benwaffle** [comment]
You might also run in to this error if you mix a nix environment (e.g. flake.nix + direnv) with asdf
