### ISSUE TITLE
./kerl: line 443: [: : integer expression expected

### ISSUE THREAD

**Issue by zfbp** [kerl/kerl#170]

**Comment by zfbp** [comment]
$ ./kerl build 19.2 erl192
Verifying archive checksum...
Checksum verified (7cdd18a826dd7bda0ca46d1c3b2efca6)
Extracting source code
Building Erlang/OTP 19.2 (erl192), please wait...
./kerl: line 443: [: : integer expression expected
APPLICATIONS DISABLED (See: /var/app/.kerl/builds/erl192/otp_build_19.2.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed
 * orber          : No C++ compiler found

APPLICATIONS INFORMATION (See: /var/app/.kerl/builds/erl192/otp_build_19.2.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /var/app/.kerl/builds/erl192/otp_build_19.2.log)
 * documentation  :
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  The documentation can not be built.

**Comment by mrallen1** [comment]
Would you please post the output of `perl -v` on your system on this ticket?

**Comment by mrallen1** [comment]
@sanmiguel I think this issue points to the fact that we need to be more careful about assuming that perl and javac exist on a system (and have parseable output) - although Erlang itself will not build if Perl is not installed on a system. (Perl is used to assemble the opcode table for the BEAM emulator.)

**Comment by zfbp** [comment]
```sh
$ perl -v
-bash: perl: command not found

$ cat /etc/centos-release
CentOS release 6.6 (Final)
```

**Comment by crsuarez** [comment]
@mrallen1, I would suggest this change:
https://github.com/kerl/kerl/pull/173

**Comment by sanmiguel** [comment]
Hey there @zfbp !

I'm trying to reproduce this as far as possible, but it's proving difficult: the `configure` script *requires* `perl` in order to build e.g. the opcode table as @mrallen1 said before. When I remove `perl` from my `$PATH` here, I get the following error:

```
$ kerl build 19.2 erl192-2
Verifying archive checksum...
Checksum verified (7cdd18a826dd7bda0ca46d1c3b2efca6)
Extracting source code
Building Erlang/OTP 19.2 (erl192-2), please wait...
/vagrant/kerl/kerl: 383: /vagrant/kerl/kerl: perl: not found
/vagrant/kerl/kerl: 443: [: Illegal number:
Configure failed.
configure: running /bin/bash '/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib/configure' --prefix=/usr/local  '--cache-file=/dev/null' 'ERL_TOP=/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2' --cache-file=/dev/null --srcdir=/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib
configure: creating ./config.status
configure: configuring in snmp/.
configure: running /bin/bash '/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib/snmp/./configure' --prefix=/usr/local  '--prefix=/usr/local' 'ERL_TOP=/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2' '--cache-file=/dev/null' '--srcdir=/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib' --cache-file=/dev/null --srcdir=/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib/snmp/.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for perl... no_perl
configure: error: Perl is required to generate v2 to v1 mib converter script
configure: error: /bin/bash '/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib/snmp/./configure' failed for snmp/.
configure: error: /bin/bash '/home/vagrant/.kerl/builds/erl192-2/otp_src_19.2/lib/configure' failed for lib
```

Note that it's the same src archive checksum, I get a slightly different error from `kerl` (which we assume is because of differing `bash` versions between my machine and yours), but then the `configure` script throws a huge error because `perl` is required.

Did you do anything before the commands you pasted to set this up?

**Comment by crsuarez** [comment]
@sanmiguel try using this workaround and see if it works:
https://github.com/kerl/kerl/pull/173#pullrequestreview-18732086.
