### ISSUE TITLE
Embed the current kerl version into the activation script to potentially warn of staleness

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#175]
Long lived Erlang installations may have problems/conflicts with behaviors provided by newer kerl installations.  To make this condition "detectable" we could add the current kerl version string into the activation script.  When the activation script is executed, we could check the current kerl installation (if there is one) and provide a warning.

Something like
```bash
install_kerl_ver="1.2.3"

if [ -x kerl ]; then
  KERLVER=`kerl version`
else
  KERLVER=
fi

# later

if [ -z $KERLVER && $KERLVER -ne $install_kerl_ver ]; then
  echo "WARNING: This Erlang installation appears to be stale. Please consider reinstalling." # or something
fi
```

**Comment by rciorba** [comment]
:+1:  Good idea. If this becomes a PR please ping me so I can update the fish part as well.

**Comment by sanmiguel** [comment]
I think we can take this a bit further.

Things I wish we'd had stored alongside a build (or installation) before include:
 - configuration flags during build (`KERL_CONFIGURE_OPTIONS` et al)
 - timestamp of build
 - exact kerl command used to create it (i.e. was it `kerl build git ...` or from a tar or...)

which leads me to think we should capture every kerl-related variable that was set in the env at the time.

I wonder if we should be capturing this during both build and install processes?

If we're smart about how we store this data, we can create some tooling within kerl to report it to the user and even add commands such as "build 19.2.2 in the exact same way as I built 19.2.1"

**Comment by mrallen1** [comment]
OK, we could extend the "metadata file" stuff we have now to do all this, I think.

**Comment by lrascao** [comment]
did the 'configuration flags during build' idea end up in some release? i've found myself wishing i had that recently

**Comment by mrallen1** [comment]
That was added in #177 which was merged on February 2, release 1.4.0. So if you're using a newer version than that, you should have the build information in the installation directory.

**Comment by lrascao** [comment]
on 1.6.0 i see:
````
----------
The current active installation is:
/Users/luis.rascao/Projects/erlang/17.4-hipe
There's no Dialyzer PLT for the active installation
**The build options for the active installation are not available.**
````

i'm probably missing something

**Comment by sanmiguel** [comment]
When did you build that Erlang version? The config options won't be
available if it was built with an older kerl.

But either way, I don't think we currently capture the kerl version in
those build options when we do capture them, and we should.

**Comment by lrascao** [comment]
not sure, i'll rebuild one and check that

**Comment by lrascao** [comment]
ok, it's working fine, jzust checked OTP20 (that i built recently) and kerl status tells me:
````
The build options for the active installation are:

 --with-ssl=/usr/local/opt/openssl
````
thanks!

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, do you think this is still worth it? Or could we close it?
