### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by fenollp** [kerl/kerl#182]
It would help development, testing & maintenance to have a test suite.
Travis CI has something called a build matrix: it allows starting more than one build per push/tag/pr.

I suggest adding a .travis.yml file that specifies a build matrix for 64bit linux & osx that tests all known OTP versions & some combination of wx, terminfo, openssl versions.
For windows there's appveyor.

The main idea is to have regression testing.

**Comment by sanmiguel** [comment]
Hi @fenollp :)

There was talk before about getting something working on Travis-CI, a while back, but I now don't remember why we didn't get anywhere with it...

I've made a start over on a branch, for this PR https://github.com/kerl/kerl/pull/183

But for now I can't seem to get Travis to recognise that I have auth'd it to access the repo, so I'll continue over in my fork for now.
