### ISSUE TITLE
Modify 'installations' subcommands

### ISSUE THREAD

**Issue by sanmiguel** [kerl/kerl#184]
Maybe it's just me, but I'm forever caught out by it being e.g. `kerl list installations` not `kerl list installs`, or `kerl delete install foo`.

**Comment by fenollp** [comment]
you should add the completion files

**Comment by sanmiguel** [comment]
Not an unreasonable point...

I do have them set up but don't always bother hitting `<Tab>` for e.g. `kerl list installs` (which obviously doesn't work...)

Anyway I guess this issue was just me whining. Closing.
