### ISSUE TITLE
Version number management

### ISSUE THREAD

**Issue by sanmiguel** [kerl/kerl#188]
Folks, we need a better plan for managing which version `kerl` reports. I've just realised we haven't bumped the internal `KERL_VERSION` since `1.3.4`...

I'm not sure what the best way to go about this is, since we just hard-code the version string inside the script anyway. I might be over-thinking it but maybe we can install a hook to bump the version string immediately before tagging?

@mrallen1 thoughts?

**Comment by mrallen1** [comment]
I like the idea of using a hook to automate this but I'm not exactly sure how to make it fool proof.

**Comment by jadeallenx** [comment]
yeah i manually update it - there's some GHA stuff to automate a new tag and stuff but I don't feel like that amount of effort is worth it
