### ISSUE TITLE
Incorrect docs symlinks in some cases

### ISSUE THREAD

**Issue by sanmiguel** [kerl/kerl#193]
In at least some cases, the symlinks we create to `html` and `man` dirs are incorrect:

```
./html -> /Users/sanmiguel/kerl/19.2.3/lib/erlang/doc
./man -> /Users/sanmiguel/kerl/19.2.3/lib/erlang/man
```

These should be

```
./html -> /Users/sanmiguel/kerl/19.2.3/lib/doc
./man -> /Users/sanmiguel/kerl/19.2.3/lib/man
```

**Comment by mrallen1** [comment]
OK, should be easy to fix at least :)

**Comment by sanmiguel** [comment]
My hesitation to fix this is that we don't appear to have changed anything around how these links are made for a while, but I'm *sure* this used to work just fine....

**Comment by sanmiguel** [comment]
Basically I don't know why this stopped working, and that scares me. :)

**Comment by mrallen1** [comment]
I bet older OTP releases had them where we're linking and the newer ones have them we're this ticket points to.  So we'll just have to figure out what release we're installing and make the links as appropriate.

**Comment by sanmiguel** [comment]
FWIW I've had this happen on releases of at least R16 vintage...

Oh but I wonder if it's related to the KERL_BUILD_BACKEND changes? We used
to always use `kerl build git ...` (which built the *incorrect* docs
mostly) - maybe the new way of building via KERL_BUILD_BACKEND puts them in
a slightly different place?

/sanmiguel

**Comment by mrallen1** [comment]
I bet older OTP versions have the files in different places, so we'll have to figure out what release we're installing and adjust accordingly. 

    On Tuesday, February 28, 2017 11:44 AM, sanmiguel <notifications@github.com> wrote:
 

 My hesitation to fix this is that we don't appear to have changed anything around how these links are made for a while, but I'm sure this used to work just fine....—
