### ISSUE TITLE
Replace env var crunching with neat xargs trick

### ISSUE THREAD

**Issue by sanmiguel** [kerl/kerl#194]
Use the trick here: https://gist.github.com/judy2k/7656bfe3b322d669ef75364a46327836

to be able to avoid having to manually touch every single env var in https://github.com/kerl/kerl/blob/master/kerl#L51-L138

**Comment by mrallen1** [comment]
This is a neat trick too: https://stackoverflow.com/a/30969768 

Might be relevant!

**Comment by paulo-ferraz-oliveira** [comment]
> to be able to avoid having to manually touch every single env var in https://github.com/kerl/kerl/blob/master/kerl#L51-L138

The file pointed too has since changed quite a lot. I'll try to get a reference as to the one you were mentioning 6+ years ago.

**Comment by paulo-ferraz-oliveira** [comment]
I could simplify it via

```sh
act_on_kerl_cfgs() {
    # $1: action - cache | restore (default)

    for _KERL_CFG in ${_KERL_CFGS_AUX}; do
        if [ $1 == cache ]; then
            eval "_KERL_CFG_VAR=\$${_KERL_CFG}"
            eval "_KERL_TARGET_VAR=__${_KERL_CFG}"
        elif [ $1 == restore ]; then
            eval "_KERL_CFG_VAR=\$__${_KERL_CFG}"
            eval "_KERL_TARGET_VAR=${_KERL_CFG}"
        fi
        if [ -n "${_KERL_CFG_VAR}" ]; then
            eval "$_KERL_TARGET_VAR=$_KERL_CFG_VAR"
        fi
    done
}
```

instead of hand-picked variable names we save them with a `__` prefix to later recover them, in the same fashion as the code does, these days, only the list to maintain becomes

```sh
_KERL_CFGS="\
OTP_GITHUB_URL=https://github.com/erlang/otp \
KERL_CONFIGURE_OPTIONS= \
KERL_CONFIGURE_APPLICATIONS= \
KERL_CONFIGURE_DISABLE_APPLICATIONS= \
KERL_SASL_STARTUP= \
KERL_DEPLOY_SSH_OPTIONS= \
KERL_DEPLOY_RSYNC_OPTIONS= \
KERL_INSTALL_MANPAGES= \
KERL_INSTALL_HTMLDOCS= \
KERL_BUILD_PLT= \
KERL_BUILD_DOCS= \
KERL_DOC_TARGETS=chunks \
KERL_BUILD_BACKEND= \
KERL_RELEASE_TARGET= \
"

which hopefully is much simpler to read. I'll pr soon, when then outstanding requests are dealt with.
