### ISSUE TITLE
Kerl should optionally install docsh

### ISSUE THREAD

**Issue by mrallen1** [kerl/kerl#210]
[docsh](https://github.com/erszcz/docsh) is a project which loads Erlang documentation into the REPL.

What would it take to install docsh via kerl?

Probably an upstream tarball and some kind of installation script?

**Comment by erszcz** [comment]
I'm glad to see this happening!

First, we would need to introduce a new flag similar to `KERL_INSTALL_MANPAGES` in `.kerlrc`, i.e. `KERL_INSTALL_DOCSH`. The second step is a procedure for fetching/cloning and building the project.

I'm not up to date with Kerl or `activate` script internals, but last time I checked it did not tweak `ERL_LIBS` env variable or the Erlang code search path in any way - if that's still the case, the best way to enable docsh would be its [`install.sh` script which sets up `$HOME/.erlang` and `user_default.erl`](https://github.com/erszcz/docsh#installation). Alternatively, if Kerl in the meantime has grown a way to modify the code path, we could plug into this mechanism.

I'm willing to work on this when time permits, but can't declare a schedule. If somebody's willing to volunteer - please don't hesitate ;)

**Comment by mrallen1** [comment]
Closing this, since we merged #213
