### ISSUE TITLE
Kerl should optionally install ferd's erlang-history patch/hack

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#211]
[erlang-history](https://github.com/ferd/erlang-history) is a project which adds persistent REPL command history to your erlang sessions.

What would it take to support this in kerl?

**Comment by mrallen1** [comment]
#214 sort of addresses this for OTP 20. Still need support for 17, 18, 19...

**Comment by sanmiguel** [comment]
Once it's merged, #214 only addresses `activate` not `activate.csh` or `activate.fish` so we need to remember to add support for this there too.

**Comment by paulo-ferraz-oliveira** [comment]
Is this still relevant? What would be missing?

**Comment by jadeallenx** [comment]
No need for this now.
