### ISSUE TITLE
kerl: not working on Solaris x86

### ISSUE THREAD

**Issue by eshikafe** [kerl/kerl#215]
Hello,

Please how do I fix the following kerl error?
kerl list releases
/export/home/vagrant/kerl: syntax error at line 153: `KERL_SYSTEM=$' unexpected
uname -a
SunOS vagrant-solaris10.dev 5.10 Generic_147148-26 i86pc i386 i86pc

It runs correctly in the terminal:

KERL_SYSTEM=$(uname -s)
echo $KERL_SYSTEM
SunOS

**Comment by eshikafe** [comment]
Resolved with KERL_SYSTEM=`uname -s`

**Comment by mrallen1** [comment]
Is Solaris' default shell not bash?

**Comment by eshikafe** [comment]
I had the same error using sh, ksh and bash

**Comment by eshikafe** [comment]
Using bash on Ubuntu and Solaris 10 (vagrant box) gives different results.
It works on Ubuntu but it fails on Solaris.

On Ubuntu 16.04: it works
austin@srap01:~$ kerl list releases
R10B-0 R10B-10 R10B-1a R10B-2 R10B-3 R10B-4 R10B-5 R10B-6 R10B-7 R10B-8 R10B-9 R11B-0 R11B-1 R11B-2 R11B                         -3 R11B-4 R11B-5 R12B-0 R12B-1 R12B-2 R12B-3 R12B-4 R12B-5 R13A R13B01 R13B02-1 R13B02 R13B03 R13B04 R13                         B R14A R14B01 R14B02 R14B03 R14B04 R14B_erts-5.8.1.1 R14B R15B01 R15B02 R15B02_with_MSVCR100_installer_f                         ix R15B03-1 R15B03 R15B R16A_RELEASE_CANDIDATE R16B01 R16B02 R16B03-1 R16B03 R16B 17.0-rc1 17.0-rc2 17.0                          17.1 17.3 17.4 17.5 18.0 18.1 18.2.1 18.2 18.3 19.0 19.1 19.2 19.3 20.0
Run '/home/austin/kerl update releases' to update this list from erlang.org
austin@srap01:~$ echo $SHELL
/bin/bash
austin@srap01:~$ cd solaris-10-x86-box/

on Solaris 10 x86 vagrant box: it fails.
austin@srap01:~/solaris-10-x86-box$ vagrant ssh
Last login: Sat Jul  8 12:05:43 2017 from 10.0.2.2
Oracle Corporation      SunOS 5.10      Generic Patch   January 2005
-bash-3.2$ echo $SHELL
/usr/bin/bash
-bash-3.2$ ls -l
total 6
-rw-r--r--   1 vagrant  vagrant      136 Aug  6  2014 local.cshrc
-rw-r--r--   1 vagrant  vagrant      157 Aug  6  2014 local.login
-rw-r--r--   1 vagrant  vagrant      174 Aug  6  2014 local.profile
-bash-3.2$ curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48551  100 48551    0     0  43040      0  0:00:01  0:00:01 --:--:-- 64476
-bash-3.2$ chmod a+x kerl
-bash-3.2$ PATH=$PATH:`pwd`
-bash-3.2$ kerl list releases
/export/home/vagrant/kerl: syntax error at line 153: `KERL_SYSTEM=$' unexpected
-bash-3.2$

**Comment by eshikafe** [comment]
See error on Solaris 11.3

austin@srap01:~/solaris-11.3-x86-box$ vagrant ssh
Password:
Last login: Tue May 17 23:50:43 2016 on console
Oracle Corporation      SunOS 5.11      11.3    September 2015
vagrant@solaris:~$
vagrant@solaris:~$
vagrant@solaris:~$ echo $SHELL
/usr/bin/bash
vagrant@solaris:~$ curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 48551  100 48551    0     0  33998      0  0:00:01  0:00:01 --:--:-- 48213
vagrant@solaris:~$ ls
kerl
vagrant@solaris:~$ chmod a+x kerl
vagrant@solaris:~$ PATH=$PATH:`pwd`
vagrant@solaris:~$ kerl list releases
sed: illegal option -- r

Run '/export/home/vagrant/kerl update releases' to update this list from erlang.org
vagrant@solaris:~$ kerl update releases
sed: illegal option -- r
The available releases are:

vagrant@solaris:~$ uname -s
SunOS
vagrant@solaris:~$

**Comment by mrallen1** [comment]
So Solaris 11 works with the `$(command)` syntax but probably needs the same sed flags as FreeBSD in line 158.  Seems like Solaris 10 has a really really old version of bash or maybe it's set with some kind of strict `sh` compatibility setting enabled.

**Comment by eshikafe** [comment]
You are absolutely correct mrallen. Really strange that even the latest Solaris is still lacking these time-saving options.

**Comment by mrallen1** [comment]
@sanmiguel suggested that because kerl starts with `#!/bin/sh` it starts Solaris bash in some kind of compatibility mode with `sh` which doesn't understand or use the `$(foo)` constructions.

**Comment by mrallen1** [comment]
OK, sorry it took a while to get back to this - I don't have a Solaris system.  But I learned the `/bin/sh` on Solaris isn't POSIX compliant.  However, the Korn shell on the system is, so we could potentially try something like

```shell
if [ `uname -s` == "SunOS" -a -n "$POSIX_SHELL" ]; then
   $POSIX_SHELL=1 /usr/bin/ksh $0 $@
fi
```

as a solution.

**Comment by mrallen1** [comment]
OK, I'm going to close this ticket for now. Please open a new one (or reopen this one) if you want to advance this.
