### ISSUE TITLE
A note about Fedora 16

### ISSUE THREAD

**Issue by robertoaloi** [kerl/kerl#22]
Having recently installed Erlang via kerl on a Fedora machine I've noticed the following, which might be of help for someone.

By default, the sudoers configuration for Fedora doesn't keep the value of the $HOME variable, which is used by kerl script.

This means that if you run the `kerl build` command from normal user, sudoing just to run the `kerl install` command, this will fail, kerl not being able to find any build:

<pre>
$ ./kerl build R15B01 r15b01
Getting the available releases from erlang.org...
[...]
Agner has been successfully built
$ sudo ./kerl install r15b01 /opt/erlang/r15b01
No build named r15b01
$ ./kerl build R15B01 r15b01
There's already a build named r15b01
./kerl list builds
R15B01,r15b01
</pre>

I understand this is not a *bug* in kerl, but it would be useful to provide a more verbose output to the user, for example showing *where* kerl is looking for builds.

**Comment by mrallen1** [comment]
I think dying with an error message if $HOME is unset is ok. I know this ticket is *really* old but was this workaround ever merged?

**Comment by mazenharake** [comment]
Pull request available for the small fix.

**Comment by mrallen1** [comment]
Please open it. Thanks!

**Comment by mazenharake** [comment]
This was merged, perhaps we can close this ticket now? Sorry for the confusion.
