### ISSUE TITLE
Unable to install OTP19 (Ubuntu AWS) - Configure Failed

### ISSUE THREAD

**Issue by syberkitten** [kerl/kerl#220]
ENV
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
``

Building Erlang/OTP 19.3 (19.3), please wait...
Configure failed.
checking whether lock counters should be enabled... no
checking whether dlopen() needs to be called before first call to dlerror()... no
checking for kstat_open in -lkstat... (cached) no
checking for tgetent in -ltinfo... no
checking for tgetent in -lncurses... no
checking for tgetent in -lcurses... no
checking for tgetent in -ltermcap... no
checking for tgetent in -ltermlib... no
configure: error: No curses library functions found
configure: error: /bin/bash '/home/ubuntu/.kerl/builds/19.3_EMQ/otp_src_19.3/erts/configure' failed for erts

Please see /home/ubuntu/.kerl/builds/19.3_EMQ/otp_build_19.3.log for full details.

Tried: apt-get update / upt-get upgrade
and installing openSSL and other ilbraries, no change.

**Comment by mrallen1** [comment]
For ubuntu, this is the list of debs that need to be installed prior to trying to build Erlang: 

`sudo apt install libssl-dev automake autoconf libncurses5-dev gcc`

**Comment by mrallen1** [comment]
You're missing a curses library. That's why the build is failing.

**Comment by fenollp** [comment]
It says it right there
```
...
configure: error: No curses library functions found
...
```
@syberkitten what are you asking for / expecting Kerl to do here?

@mrallen1 Maybe a build failure can be detected and this command can be suggested if on ubuntu:
`sudo apt install libssl-dev automake autoconf libncurses5-dev gcc`
? I would quite like that :)

**Comment by fenollp** [comment]
Hah should have suggested this at https://github.com/kerl/kerl/issues/221 sorry

**Comment by mrallen1** [comment]
No worries. :)

**Comment by mrallen1** [comment]
Going to close this since I merge #222 today. Please open a new ticket if it's still broken or an issue. Thanks.
