### ISSUE TITLE
Emphasize need for homebrew perl (>5.22?) on MacOS 10.13

### ISSUE THREAD

**Issue by nalundgaard** [kerl/kerl#233]
Related to #232, I'd like to propose that the README or script output (console, not install log) of kerl be amended to note whether or not the patch applications that appear to require newer versions of perl were applied. This is going to be a hard necessity for building pre-20 Erlangs going forward, and I suspect it will catch more people than just me.

**Comment by nalundgaard** [comment]
I think I can close this, right @mrallen1?

**Comment by mrallen1** [comment]
Thanks for opening it, but I don't think we need it.
