### ISSUE TITLE
MacOS with zsh build issue

### ISSUE THREAD

**Issue by baldmountain** [kerl/kerl#239]
I ran into an issue building erlang with MacOS (High Sierra) running zsh and oh-my-zsh. The error was:

```bash
 MAKE	depend
/bin/sh: line 0: cd: erts/emulator: No such file or directory
make: *** [depend] Error 1
```

This is caused by how zsh handles the CDPATH environment variable. If you don't have '.' in your CDPATH and you run:

```bash
cd erts/emulator
```

which the Makefile does, the cd will fail. Adding '.' to your CDPATH fixes the issue. If you don't want '.' in your CDPATH you can run:

```bash
export CDPATH=$CDPATH:.
```

and kerl builds will finish without errors.

I thought you might want to add a note in the README about this.

**Comment by mrallen1** [comment]
Thanks for the note!

@sanmiguel you're the resident zsh nerd. Shouldn't we automatically handle this for zsh invocations?

**Comment by mrallen1** [comment]
@sanmiguel ping
