### ISSUE TITLE
Warning messages but built successfully?

### ISSUE THREAD

**Issue by pernghh** [kerl/kerl#252]
Hi I have try to build Erlang several times and the build result is worked for me, but I am wondering why I see following warning messages and can't find a way to make it disappear. Dues to I afraid there might be some side effect related to these warning, I want make these warning gone.  

I am using ubuntu 14.04. And already try to add following packages:
sudo apt install plplot12-driver-wxwidgets
sudo apt install libxml2-utils

Does anybody know what am I missing components for build Erlang? 

Thank you~~~

Eric

`
vagrant@vagrant-ubuntu-trusty-64:~$ ./kerl build 19.3 19.3
Verifying archive checksum...
Checksum verified (a8c259ec47bf84e77510673e1b76b6db)
Building Erlang/OTP 19.3 (19.3), please wait...
APPLICATIONS INFORMATION (See: /home/vagrant/.kerl/builds/19.3/otp_build_19.3.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /home/vagrant/.kerl/builds/19.3/otp_build_19.3.log)
 * documentation  :
 *                  xmllint is missing.
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 19.3 (19.3) has been successfully built
`

**Comment by mrallen1** [comment]
Those messages are telling you that the [wx][1] UI toolkit, [xmllint][2], and [fop][3] don't seem to be known to the Erlang build system.  Due to that, applications which use wx like [observer][4] won't work from your Erlang build, and the Erlang documentation will not be built from the source package.

With respect to `xmllint` if you type `xmllint` from a shell prompt what happens?

[1]: https://wiki.wxwidgets.org/Installing_and_configuring_under_Ubuntu
[2]: https://packages.ubuntu.com/trusty-updates/libxml2-utils
[3]: https://packages.ubuntu.com/trusty-updates/fop
[4]: http://pic002.cnblogs.com/images/2012/40191/2012070607475843.png

**Comment by pernghh** [comment]
Thanks,

I try add some additional package. The fop & xmllint warnning is gone.
the new package I add is: 
sudo apt -y install openjdk-8-jre

I am not sure whether this package
sudo apt -y install libxml2-utils
make the warning gone also.

I will keep trying to find how to fix the wx warning?

It seems doesn't have a simple package for apt-get? 

Thank you~~

Eric

Current message:

Building Erlang/OTP 19.3 (19.3), please wait...
APPLICATIONS INFORMATION (See: /home/vagrant/.kerl/builds/19.3/otp_build_19.3.log)
 * wx             : wxWidgets not found, wx will NOT be usable

Erlang/OTP 19.3 (19.3) has been successfully built

**Comment by pernghh** [comment]
Hi, 

I try to add package:
sudo apt-get install wx2.8-headers libwxgtk2.8-0 libwxgtk2.8-dev

and do the link:
cd /usr/include
sudo ln -sv wx-2.8/wx wx

This time, I got another error?

vagrant@vagrant-ubuntu-trusty-64:~$ ./kerl build 19.3 19.3
Verifying archive checksum...
Checksum verified (a8c259ec47bf84e77510673e1b76b6db)
Extracting source code
Building Erlang/OTP 19.3 (19.3), please wait...
APPLICATIONS INFORMATION (See: /home/vagrant/.kerl/builds/19.3/otp_build_19.3.lo                                 g)
 * wx             : Can not link the wx driver, wx will NOT be useable

Erlang/OTP 19.3 (19.3) has been successfully built

I check the related information in
http://erlang.org/doc/installation_guide/INSTALL.html

It said:
wxWidgets -- Toolkit for GUI applications. Required for building the wx application. At least version 3.0 of wxWidgets is required.

I get the package information in wiki is 2.8? 
Is this related to this warning? Or just because I am using VM to build erlang?

Thank you~~

Eric

**Comment by pernghh** [comment]
I am not sure about the wx issue. 
I recreate the VM image and I got error when I try to install wx package 3+!
 
wx-common : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed

It looks like I can't use wx on ubuntu 14.04?

**Comment by mrallen1** [comment]
I'm afraid I can't help you with that problem - you'll have to ask for help from the wx community.

**Comment by pernghh** [comment]
Thanks,

It seem the wx's issue. I also try to got a old build script to build Erlang 17.3 source from internet. It worked before as the following reply and I got error when compiling wx related part. I need to turn off wx feature to make codes compiled successfully.
 
I will try figure out the wx problem from wx site. 

Thank you~~~

Eric

**Comment by mrallen1** [comment]
Haven't heard back for a while, so I'm going to close this issue. Feel free to open a new one if you need help.
