### ISSUE TITLE
Is it possible to build without documentation building? 

### ISSUE THREAD

**Issue by DmytroStepaniuk** [kerl/kerl#253]
I'm just wondering if there any opportunity to build erlang using `kerl` without building documentation for it? Thx!

**Comment by mrallen1** [comment]
If you don't set `KERL_BUILD_DOCS` then kerl will not build docs.  The warning messages that come out of the configuration step can be ignored if you didn't set the environment variable as documented [here][1].

[1]: https://github.com/kerl/kerl#building-documentation

**Comment by mrallen1** [comment]
Haven't heard back for a while, so I'm going to close this issue. Feel free to open a new one if you're still having trouble.
