### ISSUE TITLE
build names should have aliases

### ISSUE THREAD

**Issue by dcgibbons** [kerl/kerl#254]
Aliases should be provided for different build names so that multiple names can be used to refer to the exact same build.

For example, imagine this usage:
```sh
$ kerl build 20.1.7.1 erlang_20.1.7.1
...

$ kerl alias erlang_20.1.7.1 erlang_20.1
$ kerl alias erlang_20.1.7.1 20.1
```

What's the use case for this? A common scenario for me is that build systems at my organization, or from other users, do an automatic kerl check to see if the specific erlang installation the software wants is present; if not it uses kerl to install it. The naming convention used may not match the one I have already used. Certainly another installation works, but it's a waste of time and space.

**Comment by fenollp** [comment]
I'm more against than for this feature request for 2 reasons:
* it does not sound like the solution to your problem lies in Kerl
* detecting cycles in /bin/sh sounds like pain

**Comment by nalundgaard** [comment]
I agree, I think this isn't worth the effort given the nature of this tool. Better to formalize a convention with in the organization you're a part of, or just have multiple builds if not.

**Comment by mrallen1** [comment]
So should I close this?

**Comment by mrallen1** [comment]
Closing. Please open a new ticket if this is still a concern.
