### ISSUE TITLE
Compile with LibreSSL on High Sierra

### ISSUE THREAD

**Issue by siegfried** [kerl/kerl#257]
Although Apple stopped shipping OpenSSL, but on High Sierra LibreSSL is shipped with the system. Is it possible to compile Erlang using LibreSSL instead of OpenSSL installed by Homebrew? I'm asking this because OpenSSL does not support Chacha20.

**Comment by mrallen1** [comment]
Yeah I saw that too. I probably won't have time to tackle that for a while, especially making it work on OTP versions that aren't 20.x (IIRC, Ericsson added patches for Apple LibreSSL support reasonably recently.)

**Comment by mrallen1** [comment]
Looks like this is the 'official' LibreSSL enabling patch from upstream

https://github.com/erlang/otp/commit/7a033e602d31a661d6891fc2ce8ccc7589186bbe

That patch is already shipped in >=20, but not anything older. It's not clear to me how much work would be involved getting that patch backported to much older OTPs.

and here's another one that disables bad padding for LibreSSL that just got commited a few days ago

https://github.com/erlang/otp/commit/b5b6c7695c5377b5aa474d8620df7c3e9a1ba629

That code isn't even tagged for a release yet, but seems pretty important.

**Comment by mrallen1** [comment]
So maybe the idiom should be we support building from LibreSSL on OTP 20 but not anything older.

**Comment by mrallen1** [comment]
Looks like the patch referenced above for Libre was shipped in 20.3, so it seems like 20.3 (or later) would be the only reasonable target for kerl to support with Libre.

**Comment by mrallen1** [comment]
I'm expecting OTP 21 to release around the end of May, possibly to coincide with Code Beam Stockholm.

**Comment by paulo-ferraz-oliveira** [comment]
OTP's support (and thus `kerl`'s, which follows it) no longer looks at 20-. This seems to no longer be an issue in more recent Erlang versions, but an isolated thing around the time a specific release came out. (similar thing happened with `autoconf`, OTP, and `kerl` a few years back, I believe)

**Comment by jadeallenx** [comment]
Let's close this. Thanks for triaging
