### ISSUE TITLE
Unable to install Erlang using kerl in centos 6

### ISSUE THREAD

**Issue by satishkumarkt** [kerl/kerl#259]
Hi I am trying to install CouchDB 2.0 on centos for this it requires Erlang 15 above version

while I am trying to install  Erlang using kerl it gives an error.

Can anyone please help me I am new to this

ERROR
--------------------------------

Building Erlang/OTP 19.2 (19.2), please wait...
which: no dpkg in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/cpanel/composer/bin:/home/friends/bin)
APPLICATIONS DISABLED (See: /home/friends/.kerl/builds/19.2/otp_build_19.2.log)
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /home/friends/.kerl/builds/19.2/otp_build_19.2.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /home/friends/.kerl/builds/19.2/otp_build_19.2.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.

Crash dump is being written to: erl_crash.dump...done

**Comment by mrallen1** [comment]
There's not enough detail here to solve your build issue.  Will you please post the last 20 or so lines from your kerl build log?

     $ tail -20 /home/friends/.kerl/builds/19.2/otp_build_19.2.log

You ought to be aware that CentOS ships a crippled OpenSSL library without elliptic curve support, so you have to tell Erlang to not try and use those crypto routines or Erlang will be broken on your system. (See #212 for details.)

**Comment by satishkumarkt** [comment]
last 20  lines from your kerl build 

[friends@s198-12-149-25 ~]$ tail -20 /home/friends/.kerl/builds/19.2/otp_build_19.2.log
gmake[2]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe'
Makefile:72: warning: overriding commands for target `clean'
/home/friends/.kerl/builds/19.2/otp_src_19.2/make/otp_subdir.mk:29: warning: ignoring old commands for target `clean'
=== Entering application hipe
gmake[3]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/rtl'
gmake[4]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/main'
 VSN    hipe.hrl
gmake[4]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/main'
 ERLC   ../ebin/hipe_rtl.beam
Failed to create aux thread

Crash dump is being written to: erl_crash.dump...done
/bin/sh: line 1: 30433 Aborted                 erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl.erl
gmake[3]: *** [../ebin/hipe_rtl.beam] Error 134
gmake[3]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/rtl'
gmake[2]: *** [opt] Error 2
gmake[2]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe'
gmake[1]: *** [opt] Error 2
gmake[1]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib'
gmake: *** [secondary_bootstrap_build] Error 2

**Comment by mrallen1** [comment]
Have you tried building this before and it failed? It looks like there's some kind of old configuration laying around in the directory.

**Comment by satishkumarkt** [comment]
Yes I tried before
then I rebuild my os and tried again same error

steps I followed
1. curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
2. chmod a+x kerl
3. /home/friends/kerl build 19.2 19.2

Log
---------------------
gmake[3]: Nothing to be done for `all'.
gmake[3]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/erts/lib_src'
gmake[2]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/erts/lib_src'
(cd preloaded/src && gmake ../ebin/erts.app)
gmake[2]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/erts/preloaded/src'
gmake[2]: `../ebin/erts.app' is up to date.
gmake[2]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/erts/preloaded/src'
gmake[1]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/erts'
 MAKE   secondary_bootstrap_build
gmake[1]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib'
gmake[2]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe'
Makefile:72: warning: overriding commands for target `clean'
/home/friends/.kerl/builds/19.2/otp_src_19.2/make/otp_subdir.mk:29: warning: ignoring old commands for target `clean'
=== Entering application hipe
gmake[3]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/rtl'
gmake[4]: Entering directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/main'
 VSN    hipe.hrl
gmake[4]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/main'
 ERLC   ../ebin/hipe_rtl.beam
Failed to create aux thread

Crash dump is being written to: erl_crash.dump...done
/bin/sh: line 1: 15685 Aborted                 erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl.erl
gmake[3]: *** [../ebin/hipe_rtl.beam] Error 134
gmake[3]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe/rtl'
gmake[2]: *** [opt] Error 2
gmake[2]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib/hipe'
gmake[1]: *** [opt] Error 2
gmake[1]: Leaving directory `/home/friends/.kerl/builds/19.2/otp_src_19.2/lib'
gmake: *** [secondary_bootstrap_build] Error 2

**Comment by mrallen1** [comment]
OK, sorry it's not working.

For the purposes of your use of CouchDB, could you possibly use an Erlang that's precompiled?

https://www.erlang-solutions.com/resources/download.html

There are precompiled packages for CentOS 6 - and instructions for installing them out of an RPM repository.

**Comment by mrallen1** [comment]
I haven't heard back from you, so I'm assuming you either found a way to make this work or you're frustrated enough to try something else. :)

If I don't hear back in 7 days I'm going to close this ticket. Feel free to open a new one if you like.

**Comment by ngeraedts** [comment]
I'm running into a similar issue on our build agent. The logs are near identical, but I'm attempting to install Erlang 20.0 and 20.2. 

```
/bin/sh: line 1: 45065 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_ssapre.erl
gmake[3]: *** [../ebin/hipe_rtl_ssapre.beam] Error 134
/bin/sh: line 1: 45066 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_lcm.erl
gmake[3]: *** [../ebin/hipe_rtl_lcm.beam] Error 134
/bin/sh: line 1: 45051 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_cfg.erl
gmake[3]: *** [../ebin/hipe_rtl_cfg.beam] Error 134
/bin/sh: line 1: 45060 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_arith_32.erl
gmake[3]: *** [../ebin/hipe_rtl_arith_32.beam] Error 134
/bin/sh: line 1: 45052 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_icode2rtl.erl
/bin/sh: line 1: 45063 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_binary_construct.erl
gmake[3]: *** [../ebin/hipe_icode2rtl.beam] Error 134
gmake[3]: *** [../ebin/hipe_rtl_binary_construct.beam] Error 134
/bin/sh: line 1: 45011 Aborted                 (core dumped) erlc -W +debug_info -Werror +inline +warn_unused_import +warn_export_vars -o../ebin hipe_rtl_arch.erl
gmake[3]: *** [../ebin/hipe_rtl_arch.beam] Error 134
gmake[3]: Leaving directory `/Network/filer003/aws_homes/nicholas.geraedts/.asdf/plugins/erlang/kerl-home/builds/asdf_20.2/otp_src_20.2/lib/hipe/rtl'
gmake[2]: *** [opt] Error 2
gmake[2]: Leaving directory `/Network/filer003/aws_homes/nicholas.geraedts/.asdf/plugins/erlang/kerl-home/builds/asdf_20.2/otp_src_20.2/lib/hipe'
gmake[1]: *** [opt] Error 2
gmake[1]: Leaving directory `/Network/filer003/aws_homes/nicholas.geraedts/.asdf/plugins/erlang/kerl-home/builds/asdf_20.2/otp_src_20.2/lib'
gmake: *** [secondary_bootstrap_build] Error 2
```

I do have a development VM (also centos6 based) where asdf-elixir and kerl are able to successfully compiled. I'll see if I can find the missing dependency between the two and report back.

**Comment by fenollp** [comment]
centos6 + 20.2 should build fine: https://github.com/kerl/kerl/pull/264

**Comment by mrallen1** [comment]
I'm going to close this ticket for now. Open a new one if you're still having trouble, please.
