### ISSUE TITLE
Feature request: Clean up archives

### ISSUE THREAD

**Issue by bmaupin** [kerl/kerl#263]
I'd love it if kerl had a way to clean up the archives folder. Maybe when you delete a build, it deletes the corresponding archive? I'm not really picky on how it's done. But I could see the archives folder getting fairly large and space can be an issue on some servers:

    $ du -sh .kerl/archives/
    250M    .kerl/archives/

    $ du -sh .kerl/archives/*
    28K     .kerl/archives/MD5
    84M     .kerl/archives/otp_src_20.0.tar.gz
    84M     .kerl/archives/otp_src_20.1.tar.gz
    84M     .kerl/archives/otp_src_20.2.tar.gz

Thanks!

**Comment by bmaupin** [comment]
Works for me!

**Comment by bmaupin** [comment]
Based on [my last comment on #262](https://github.com/kerl/kerl/issues/262#issuecomment-359557146), it sounds like this is actually the intended functionality of `kerl cleanup`. Since it doesn't work like this, maybe this is just a bug and a duplicate of #262?

**Comment by mrallen1** [comment]
It's possible. I haven't really looked into it closely yet.  I hope to do some kerl triage this week.
