### ISSUE TITLE
Error: type public_key() undefined on ubuntu

### ISSUE THREAD

**Issue by Gsantomaggio** [kerl/kerl#265]
Hi,
When I try to execute my application I get this error:

```
$ make shell
23:40:15.004 [error] /home/gabriele/.kerl/builds/20.2/otp_src_20.2/lib/ssh/src/ssh_client_key.erl:26: Error: type public_key() undefined
23:40:15.083 [error] /home/gabriele/.kerl/builds/20.2/otp_src_20.2/lib/ssh/src/ssh_server_key.erl:32: Error: type public_key() undefined
```

Running on ubuntu:
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
```
openssl 
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

Crypto seems to work correctly:

```
$ erl
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.2  (abort with ^G)
1> crypto:start().
ok
2>
```

Kerl version `1.8.1`

What could be?
Thank you

**Comment by fenollp** [comment]
Sounds like a typo on your part: it's `public_key:public_key()`.
See [the docs](https://erldocs.com/current/public_key/public_key.html?i=1&search=public_key#public_key).

**Comment by Gsantomaggio** [comment]
Thanks, I will investigate.
It is strange, since on mac Sierra with the standard installation I don't have this problem.

**Comment by Gsantomaggio** [comment]
I tried to build Erlang otp 20.2 manually and I got the same error. 
I close this issue. Thanks
