### ISSUE TITLE
dirty schedulers

### ISSUE THREAD

**Issue by alexshavelev** [kerl/kerl#268]
is there possibility to build 18.x with `--enable-dirty-schedulers`

**Comment by mrallen1** [comment]
Yes, definitely. Add the flag to the environment variable [`KERL_CONFIGURE_OPTIONS`](https://github.com/kerl/kerl#kerl_configure_options).

**Comment by alexshavelev** [comment]
thanks

**Comment by mrallen1** [comment]
You're welcome. :)
