### ISSUE TITLE
"kerl cleanup" missing from shell completion scripts

### ISSUE THREAD

**Issue by nalundgaard** [kerl/kerl#273]
I recently noticed this for bash. Would be nice to have it working!

**Comment by paulo-ferraz-oliveira** [comment]
Fwiw, `bash` completion scripts don't, but `zsh` do, so we're halfway there 😄

**Comment by paulo-ferraz-oliveira** [comment]
For `bash` these are missing:

* `version`
* `deploy`
* `plt`
* `prompt`
* `emit-activate`
* `cleanup`

For `zsh` these are missing:

* `version`
* `plt`
* `emit-activate`

If/when I have time I'll get to them all at once.
