### ISSUE TITLE
kerl doesn't install Erlang crypto with openssl 1.1.0g and 1.1.0g Ubuntu 18.04

### ISSUE THREAD

**Issue by dabeat** [kerl/kerl#278]
Trying to install Erlang (17.5 and 20.3) in Ubuntu 18.04 with:

OpenSSL 1.1.0g   2 Nov 2017
libssl-dev version (1.1.0g-2ubuntu4).

When running erl for interactive console it works. When running rebar:

```
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,165}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,752}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,276}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
```

I tried also downgrading openssl to 

OpenSSL 1.0.1k 8 Jan 2015

and still the same problem.

I have installed Erlang following [this guide](https://tecadmin.net/install-erlang-on-ubuntu/) and it works.

Any clue what might be the problem when installing it with kerl?

**Comment by mrallen1** [comment]
You're going to have a tough time with openssl 1.1.x and 17.5.  If you downgraded, you'll have to completely delete the kerl build stuff and make sure that ldd and so forth point to the right place.

**Comment by dabeat** [comment]
Yes, the problem seems to be at least with Erlang 17.5. I got Erlang 20.3 successfully installed.
I'll try downgrading openssl and libssl-dev.

**Comment by mrallen1** [comment]
Yeah, sorry about that.

**Comment by cmeiklejohn** [comment]
I'm also having this same problem with trying to build any of the Erlang/OTP 19 releases as well on Ubuntu 18.04.  Is this related to the OpenSSL change as well?

```
$ KERL_BUILD_DOCS=yes kerl build 19.3 19.3                                                
Downloading otp_src_19.3.tar.gz to /home/cmeiklejohn/.kerl/archives
Getting checksum file from erlang.org...
Verifying archive checksum...
Checksum verified (a8c259ec47bf84e77510673e1b76b6db)
Extracting source code
Building Erlang/OTP 19.3 (19.3), please wait...
APPLICATIONS DISABLED (See: /home/cmeiklejohn/.kerl/builds/19.3/otp_build_19.3.log)
 * crypto         : No usable OpenSSL found
 * odbc           : ODBC library - link check failed
 * ssh            : No usable OpenSSL found
 * ssl            : No usable OpenSSL found

APPLICATIONS INFORMATION (See: /home/cmeiklejohn/.kerl/builds/19.3/otp_build_19.3.log)
 * wx             : wxWidgets not found, wx will NOT be usable
```

**Comment by paulo-ferraz-oliveira** [comment]
All the comments refer to OTP 20-. I'm not sure this issue is still relevant, since I haven't witnessed it recently (though my use case is usually limited to Ubuntu, MacOS, and CentOS).

**Comment by jadeallenx** [comment]
I'm going to close this - reopen if its still needed

**Comment by paulo-ferraz-oliveira** [comment]
Still open 😄
