### ISSUE TITLE
21.0-rc1 Not found

### ISSUE THREAD

**Issue by GeraldXv** [kerl/kerl#280]
`/usr/local/bin/kerl update releases` can not get the otp 21.

**Comment by fenollp** [comment]
It’s been mentioned on the erlang-questions ML. Looks like it is no longer on erlang.org for some reason outside of Kerl’s reach. 

As a workaround use ˋKERL_BUILD_BACKEND=git kerl update releases`

**Comment by GeraldXv** [comment]
Thanks @fenollp
