### ISSUE TITLE
Build RabbitMQ with Erlang installed by Kerl

### ISSUE THREAD

**Issue by asomov** [kerl/kerl#281]
Hi all,
I am trying to create a docker image which is suitable for RabbitMQ development.
The docker image is created with Ansible which is using Kerl to install Erlang.

The project is here: https://github.com/asomov/rabbitmq-server-dev

At the moment I follow the instructions at https://www.rabbitmq.com/build-server.html
but I get an error: https://gist.github.com/asomov/8094aa2758e5b611b88b3abfffd8d6ab

```
src/rabbit_net.erl:21: can't find include lib "ssl/src/ssl_api.hrl"
src/rabbit_net.erl:94: record sslsocket undefined
```

Feel free to check the project out and give it a try ! You do not need to install anything (except the docker itself)

Any help with the build is appreciated...

Cheers,
Andrey

**Comment by mrallen1** [comment]
Not sure what underlying Linux your Docker image is using, but we've had some reports that very recent OpenSSL (1.1.0) don't seem to work against certain versions of Erlang.

**Comment by fenollp** [comment]
Yeah `application:ensure_all_started(crypto).` would let you know if the OpenSSL package is the issue. 

Why don’t you just fork Docker’s own rabbitmq Dockerfile?

**Comment by asomov** [comment]
@fenollp : I will be happy to steal the work from somebody else and reuse existing dockerfile. But I could not find any. I found dockerfile for running rabbitmq-server but not for building it.

I try to create Ansible script which can be used either with Docker or without to install all the components to develop RabbitMQ server. (docker specific tasks are implemented in dockerfile)

@mrallen1 : what is the workaround ?
```
# openssl
OpenSSL> version
OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by fenollp** [comment]
Ok. Nice trick wrt using Ansible for both workflows though usually it’s less error prone to have just one workflow. 

Anyway the solution is to downgrade/pin your ssl package to an older version. See kerl’s CI file for versions that are known to work.

**Comment by asomov** [comment]
Thank you. It works now.

P.S. I am impressed how difficult it is to start development. The threshold to contribute anything is very high. Python or Java development is easier to start. You do not have to build Python or Java and you do not need to build the building tools taking care of all the dependencies...

**Comment by fenollp** [comment]
Patches welcomed :)

You could also just apt install erlang or use the erlang Docker image from Docker hub too.

**Comment by asomov** [comment]
@fenollp : which Docker image ?

**Comment by asomov** [comment]
Do you mean https://hub.docker.com/_/rabbitmq/ ?
This docker is only to run rabbitmq. It does not help to build and contribute to rabbitmq

**Comment by asomov** [comment]
@fenollp : thank you for your reccomendation - I have removed Ansible. 

It was a challenge to activate Erlang with Kerl in Docker, but in general Kerl works great. Good Job !

**Comment by fenollp** [comment]
@asomov Glad I could help :)

@mrallen1 Maybe a patch similar to https://github.com/alpinelinux/aports/commit/e7e1a45bc6748a6e1c493792e81ae854f6c2a685 could help?

**Comment by mrallen1** [comment]
Yeah that would be super cool, I think.
