### ISSUE TITLE
Kerl Fails To Build "No 32-bit type found"

### ISSUE THREAD

**Issue by HangingClowns** [kerl/kerl#283]
iMac Pro 10.13.5

I'm running kerl through asdf and I keep getting this strange error:
```
Downloading OTP-20.3.7.tar.gz to /Users/allen/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    131      0 --:--:-- --:--:-- --:--:--   131
100 51.0M    0 51.0M    0     0  1004k      0 --:--:--  0:00:52 --:--:-- 1462k
Extracting source code
Building Erlang/OTP 20.3.7 (asdf_20.3.7), please wait...
Configure failed.
checking for Linux futexes... no
checking for pthread_setname_np... no
checking for pthread_getname_np... no
checking size of short... 0
checking size of int... 0
checking size of long... 0
checking size of long long... 0
checking size of __int128_t... 0
configure: error: No 32-bit type found
```

It's important to note that I did migrate to this computer, just today. So I'm wondering if maybe I need to rebuild some packages or something in my homebrew to make this work?

I was previously having no issue to compile on my old machine, but I haven't been able to do it on my new computer.

**Comment by mrallen1** [comment]
My experience with using Erlangs build with previous kernels has always been very dicey. Generally you will need to refresh your whole build chain including the dependencies that weren't part of Apple's upgrade stuff or Xcode including whatever you pulled down from homebrew.

**Comment by HangingClowns** [comment]
thats' what i was thinking, do you happen to know what i would need to refresh within homebrew?

**Comment by mrallen1** [comment]
I know for certain than any 32 bit library will not work on High Sierra. That's one of things Apple explicitly changed in the OS for that release. Above and beyond that, no, sorry. I thought there was some kind of homebrew command which would automatically fetch new versions of stuff when you upgrade your OS, but I don't know what it is. Sorry.

**Comment by HangingClowns** [comment]
Yeah, sadly it seems I can't use my old installation. So I just wiped it, manually moved over my files and it worked immediately. Thanks for the input!

**Comment by mrallen1** [comment]
Cool, I'm glad it all worked out for you but sorry for the inconvenience.

**Comment by kyleaa** [comment]
Just posting for future travelers (since this comes up as the top google search) - I had this same issue after using Migration Assistant and struggled with it for a bit. I had given up on asdf and switched to using the brew erlang, but I had issued compiling with rebar as well and in researching that I found the cure which resolves this as well - removing `/usr/local/include`.

**Comment by mrallen1** [comment]
Thanks for the note @kyleaa

**Comment by Hugainz** [comment]
Thank you so much @kyleaa ! Was struggling with the exact same problems after using the migration assistant.
