### ISSUE TITLE
21.0 and Corba

### ISSUE THREAD

**Issue by crownedgrouse** [kerl/kerl#285]
Hi,

Since 21.0, CORBA is not anymore coming in OTP, but is moved in another git repo.
Can kerl be able to install corba at same time ? Could this be an environment variable  or a question at build time ?

thanks

**Comment by crownedgrouse** [comment]
note that OTP will probably move other applications in futur . this question is not limited to Corba...

**Comment by fenollp** [comment]
Can't CORBA be an explicit dependency of your application?

I'm thinking either `{deps, [corba]}` or some rebar.config.script / rebar3 trickery that depends on the OTP version installed.

I am not sure that kerl should be providing a way to install CORBA alongside OTP. To me that is a problem with a rebar3 solution. What do you think?

**Comment by crownedgrouse** [comment]
my concern is for geas.  I wonder if I should keep CORBA in geas database or not. I would prefere that CORBA comes in OTP as a configure option, like ODBC or Java. Currently compiling Corba need both a build OTP and source, and giving ERL_TOP path. Telling configure that I want Corba would be simpler MHO. But this imply a git clone of repo before compiling. And OTP is not currently handled by rebar3, but by Makefiles, and not erlang;mk...

**Comment by mrallen1** [comment]
Sorry to be blunt about it but, I really have no interest in extending kerl to support CORBA builds outside of OTP.

**Comment by crownedgrouse** [comment]
Looks like lot of people do not really care of corba indeed.  :). But some recent PR let it easier to install with Otp. Closing thanks

**Comment by fenollp** [comment]
I mean geas really cares about OTP releases. To me if a module is no longer in an OTP release then that's somthing geas finds, corba is no exception.
I have no interest in implementing that kind of exception in kerl either.

**Comment by crownedgrouse** [comment]
True, but currently this is not easy as adding   a deps to rebar.still need an otp configured source tree. My concern is that maybe other applications may move outside otp in future. They should be more independent to Otp to achieve this. Corba wasn't the best candidate from this POV. Even if I understand the choice, due to few usage probably outside Ericsson?
