### ISSUE TITLE
`kerl build` still checks apps excluded in $KERL_CONFIGURE_DISABLE_APPLICATIONS

### ISSUE THREAD

**Issue by aquarhead** [kerl/kerl#287]
```
APPLICATIONS DISABLED (See: /Users/aquarhead/.kerl/builds/20.3/otp_build_20.3.log)
 * jinterface     : No Java compiler found
 * odbc           : odbc disabled by user.
 * jinterface     : User gave --without-jinterface option
 * odbc           : User gave --without-odbc option
```

Even though I defined `export KERL_CONFIGURE_DISABLE_APPLICATIONS="jinterface odbc"` when running `kerl build` it still prompts about java, shouldn't it skip java checks if I don't need Java interop?

**Comment by fenollp** [comment]
Which commit of kerl are you using?

**Comment by aquarhead** [comment]
I did reinstalled with `brew install --HEAD kerl` before running `kerl build 20.3 20.3`

**Comment by mrallen1** [comment]
It's part of the base build (via autotools) to probe for Java. I've looked at what it would take to disable it completely and it's pretty complicated.

**Comment by fenollp** [comment]
If you can't load any of jinterface nor odbc apps then it's really just about the prompt and that's been answered. I'm closing this.
If you are unhappy with this (except the java line) feel free to (re-)open an issue.
