### ISSUE TITLE
kerl build hangs if no wx or fop

### ISSUE THREAD

**Issue by llaisdy** [kerl/kerl#288]
Dear All

Kerl build hangs if wx is not available or if documentation cannot be built - i.e. after printing this line ...

    *                  The documentation can not be built.

... kerl does not return to the shell prompt.  Is this expected behaviour?

Is there a way of telling kerl, either of:

- Don't build the documentation
- Tell me if I'm missing any requirements

Thanks

Ivan

**Comment by fenollp** [comment]
`KERL_BUILD_DOCS` defaults to not being set to `yes` so should not be building docs.
Kerl not returning to the shell prompt sounds like an error.

Could you provide information?
* kerl commit
* OS / distribution name/version
* actual logs

>Tell me if I'm missing any requirements

This should have happened & be displayed above the line you're quoting :/

**Comment by llaisdy** [comment]
Thanks for your help.  I'll have another go this evening and send logs.  The kerl version is 1.8.3 . The OS is Ubuntu (I forget version but recently updated).

**Comment by mrallen1** [comment]
More context would be helpful. 

For clarity, kerl doesn't necessarily stop working because it can't find wx or documentation can't be built, so hearing that it doesn't drop back to the command line doesn't necessarily indicate an error.

How long did you wait before deciding kerl was hung?

**Comment by llaisdy** [comment]
You were right, I wasn't waiting long enough.  It took 12 minutes (on an oldish Thinkpad W530).
