### ISSUE TITLE
"Couldn't install" error because kerl uses random install script

### ISSUE THREAD

**Issue by llaisdy** [kerl/kerl#289]
Dear All

I am running kerl 1.8.3 on MacOS 10.13.4.  I have successfully built and installed erlang releases using kerl on this machine in the recent past (but n.b. with kerl 1.5.1).

My latest attempt got the "Couldn't install" error message:

    $  kerl install r203 ~/bin/erl_kerl_builds/r203
    Installing Erlang/OTP 20.3 (r203) in /Users/ivan/bin/erl_kerl_builds/r203...
    Couldn't install Erlang/OTP 20.3 (r203) in /Users/ivan/bin/erl_kerl_builds/r203

Digging into the kerl shell script I ran the relevant shell function (from do_install line 816) with out the ">/dev/null 2>&1" to see a more informative error message ...

    $ cd .kerl/builds/r203/otp_src_20.3/
    
    $ ERL_TOP=/Users/ivan/.kerl/builds/r203/otp_src_20.3 ./otp_build release -a /Users/ivan/bin/erl_kerl_builds/r203
    
    === Entering application stdlib
    make  RELEASE_PATH="/Users/ivan/bin/erl_kerl_builds/r203"   release_spec
    mkdir -p "/Users/ivan/bin/erl_kerl_builds/r203/lib/stdlib-3.4.4/src"
    /Library/Frameworks/R.framework/Resources/bin/install -c -m 644 -p array.erl base64.erl
      beam_lib.erl ... win32reg.erl zip.erl erl_parse.yrl
      "/Users/ivan/bin/erl_kerl_builds/r203/lib/stdlib-3.4.4/src"
    /Library/Frameworks/R.framework/Resources/bin/install: line 34: /bin/R: No such file or directory

The kerl script is using the install script from my R installation, or rather, what seems to be my default install script:

    $ which install
    /Library/Frameworks/R.framework/Resources/bin/install

My questions are:

- does the kerl set up not have an `install` of its own?

- is there a standard install which my R installation might be masking?

Thanks

Ivan

**Comment by fenollp** [comment]
Looks like R is too high in your $PATH. Try putting it at the tail.

On osx I have: (consider that I did `brew install coreutils`)
```shell
0 ~  (21.0) λ which install
/usr/local/opt/coreutils/libexec/gnubin/install
0 ~  (21.0) λ whereis install
/usr/bin/install
```

**Comment by llaisdy** [comment]
Good point.  I add things to the front, which is probably a bad idea.

**Comment by llaisdy** [comment]
That fixed it, thanks.  Had to rebuild

**Comment by thoughtarray** [comment]
Hi all. I was debating on whether to open a new ticket or reopen this one—it seems very closely related.

I'm on MacOS 10.15.3 & `kerl` 1.8.7, but I believe this issue affects many versions of MacOS.

I was receiving an unhelpful `Installing Erlang/OTP [blah] in [blah]` message. I was about to `brew install coreutils` like fenollp, but I got to doing something else and discovered that (after having updated XCode) I needed to accept the CLI terms & conditions (`sudo xcodebuild -license accept`).

I believe it'd be MacOS user-friendly to add a check for this. Or at lease output the error messages by default.

**Comment by mrallen1** [comment]
Hi, thanks for the report. Can you please help me understand what you're asking kerl should check? 

That your install script is what you expect? Or that xcode doesn't complain? Or both? I'm looking for the desired behavior as you see it. Thanks!

**Comment by thoughtarray** [comment]
Hi @mrallen1, thanks for responding.

The desired result is to know why `kerl install` is failing. In this case, it was because of XCode licensing. The lowest impact change would just be outputting errors to STDERR. The next level would be including some kind of check to see if the installation failure is because of an XCode license acceptance issue. This check is pretty common and is included in tools like `brew` (which is how I installed `kerl`).

**Comment by mrallen1** [comment]
Ah, I see. Instead of eating the errors in /dev/null, we should capture them and emit them if the command fails. That's good feedback. I will open a new ticket on your behalf :)
