### ISSUE TITLE
Unable to compile 21.1 with wx on Debian stretch

### ISSUE THREAD

**Issue by lpil** [kerl/kerl#305]
I've installed all the packages required as directed by the [asdf Erlang README](https://github.com/asdf-vm/asdf-erlang#ubuntu-and-debian) (and all wx packages available) yet I am still unable to compile with wx support.

> For building with wxWidgets (start observer or debugger!) apt-get -y install libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev libpng3

```
APPLICATIONS INFORMATION (See: /home/louispilfold/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_build_21.1.log)
 * wx             : wxWidgets not found, wx will NOT be usable
```

The rest of the compilation appears to work OK.

Related issue: https://github.com/asdf-vm/asdf-erlang/issues/91

Possibly related issue on Fedora 28 with Erlang 21.1: https://github.com/asdf-vm/asdf-erlang/issues/90

This issue also features output in which wxWidgets isn't available, though it's unclear if that is intentional: https://github.com/kerl/kerl/issues/279

**Comment by paulo-ferraz-oliveira** [comment]
Can't reproduce this with the following setup:

- Debian: https://hub.docker.com/_/debian latest
- Tools: apt-get install -y curl git gcc libssl-dev make automake autoconf libncurses5-dev g++ libwxgtk3.0-gtk3-dev
- CLI: KERL_CONFIGURE_OPTIONS=--with-wx ./kerl build 23.

Not sure about kerl's support for the different operating systems, though.

---

Result:
```
KERL_CONFIGURE_OPTIONS=--with-wx ./kerl build 23.0
Extracting source code
Building Erlang/OTP 23.0 (23.0), please wait...
APPLICATIONS DISABLED (See: /root/.kerl/builds/23.0/otp_build_23.0.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

DOCUMENTATION INFORMATION (See: /root/.kerl/builds/23.0/otp_build_23.0.log)
 * documentation  :
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  xmllint is missing.
 *                  The documentation cannot be built.

Erlang/OTP 23.0 (23.0) has been successfully built
```

**Comment by jadeallenx** [comment]
please reopen if still needed
