### ISSUE TITLE
Error creating the instance 21.1 

### ISSUE THREAD

**Issue by VladimirTambovtsev** [kerl/kerl#306]
Mac OS High Sierra: 10.13.6

After installing by brew, I try to build instance
<pre>
>>kerl build 21.1 21.1
Verifying archive checksum...
Checksum verified (482f91cf34c2ffb1dff6e716a15afefa)
Building Erlang/OTP 21.1 (21.1), please wait...
APPLICATIONS DISABLED (See: /Users/vladimir/.kerl/builds/21.1/otp_build_21.1.log)
 * odbc           : ODBC library - header check failed

DOCUMENTATION INFORMATION (See: /Users/vladimir/.kerl/builds/21.1/otp_build_21.1.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.
</pre>

Any ideas? Other versions failed creating as well

**Comment by fenollp** [comment]
Looks like you're not waiting long enough. This is what a build looks like: https://travis-ci.org/kerl/kerl/jobs/436555468#L284

**Comment by VladimirTambovtsev** [comment]
Wow. That was unexpected. I'll give it another shot. Thanks for your reply
