### ISSUE TITLE
kerl silently produces a build without crypto if libssl headers are missing

### ISSUE THREAD

**Issue by kgadek** [kerl/kerl#31]
Porting issue from https://github.com/evax/kerl/issues/13

If libssl headers are missing in the system, the resulting Erlang build will not include crypto module. Such Erlang build is pretty much useless. For instance, rebar won't be working without crypto.

It would be great if kerl were asking a user whether he wants to continue a build without crypto. A simpler but a still better way of handling this situation would be exiting with an error.

-- originally reported by @alavrik

**Comment by ludwikbukowski** [comment]
still

**Comment by jacktang** [comment]
+1 for crypto application should be included, otherwise exception should be thrown

**Comment by StoneCypher** [comment]
At least a highly visible end-warning?

**Comment by mrallen1** [comment]
Agreed.

**Comment by mrallen1** [comment]
Looking at #53 for this issue.

**Comment by mrallen1** [comment]
We've just merged #148 which should warn about this problem. Please reopen if needed.
