### ISSUE TITLE
Unable to build erlang 21.3.2 on Ubuntu 18

### ISSUE THREAD

**Issue by SheriefAlaa** [kerl/kerl#312]
Hi everyone,

I was able to build erland 21.3.2 or the last two weeks up until I installed open jdk and the other deps for running the erlang debugger. However, when I did so, I could never build.

EDIT:

Java's version:
> javac --version
> javac 10.0.2

Log:
> CXX	x86_64-unknown-linux-gnu/egl_impl.o
>  CC	../priv/x86_64-unknown-linux-gnu/erl_gl.so
> /usr/bin/ld: cannot find -lGL
> collect2: error: ld returned 1 exit status
> Makefile:172: recipe for target '../priv/x86_64-unknown-linux-gnu/erl_gl.so' failed
> make[3]: *** [../priv/x86_64-unknown-linux-gnu/erl_gl.so] Error 1
> make[3]: *** Waiting for unfinished jobs....
> make[3]: Leaving directory '/home/sherief/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.2/otp_src_21.3.2/lib/wx/c_src'
> /home/sherief/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.2/otp_src_21.3.2/make/otp_subdir.mk:29: recipe for target 'opt' failed
> make[2]: *** [opt] Error 2
> make[2]: Leaving directory '/home/sherief/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.2/otp_src_21.3.2/lib/wx'
> /home/sherief/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.2/otp_src_21.3.2/make/otp_subdir.mk:29: recipe for target 'opt' failed
> make[1]: *** [opt] Error 2
> make[1]: Leaving directory '/home/sherief/.asdf/plugins/erlang/kerl-home/builds/asdf_21.3.2/otp_src_21.3.2/lib'
> Makefile:490: recipe for target 'libs' failed
> make: *** [libs] Error 2
> 

EDIT:

I am using asdf-vm.

Any help would be much appreciated.

Thanks!

**Comment by SheriefAlaa** [comment]
It seems I have solved it.

The problem was that the installer was looking for

> /usr/lib/libGL.so

but it was linked as
> lrwxrwxrwx 1 root root 36 Apr  5 11:44 /usr/lib/libGL.so.1 -> /usr/lib/x86_64-linux-gnu/libGL.so.1

so by renaming the symlink to
> sudo ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/libGL.so

I got it to build.

**Comment by mrallen1** [comment]
I'm glad you figured out the problem and were able to build Erlang.
