### ISSUE TITLE
Warning on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Eiji7** [kerl/kerl#323]
Hey, I'm using `asdf` for managing multiple versions of development software. It uses this project and on `openSUSE` distribution there is one small problem. Luckily it does not stops building process, but still shows a warning which is really confusing:

> WARNING: It appears a required development package 'openssl-devel' is not installed.

I have found that this message comes from:
https://github.com/kerl/kerl/blob/a0f478901d228f1ef773e74bfed1c97c624dcab0/kerl#L371-L389

To understand what is going wrong on `openSUSE` simply let me show you my output:
```
$ rpm -q openssl-devel
pakiet openssl-devel nie jest zainstalowany
# message in Polish that such package is not installed
$ rpm -q libopenssl-devel
libopenssl-devel-1.1.1c-1.1.noarch
```

Finally to confirm that such package just does not exists here is a search result:
```bash
$ zypper search openssl-devel
Wczytywanie danych repozytorium...
# Loading repository data ...
Odczytywanie zainstalowanych pakietów...
# Reading installed packages ...

S  | Nazwa                 | Podsumowanie                                          | Typ   
---+-----------------------+-------------------------------------------------------+-------
i+ | libopenssl-devel      | Include Files and Libraries mandatory for Development | pakiet
   | xmlsec1-openssl-devel | OpenSSL crypto plugin for XML Security Library        | pakiet

# Nazwa -> Name
# Podsumowanie -> Summary
# Typ -> Type
# pakiet -> package
```

Do you think that you can add a special check for this case? Please look that it's not a distribution which nobody knows about. Following [Distrowatch](https://distrowatch.com) `openSUSE` is 10th of most popular distributions and also 4 of 62 `Independent` distributions.

**Comment by k-cross** [comment]
I just ran into this myself updating from `asdf` to `22.3.3` from `22.3`. It's possible I upgraded something that caused a conflict but I certainly have the `libopenssl-devel` installed. Wondering what a workaround might be.

**Comment by oshanz** [comment]
https://github.com/kerl/kerl/blob/3a3f96f7a3067ec4bbf0f3937604750a311b74e3/kerl#L472

suse doesn't have a `openssl-devel` package. it is named as `libopenssl-devel`

![image](https://user-images.githubusercontent.com/5364479/125797621-3cd43c4a-eec9-4935-a1f4-30a1c26508ce.png)

**Comment by crownedgrouse** [comment]
Can you please provide what `uname -s` provide on opensuse ?
So a workaround can be done on requirement ?

**Comment by crownedgrouse** [comment]
Can you please provide what `uname -s` provide on opensuse ?
So a workaround can be done on requirement ?

**Comment by oshanz** [comment]
```bash
$ uname -a
Linux localhost.localdomain 5.17.4-1-default #1 SMP PREEMPT Wed Apr 20 07:43:03 UTC 2022 (75e9961) x86_64 x86_64 x86_64 GNU/Linux


$ lsb_release -ir
Distributor ID: openSUSE
Release:        20220428
```

**Comment by crownedgrouse** [comment]
can you test this dev branch : https://github.com/crownedgrouse/kerl/tree/feature/opensuse_workaround  ?
before I propose a PR, as I do not have an opensuse machine right now.

**Comment by oshanz** [comment]
I've tested using a suse container image and warning are working correctly. thanks for the fix @crownedgrouse :rocket: 

```bash
The asdf_26.2.1 build has been deleted
Extracting source code
Building Erlang/OTP 26.2.1 (asdf_26.2.1), please wait...
WARNING: It appears a required development package 'libopenssl-devel' is not installed.
WARNING: It appears a required development package 'make' is not installed.
WARNING: It appears a required development package 'automake' is not installed.
WARNING: It appears a required development package 'autoconf' is not installed.
WARNING: It appears a required development package 'ncurses-devel' is not installed.
WARNING: It appears a required development package 'gcc' is not installed.
Build failed.
checking for cc... no
checking for cl.exe... no
checking for clang... no

```

**Comment by crownedgrouse** [comment]
Huhh. I admit I totally forgot this two years old subject . I will propose a PR then...

**Comment by paulo-ferraz-oliveira** [comment]
Closing as stale. The linked pull request was also stale. Feel free to re-open if the issue persists.
