### ISSUE TITLE
unable to build otp 17.5 on Mac OS catalina.

### ISSUE THREAD

**Issue by kstanyu** [kerl/kerl#328]
APPLICATIONS DISABLED (See: /Users/sly/.kerl/builds/17.5/otp_build_17.5.log)
 * odbc           : ODBC library - link check failed

DOCUMENTATION INFORMATION (See: /Users/sly/.kerl/builds/17.5/otp_build_17.5.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

**Comment by robsonperassoli** [comment]
@kstanyu i was able to build using this configuration on `~/.kerlrc`:
```
export CFLAGS="-g -O3 -fno-stack-check"
KERL_CONFIGURE_OPTIONS="--without-javac --with-ssl=/usr/local/Cellar/openssl@1.1/1.1.1d"
```

Used kerl@1.8.6 and erlang@22.1

**Comment by Lucas3oo** [comment]
At least Erlang 18 needs OpenSSL 1.0.2. I can't get it to work with OpenSSL 1.1. The config step says that no suitable OpenSSL is found.
