### ISSUE TITLE
erl_call not exposed when installing erlang via kerl

### ISSUE THREAD

**Issue by onno-vos-dev** [kerl/kerl#329]
### Description
`erl_call` is not exposed when I install Erlang via kerl. This is problematic when one wants to execute rpc calls from the command line without having to start a erlang shell and using `rpc:call/x`. 

### Expected behavior
`erl_call` is added to $PATH so that it can be used from the command line

I'm suprised there's no issue opened here and I cannot find any reference to this being a problem to anyone? If this feature is something you'd like to support, I'm happy to implement the support for this :) Briefly looking through `kerl` it should be fairly trivial to add support for this. 

Would love to hear your view on this :)

**Comment by mrallen1** [comment]
I've been using Erlang since 2012 and I've never used this utility; that being said, I support a PR to implement the functionality you'd like to see.

**Comment by onno-vos-dev** [comment]
I understand that many are likely to not use this functionality but I encountered this issue when trying to execute some bash scripts that use erl_call :)

I'll work on the PR over the next few days 👍

Thank you the quick response!
