### ISSUE TITLE
dependencies for kerl 

### ISSUE THREAD

**Issue by fogfish** [kerl/kerl#331]
`kerl` do not work out of the box on clean linux machine. It requires some tools to compile Erlang. It would be good if README lists these packages.

**Comment by fogfish** [comment]
Just a suggestions to improve usability but does not seems any one cares about it.

**Comment by mrallen1** [comment]
Hi, sorry I didn't respond to your ticket quickly enough - I am not opposed to adding some information about it but I am concerned that we're going to have to start listing RPMs and DEBs and emerge instructions for every flavor of Linux out there and I kind of don't want to do that.

I would be open to a PR to add the information along the lines you suggest.

**Comment by crownedgrouse** [comment]
Maybe simply give this URL https://www.erlang.org/doc/installation_guide/install  on Erlang compilation failure as user help ?

**Comment by paulo-ferraz-oliveira** [comment]
These days, the README specifies tool like `curl` and `git`, but that's probably not what OP is looking for. At the same time we've implemented a mechanism to make adding new Linux flavours, for dependencies, easier. I'm not opposed to @crownedgrouse's suggestion, and if I reach this issue in the future and it's still open that's the one I'll implement to close it.

**Comment by jadeallenx** [comment]
I think this issue can be closed. The new system is in place and I'm comfortable with it. The prereqs for kerl itself remain git and curl and so forth.
