### ISSUE TITLE
Shell script error (_KERL_SAVED_ERL_AFLAGS: unbound variable)

### ISSUE THREAD

**Issue by rjcoelho** [kerl/kerl#332]
For some reason I now get
`/.kerl/installs/21.3/activate:4: _KERL_SAVED_ERL_AFLAGS: unbound variable`
Adding `set +o nounset` or `set +u` solves the issue.

I'm using `zsh 5.7.1 (x86_64-apple-darwin18.2.0)` and activating inside direnv's enrc. 

Its probably related to https://github.com/direnv/direnv/commit/c70f7cddca922e830c6225833e4d736327d8bf7e
Since this usage (calling kerl activate inside direnv is probably very common) I vote to include `set +u` when generating the kerl's activate script.

**Comment by fenollp** [comment]
This seems to be due to https://github.com/kerl/kerl/blob/a2acb6bb6bf598edef93d9481ec2fac950318988/kerl#L898-L901
Do you mind creating a PR that silences this warning?
I'm thinking something along the lines of using
```shell
    aflags="${_KERL_SAVED_ERL_AFLAGS:-}"
    if [ -n "\$aflags" ]; then
        ...
```

**Comment by rjcoelho** [comment]
Well direnv has since reverted the changes. So i'm going to close this. It would be nice to make kerl script work without +u
