### ISSUE TITLE
Releases list only includes minor versions (not patch)

### ISSUE THREAD

**Issue by jwheare** [kerl/kerl#333]
Since the `kerl list releases` command only shows releases with a tarball on http://erlang.org/download/ it skips out patch releases. e.g. 22.2 is listed, but not 22.2.6

If someone wants to install the latest release they need to specify it as a git tag.

It might be worth using the github releases page to populate this list instead:
https://github.com/erlang/otp/releases

**Comment by jwheare** [comment]
See https://bugs.erlang.org/browse/ERL-1126 for some background on why erlang.org/download only shows minor releases.

**Comment by fenollp** [comment]
You can circumvent this by using the git backend: https://github.com/kerl/kerl#kerl_build_backend

Note: https://github.com/kerl/kerl/pull/277

**Comment by jwheare** [comment]
Yup, just noting that the default case could be improved.

**Comment by mrallen1** [comment]
I agree. For a while we've had a PR teed up to switch the default from an erlang.org download to a git build but I thought we ought to make a big announcement first - I think perhaps the upcoming CodeBEAM conference at the beginning of March might be suitable.
