### ISSUE TITLE
KERL_BUILD_DOCS=yes and doc chunks

### ISSUE THREAD

**Issue by wojtekmach** [kerl/kerl#334]
OTP 23.0-rc1 introduces EEP-48 style doc chunks and new functions for accessing documentation in the shell. See https://github.com/erlang/otp/pull/2545 for more information.

I tried building OTP 23.0-rc1 with kerl (via asdf-erlang) but noticed the chunks are not generated, e.g. `lib/stdlib-3.12/doc/chunks/array.chunk` is not there. Should `KERL_BUILD_DOCS=yes` build them or there should be another option?

`cd /path/to/otp && make release_docs` does build the doc chunks so I assume kerl uses something else to build docs.

**Comment by mrallen1** [comment]
https://github.com/kerl/kerl/blob/master/kerl#L858 calls `make docs` - i think we just need to adjust the make target here.

**Comment by wojtekmach** [comment]
I tried replacing `make docs` with `make release_docs` but no luck, I still see:

```
$ ./kerl install 23.0-rc1 23
$ ls 23/lib/stdlib-3.12/
ebin     examples include  src
```

so no `doc/chunks`. I did observe something curious though:

```
$ ls 23/lib/lib/stdlib-3.12/doc
chunks html   pdf
```

not sure where `lib/lib` comes from  but this seems to be the culprit. Any ideas?

**Comment by erszcz** [comment]
I confirm what @wojtekmach says. There's an issue with the `$LIB/doc/chunks` being placed one level deeper than expected, therefore `code:get_doc/1` can't find them.

**Comment by garazdawi** [comment]
If you only want to build the chunks (and not pdf, html, man) you can call `make docs DOC_TARGETS=chunks`. This will considerably speed up the doc build. Maybe it would even be a good idea to do this by default so that doc chunks always are available?

**Comment by erszcz** [comment]
> Maybe it would even be a good idea to do this by default so that doc chunks always are available?

:+1: for making it the default!

**Comment by mrallen1** [comment]
This is all great stuff thanks. I'll work on getting it fixed up this week.

**Comment by mrallen1** [comment]
OK, spending an evening tracing through everything with `bash -x` led me to [here][1]. I believe the path is getting munged by that `cp` command on line 1176. I'll try to patch tomorrow and retest.

[1]: https://github.com/kerl/kerl/blob/master/kerl#L1172-L1184

**Comment by mrallen1** [comment]
Also it looks like that make target config is only available in >= 23 (I haven't done a bunch of research on that, but grepping through 22.3 didn't yield anything like 23)

**Comment by garazdawi** [comment]
> Also it looks like that make target config is only available in >= 23 (I haven't done a bunch of research on that, but grepping through 22.3 didn't yield anything like 23)

yes. I just added it when working on the `chunks` support.

**Comment by mrallen1** [comment]
@garazdawi Can you help me debug the chunks getting put into the proper place?

**Comment by mrallen1** [comment]
i think this is resolved now - open a new issue if it is still broken

**Comment by wojtekmach** [comment]
Thank you!
