### ISSUE TITLE
Unable to build 22.3 on macOS 10.15.4

### ISSUE THREAD

**Issue by eproxus** [kerl/kerl#335]
On a clean install of macOS 10.15.4 with Homebrew `openssl@1.1` (1.1.1d) and `wxmac` 3.1.3 the following error is generated when building Erlang/OTP 22.3:

```
» kerl build 22.3 22.3                                                       1s
Downloading OTP-22.3.tar.gz to /Users/user/.kerl/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120  100   120    0     0    336      0 --:--:-- --:--:-- --:--:--   335
100 53.2M    0 53.2M    0     0  6954k      0 --:--:--  0:00:07 --:--:-- 9950k
Extracting source code
Building Erlang/OTP 22.3 (22.3), please wait...
APPLICATIONS DISABLED (See: /Users/user/.kerl/builds/22.3/otp_build_22.3.log)
 * jinterface     : Java compiler disabled by user
 * odbc           : ODBC library - header check failed

DOCUMENTATION INFORMATION (See: /Users/user/.kerl/builds/22.3/otp_build_22.3.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.
 RANLIB ../lib/internal/x86_64-apple-darwin19.4.0/liberts_internal_r.a
 GEN    obj/x86_64-apple-darwin19.4.0/opt/MADE
 LD     /Users/user/.kerl/builds/22.3/otp_src_22.3/bin/x86_64-apple-darwin19.4.0/beam.smp
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Users/user/.kerl/builds/22.3/otp_src_22.3/bin/x86_64-apple-darwin19.4.0/beam.smp] Error 1
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Please see /Users/user/.kerl/builds/22.3/otp_build_22.3.log for full details.
```

Full log: [otp_build_22.3.log](https://github.com/kerl/kerl/files/4387399/otp_build_22.3.log)

<details>
    <summary>Brew Packages</summary>

    ```
    antibody
    autoconf
    bat
    broot
    exa
    freetype
    gdbm
    gettext
    git
    glib
    ilmbase
    imagemagick
    jpeg
    libde265
    libevent
    libffi
    libheif
    libomp
    libpng
    libtermkey
    libtiff
    libtool
    libuv
    libvterm
    little-cms2
    luajit
    msgpack
    ncurses
    neovim
    openexr
    openjpeg
    openssl@1.1
    pcre
    pcre2
    python
    readline
    shared-mime-info
    sqlite
    tmux
    unibilium
    utf8proc
    webp
    wxmac
    x265
    xz
    ```
</details>

The build also fails for Erlang/OTP 21.3.8.14 with the same error.

This is being discussed on the Erlang Questions mailing list regarding 23.0-rc2 as well: http://erlang.org/pipermail/erlang-questions/2020-March/099339.html

**Comment by eproxus** [comment]
Tracking it here in the Erlang bug tracker: https://bugs.erlang.org/browse/ERL-1205

**Comment by ncraver** [comment]
I can confirm that 
```
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
``` 
is also causing me issues after upgrading from 10.15.3 (worked fine in 10.15.3).

**Comment by ncraver** [comment]
This appears to be a workaround
https://github.com/erlang/otp/blob/master/erts/configure.in#L943-L957

**Comment by keown** [comment]
same error with OTP 21

**Comment by behe** [comment]
erlang/otp#2577

**Comment by eproxus** [comment]
It’ll be officially fixed in 22.3.1 and 23.

21 and below was never was and will not be supported on Catalina 10.15.4, unfortunately.

@mrallen1 Perhaps there could be an error message printed when building unsupported versions?

**Comment by kpanic** [comment]
This should help before they release the fix:
`kerl build git https://github.com/erlang/otp.git maint maint`

I commented a similar approach for `asdf` here https://github.com/asdf-vm/asdf-erlang/issues/129#issuecomment-608337042

**Comment by mrcdll** [comment]
We merge a fix yesterday and it will be available with the next release. https://github.com/kerl/kerl/pull/337

**Comment by devansjo** [comment]
Cheap workaround for those on 21 and below is to downgrade xcode. Delete the app and then reinstall a previous version from Apple's [developer portal](https://developer.apple.com/download/more/?name=Xcode)

**Comment by eproxus** [comment]
Can confirm the workaround from @devansjo works. You need to downgrade the Command Line Tools for Xcode as well. Tested with Xcode 11.3 and Command Line Tools for Xcode 11.3.1 on macOS Catalina 10.15.4.

**Comment by mrallen1** [comment]
OK. So maybe the solution here is to detect the situation when someone has a newer Xcode installed on Catalina _and_ they're trying to build an older Erlang release, then emit this suggestion and stop building.

**Comment by eproxus** [comment]
Downgrading all of Xcode and dependent tools will create other problems in the long run, such as mess up with Homebrew etc. If the problem can be patched away on older Erlang releases by Kerl, I would suggest keep doing that instead. If some versions can't be patch, perhaps list them as incompatible with the macOS version in question.

**Comment by aYukiSekiguchi** [comment]
My coworker faced the same problem during building Erlang 20.3.8.26 with kerl 2.1.0 on macOS Catalina.

These are his clang version:
```
% clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_11.6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

and command line tools version:
```
% xcode-select -v
xcode-select version 2373.
```

I guess that the following commit breaks this build. The version of Xcode is different from the version of clang. You can see their list in [here](https://gist.github.com/yamaya/2924292#file-xcode-clang-vers-L340)
https://github.com/kerl/kerl/commit/918aeb54b94ac2a2a5b2853025b70f16bd1ebbc2#diff-2df8b125dc6a121ab2da71f2e0fe968fd2d8d710fbecfcb53e93fc2c6c05850bL665

I think you should change `compare_sem_version $clang_version ">" "11.4"` from `11.4` to `11.0.3`

**Comment by jadeallenx** [comment]
closing this now; reopen if its still valid
