### ISSUE TITLE
kerl 2.0.0 seems to ignore --without-wx with OTP 23.0

### ISSUE THREAD

**Issue by vinoski** [kerl/kerl#340]
With the setting below in `~/.kerlrc`, `kerl` 1.8.7 builds Erlang/OTP 23.0 correctly and honors the provided options:

    KERL_CONFIGURE_OPTIONS="--without-odbc --without-wx"

But with `kerl` 2.0.0, the build fails, despite apparently recognizing the options as the output below shows:

    Building Erlang/OTP 23.0 (r23), please wait...
    APPLICATIONS DISABLED (See: /my/homedir/.kerl/builds/r23/otp_build_23.0.log)
     * odbc           : odbc disabled by user.
     * odbc           : User gave --without-odbc option
     * wx             : User gave --without-wx option

    APPLICATIONS INFORMATION (See: /my/homedir/.kerl/builds/r23/otp_build_23.0.log)
     * wx             : wxWidgets was not compiled with --enable-compat28, wx will NOT be useable
     * wxWidgets don't have gl support, wx will NOT be useable
     * wxWidgets don't have wxStyledTextControl (stc.h), wx will NOT be useable
     * Can not link the wx driver, wx will NOT be useable

    DOCUMENTATION INFORMATION (See: /my/homedir/.kerl/builds/r23/otp_build_23.0.log)
     * documentation  :
     *                  fop is missing.
     *                  Using fakefop to generate placeholder PDF files.

    Build failed.
     ERLC	../ebin/dbg_wx_break.beam
     ERLC	../ebin/dbg_wx_break_win.beam
     ERLC	../ebin/dbg_wx_code.beam
     ERLC	../ebin/dbg_wx_filedialog_win.beam
    compile: warnings being treated as errors
    dbg_wx_filedialog_win.erl:22: behaviour wx_object undefined
    make[3]: *** [../ebin/dbg_wx_filedialog_win.beam] Error 1
    make[2]: *** [opt] Error 2
    make[1]: *** [opt] Error 2
    make: *** [libs] Error 2

This is on macOS Catalina 10.15.4, completely up to date with Apple patches.

Note also that building the 23.0 source tarball with these same `configure` options works correctly.

There's an old installation of `wxWidgets` on this machine, version 3.0.2, that is no doubt causing some of the error messages above, but those same messages do not occur with `kerl` 1.8.7 nor when building the tarball directly.

**Comment by mrallen1** [comment]
Thanks for the report. Unsure why kerl behaves like this right now though.

**Comment by rjcoelho** [comment]
same error when compiling otp-18.3
kerl build git https://github.com/erlang/otp.git OTP-18.3 OTP-18.3 

using KERL_CONFIGURE_OPTIONS                                                                                                                                                                                                                                                  
--without-javac --enable-hipe --enable-builtin-zlib --without-odbc --without-wx

**Comment by paulo-ferraz-oliveira** [comment]
I still don't have an official answer to https://bugs.erlang.org/browse/ERL-1472, but in Slack I was advised that there's no dependency resolution for the build flow, which means that if you do `--without-wx` you need to do the same for `et`, `observer` and `debugger`.

@mrallen1: this is not a `kerl`-specific issue.

**Comment by mrallen1** [comment]
Thanks for the clarification @paulo-ferraz-oliveira :+1:

**Comment by nihilismus** [comment]
The options suggested by @rjcoelho let me install _Erlang 23.0_ successfully. I'm in _Void Linux x86_64_ using _kerl 2.1.0_ and _kiex_:

```
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.11.0 (compiled with Erlang/OTP 23)
IEx 1.11.0 (compiled with Erlang/OTP 23)
Mix 1.11.0 (compiled with Erlang/OTP 23)
```

**Comment by paulo-ferraz-oliveira** [comment]
@mrallen1, some recent developments in Erlang/OTP move toward fixing what issue this refers to. Since this is not `kerl` specific, as pointed out previously, I propose closing it.

**Comment by mrallen1** [comment]
ok thanks
