### ISSUE TITLE
Can't choose more then one doc target

### ISSUE THREAD

**Issue by maxno-kivra** [kerl/kerl#341]
In https://github.com/kerl/kerl/pull/336 support for building the new doc chunks were added by setting `DOC_TARGETS` when building the docs. This is great, and even better you can tweak said `DOC_TARGETS` using `KERL_DOC_TARGETS`.

I like having the man pages around, and also be able to use `h/1` in the shell would be nice. Unfortunately you can only build one such doc target, as the string concatenation here:

https://github.com/kerl/kerl/blob/cd6280cb7de71e0d3c3c61648aeca12e2b70cffb/kerl#L947-L948

Makes the build fail with ``make[3]: *** No rule to make target `chunks', needed by `docs'.  Stop.``, when `KERL_DOC_TARGETS="man chunks"`.

Manually running `make release_docs DOC_TARGETS="man chunks"` works like a charm though.

The solution is probably to avoid string concatenation altogether. I'm thinking either writing out the command in full every time it's run (maybe another small helper function?), or setting `DOC_TARGETS` as an exported environmental variable and hope `make` picks it up. The latter _should_ work on most systems, but if kerl wants to support stuff like AIX/Sun/Solaris/... then it might be a solution.

What do you think?

**Comment by maxnordlund** [comment]
@mrallen1 since you've been working a bit on this, what do you think?

**Comment by maxno-kivra** [comment]
@mrallen1 since you've been working a bit on this, what do you think?

**Comment by mrallen1** [comment]
I haven't worked on it at all. I would be happy to take a PR implementing a proposed solution though. :)

**Comment by maxno-kivra** [comment]
Do you know if exporting `DOC_TARGETS` is enough for make to pick it up? Never really used that feature of make to be honest.

**Comment by mrallen1** [comment]
Offhand, no, sorry I don't know.

**Comment by maxno-kivra** [comment]
I'll experiment then. Wish me luck 🙂

**Comment by maxno-kivra** [comment]
Just want to mention I have fixed this in #344, for those who stumble upon this in the future. Hopefully it gets merged soonish. 😄

**Comment by mrallen1** [comment]
I would appreciate testing on #362 if you have time - thanks!
