### ISSUE TITLE
Pre-built source files now on github

### ISSUE THREAD

**Issue by garazdawi** [kerl/kerl#351]
Hello,

I recently added prebuilt source tar archives to github. See the assets on https://github.com/erlang/otp/releases/tag/OTP-23.1 for example. From now on, all releases and patches will have these prebuilt archives, so if you want to speed up the building of Erlang/OTP  you can use these instead of the archives built by github.

Also all existing prebuilt archives are in the process of being synced over to github, see https://github.com/erlang/otp/releases/tag/OTP-21.0 as an example. So for the places where you previously used `KERL_BUILD_BACKEND=tarball` you can now download from github and not have the issue of erlang.org being slow/unavailable.

If you need any help or have any questions, do let me know.

**Comment by mrallen1** [comment]
Thanks for letting me know!

**Comment by garazdawi** [comment]
This is also relevant: https://github.com/erlang/otp/pull/2782

It will take a while for all old patches to be built, but when they are you can get any patch including and after 21 as a pre-build .tar.gz from github.
