### ISSUE TITLE
Can't build any versions on Arch using autoconf 2.70

### ISSUE THREAD

**Issue by doughsay** [kerl/kerl#359]
I'm on an up-to-date Arch system that has recently updated to autoconf 2.70.  I'm pretty sure this is the culprit, but I could be wrong.

Building any version I've tried results in this:

```
Extracting source code
mv: cannot move './otp-OTP-23.2.1' to '/home/chris/.kerl/builds/23.2.1/otp_src_23.2.1/otp-OTP-23.2.1': Directory not empty
Building Erlang/OTP 23.2.1 (23.2.1), please wait...
Configure failed.
config.status: x86_64-unknown-linux-gnu/config.h is unchanged
config.status: creating include/internal/x86_64-unknown-linux-gnu/ethread_header_config.h
config.status: include/internal/x86_64-unknown-linux-gnu/ethread_header_config.h is unchanged
config.status: creating include/x86_64-unknown-linux-gnu/erl_int_sizes_config.h
config.status: include/x86_64-unknown-linux-gnu/erl_int_sizes_config.h is unchanged

=== Running configure in /home/chris/.kerl/builds/23.2.1/otp_src_23.2.1/make ===
./configure --disable-option-checking --cache-file=/dev/null --srcdir="/home/chris/.kerl/builds/23.2.1/otp_src_23.2.1/make"
configure: error: cannot find required auxiliary files: install-sh config.guess config.sub
ERROR: /home/chris/.kerl/builds/23.2.1/otp_src_23.2.1/make/configure failed!

Please see /home/chris/.kerl/builds/23.2.1/otp_build_23.2.1.log for full details.
```

build log attached:
[otp_build_23.2.1.log](https://github.com/kerl/kerl/files/5772139/otp_build_23.2.1.log)

**Comment by doughsay** [comment]
Here's a related PR in erlang/otp: https://github.com/erlang/otp/pull/2948

I assume `kerl` will have to apply a similar patch for older builds...?

**Comment by Isaius** [comment]
I think so. I was able to build without using `kerl`, but when tried (using asdf) didn't work. That explains why.
And I was on Arch too.

**Comment by doughsay** [comment]
I'm not really sure how to make this a clean PR to kerl, but here's my brute-force patched version of kerl: https://gist.github.com/doughsay/009661034ac6da463914ebd6233b6da8

This works for me on Arch installing latest Erlang/OTP (23.2.1), YMMV

Relevant addition is here: https://gist.github.com/doughsay/009661034ac6da463914ebd6233b6da8#file-kerl-sh-L650

If you're using `asdf-erlang` you can patch the version of kerl in `~/.asdf/plugins/erlang/kerl`

**Comment by rokku3kpvc** [comment]
on Arch when installing Erlang (22.2.3) the most easiest way for me to avoid this issue was downgrading autoconf to 2.69:
`sudo DOWNGRADE_FROM_ALA=1 downgrade autoconf`

but then I stucked with this problem https://github.com/kerl/kerl/issues/347
and in my case, using [gcc9](https://aur.archlinux.org/packages/gcc9/) was the right solution:
`CC=gcc-9 asdf install erlang 22.2.3`

**Comment by paulo-ferraz-oliveira** [comment]
I had this issue. Had to downgrade to `autoconf 2.69` too.
