### ISSUE TITLE
`kerl version` returns 2.0.1

### ISSUE THREAD

**Issue by halostatue** [kerl/kerl#368]
I’ve installed with homebrew, which shows that 2.1.1 was installed, but the installed script reports `2.0.1`.

**Comment by paulo-ferraz-oliveira** [comment]
I installed via `curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl` and get the proper version.

**Comment by paulo-ferraz-oliveira** [comment]
I uninstalled my version, installed via `brew` and get the correct version also.

**Comment by paulo-ferraz-oliveira** [comment]
Might you have some other version in your path that's been called instead of `brew`'s?

**Comment by halostatue** [comment]
Good call. I had a different locally installed version.
