### ISSUE TITLE
macOS fails to build OTP <23.2.2 after latest Xcode tools

### ISSUE THREAD

**Issue by rmpalomino** [kerl/kerl#369]
# Problem 
OTP builds including 23.2.1 and below are failing after installing the latest XCode command line tools, with the following error:

```
❯ kerl build 23.2.1
Downloading OTP-23.2.1.tar.gz to /Users/rpalomino/.kerl/archives...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    289      0 --:--:-- --:--:-- --:--:--   289
100 53.9M    0 53.9M    0     0  6482k      0 --:--:--  0:00:08 --:--:-- 7697k
Extracting source code
Building Erlang/OTP 23.2.1 (23.2.1), please wait...
Configure failed.
config.status: x86_64-apple-darwin20.3.0/config.h is unchanged
config.status: creating include/internal/x86_64-apple-darwin20.3.0/ethread_header_config.h
config.status: include/internal/x86_64-apple-darwin20.3.0/ethread_header_config.h is unchanged
config.status: creating include/x86_64-apple-darwin20.3.0/erl_int_sizes_config.h
config.status: include/x86_64-apple-darwin20.3.0/erl_int_sizes_config.h is unchanged

=== Running configure in /Users/rpalomino/.kerl/builds/23.2.1/otp_src_23.2.1/make ===
./configure '--enable-smp-support' '--enable-threads' '--enable-kernel-poll' '--enable-hipe' '--enable-darwin-64bit' '--with-ssl=/usr/local/opt/openssl@1.1' '--without-odbc' CFLAGS='-m64 -g -O2' LDFLAGS='-m64 ' --enable-m64-build --disable-option-checking --cache-file=/dev/null --srcdir="/Users/rpalomino/.kerl/builds/23.2.1/otp_src_23.2.1/make"
configure: error: cannot find required auxiliary files: install-sh config.guess config.sub
ERROR: /Users/rpalomino/.kerl/builds/23.2.1/otp_src_23.2.1/make/configure failed!

Please see /Users/rpalomino/.kerl/builds/23.2.1/otp_build_23.2.1.log for full details.
```

I updated the Xcode command line tools by running `xcode-select --install` after seeing that Homebrew needed updated tools to upgrade the Python formula.

Xcode, autoconf, automake versions (truncated output):
```
❯ xcode-select -v
xcode-select version 2384.

❯ autoconf --version
autoconf (GNU Autoconf) 2.71

❯ automake --version
automake (GNU automake) 1.16.3

❯ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

# Workaround
I did the following to get a build working for 21.3.8.17 after seeing that erlang/otp was [patched for OTP 23.2.2+](https://github.com/erlang/otp/pull/2948/commits/c5b04efb55304a7c6f569c33c8e5875a32877f31):
* Checked out erlang/otp
* Ran `git format-patch -1 -p c5b04efb55304a7c6f569c33c8e5875a32877f31`
* Copied patch to clipboard
* Ran `kerl build 21.3.8.17` to create the build directory `~/.kerl/builds/21.3.8.17/otp_src_21.3.8.17`
* Saved patch to a file in `~/.kerl/builds/21.3.8.17/otp_src_21.3.8.17`
* Applied the patch to `~/.kerl/builds/21.3.8.17/otp_src_21.3.8.17`

**Comment by luisdlopez** [comment]
I have this exact same issue while trying to install Erlang/OTP 22.3.3 (or any 22.x.x version) **using asdf**

All versions for xcode, autoconf, automake and gcc are the same. The "missing" auxiliary files are present, the make file just cannot find them.

**Comment by rjcoelho** [comment]
@rmpalomino should we include patch in kerl code it so It can automatically path when needed and thus avoid manual intervention which may fail as seen by @luisdlopez ? If so open a pr I say

**Comment by lamboap** [comment]
any update to this?  I believe I have the same issue can't build erlang 22.0.7using asdf after updating xcode and brew upgrade

**Comment by nalundgaard** [comment]
See https://github.com/kerl/kerl/issues/359, it looks to me like autoconf is the problem, not xcode. Downgrading to autoconf 2.69 seems to do the trick:

```sh
brew install autoconf@2.69
brew unlink autoconf
brew link autoconf@2.69
```

It would be nice to backport this patch for newer autoconf for OTP 20-22 at least, but this is certainly an easier workaround.
