### ISSUE TITLE
Lot of false warnings on Arch Linux with dpkg package installed

### ISSUE THREAD

**Issue by Sgiath** [kerl/kerl#375]
I am getting these warnings:

```
WARNING: It appears that a required development package 'libssl-dev' is not installed.
WARNING: It appears that a required development package 'make' is not installed.
WARNING: It appears that a required development package 'automake' is not installed.
WARNING: It appears that a required development package 'autoconf' is not installed.
WARNING: It appears that a required development package 'libncurses5-dev' is not installed.
WARNING: It appears that a required development package 'gcc' is not installed.
```

The reason is that I am on Arch Linux and installed [dpkg](https://archlinux.org/packages/community/x86_64/dpkg/) package which allows me to install `.deb` archives but most of the packages are installed through native package manager `pacman`.

Could the mechanism for checking used package manager be more strict? I get that I can ignore the warnings but they are annoying and false.

**Comment by jadeallenx** [comment]
Sorry it's annoying - for 99% of our users these warnings are helpful and useful. If you have a suggestion how to detect this scenario I'd be open to a PR. Thanks for the report.

**Comment by skwerlman** [comment]
hitting a similar issue, also on arch linux, but in my case i have `rpm-tools` installed instead of `dpkg`

**Comment by paulo-ferraz-oliveira** [comment]
👋 Pull requests are accepted, as per @jadeallenx above.

**Comment by jadeallenx** [comment]
I do think we should overhaul how we are checking for build prereqs because I am tired of these tickets for SuSE and Arch and whatever other random Linuxes out there. (Sorry @skwerlman this isn't directed at you, just my frustration that we do an incomplete job and we shouldn't keep adding new flavors of Linuxes and their package names as one-offs)

**Comment by paulo-ferraz-oliveira** [comment]
What do you propose, @jadeallenx? Do the packages we search have common names across the distros? Or are placed in the same folders? I don't see a very easy way to do much different from what we're doing, but I'd love to learn.

**Comment by jadeallenx** [comment]
> What do you propose, @jadeallenx? Do the packages we search have common names across the distros? Or are placed in the same folders? I don't see a very easy way to do much different from what we're doing, but I'd love to learn.

See #439 probably should migrate discussion of this to that issue.

**Comment by skwerlman** [comment]
it might be possible to do an okay job of guessing which package manager to use for package checks by looking at `/etc/os-release` which is _usually_ populated with info about the distro.

Then if the ID and ID_LIKE dont match any distro you support for package checks, just warn to the user and continue

https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, but that's the thing. At the moment we do stuff like

```bash
    has_dpkg=$(command -v dpkg)
    has_rpm=$(command -v rpm)
    has_apk=$(command -v apk)
```

which seems more generic than supporting specific distros. It's my understanding we should support package managers and/or presence of packages, and not start with distros, but I might be missing something from your comment.

@jadeallenx, what we could do is add a flag for "no_warn" (in which case the consumer knows they don't want to be warned) and keep adding checks where we believe they'll be useful for the majority of consumers (or all, even, if possible) 😄.

**Comment by paulo-ferraz-oliveira** [comment]
Only saw your comment now 😓. Discussion is then considered _migrated_. @skwerlman, feel free to continue there and/or suggest on top of what @jadeallenx already did. Closing...
