### ISSUE TITLE
everytime open a new WLS terminal, I have to activate erl

### ISSUE THREAD

**Issue by DominicGame** [kerl/kerl#382]
first of all, I'm going to work with window linux shell(wls), but I'm not familiar to linux

I have 'activate' an otp in A terminal
then, I start B terminal and `kerl status` show
```
Available builds:
23.3.4.7,23
----------
Available installations:
23 /otp/23
----------
No Erlang/OTP installation is currently active
```

I found the 'export' command don't work on the diff terminal
So, If I have to write some code to avoid 'activate' everytime when  I open a  new terminal
just like
`if(last_otp) activate(last_otp)`

**Comment by jadeallenx** [comment]
Well if you want to activate an installation when you start a shell instance you can add the activate command to your `.profile`

I’m not sure what flavor of Linux you have set up in WSL but they all support that.

**Comment by DominicGame** [comment]
oh, I see, thanks for your reply.
