### ISSUE TITLE
Wx issue when trying to install Erlang 24.1.4 on OSX 10.15.7

### ISSUE THREAD

**Issue by Stratus3D** [kerl/kerl#386]
I tried installing Erlang 24.1.4 on OSX 10.15.7 via asdf-erlang and kerl. It kept failing on some wx code, so I tried disabling wx and compiling, but it still failed, just at a different point in compilation.

```
$ export KERL_CONFIGURE_OPTIONS="--with-ssl=`brew --prefix openssl@1.1` \
                               --without-wx \
                               --without-javac"

$ asdf install erlang 24.1.4                                             
asdf_24.1.4 is not a kerl-managed Erlang/OTP installation
The asdf_24.1.4 build has been deleted
Extracting source code
Building Erlang/OTP 24.1.4 (asdf_24.1.4), please wait...
APPLICATIONS DISABLED (See: /Users/trevorbrown/.asdf/plugins/erlang/kerl-home/builds/asdf_24.1.4/otp_build_24.1.4.log)
 * jinterface     : Java compiler disabled by user
 * wx             : User gave --without-wx option

^[Build failed.
compile: warnings being treated as errors
dbg_wx_filedialog_win.erl:22:2: behaviour wx_object undefined
%   22| -behaviour(wx_object).
%     |  ^

make[3]: *** [../ebin/dbg_wx_filedialog_win.beam] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [opt] Error 2
make[1]: *** [opt] Error 2
make: *** [libs] Error 2

Please see /Users/trevorbrown/.asdf/plugins/erlang/kerl-home/builds/asdf_24.1.4/otp_build_24.1.4.log for full details.
```

It's odd to me that it acknowledges that I disabled wx, but then fails when trying to compile a file that appears to be dependent on wx. Any idea what is going on here? This is the first time I've encountered this particular error. Let me know if I should open an issue on the Erlang issue tracker instead. Thanks!

**Comment by Stratus3D** [comment]
I just confirmed Erlang 24.1.3 compiled with no issues. Not sure what got introduced in Erlang 24.1.4.

**Comment by Stratus3D** [comment]
I don't see many differences between these two Erlang versions. https://github.com/erlang/otp/compare/OTP-24.1.3...OTP-24.1.4

**Comment by garazdawi** [comment]
I don't know why `24.1.4` fails, but the `--without-*` mechanism of `./configure` is not clever enough to figure out which applications depend on which so you will have to also supply other applications that need wx to work.

**Comment by paulo-ferraz-oliveira** [comment]
@Stratus3D, I'm tentatively closing this issue, as it seems to not be relevant at the moment. Feel free to reopen if you want to discuss further. Fwiw, `kerl` CI goes over 24 and `wx`.
