### ISSUE TITLE
How to manage downloads in `KERL_DOWNLOAD_DIR`?

### ISSUE THREAD

**Issue by Stratus3D** [kerl/kerl#387]
> I currently have 28 tarballs in `~/.asdf/plugins/erlang/kerl-home/archives` taking up 1.6 GB of space for only three versions of Erlang installed. Can any or all of these files be deleted? Is there a cleanup command somewhere that I'm missing?

-- @CraigCottingham - https://github.com/asdf-vm/asdf-erlang/issues/231

> @CraigCottingham I think so. However, the kerl docs don't explain how to manage the `KERL_DOWNLOAD_DIR`, and there don't appear to be any kerl commands for removing those archives. I tried running `./kerl cleanup all` and that did not remove them:
> 
> ```
> $ ls  ~/.asdf/plugins/erlang/kerl-home/archives    
> OTP-20.0.tar.gz      OTP-20.3.6.tar.gz    OTP-21.3.2.tar.gz    OTP-22.0.7.tar.gz    OTP-22.2.8.tar.gz    OTP-23.0.2.tar.gz    OTP-23.1.5.tar.gz    OTP-23.2.5.tar.gz    OTP-24.0.6.tar.gz    OTP-24.1.4.tar.gz
> OTP-20.1.tar.gz      OTP-20.3.8.22.tar.gz OTP-21.3.8.2.tar.gz  OTP-22.1.5.tar.gz    OTP-22.3.tar.gz      OTP-23.0.3.tar.gz    OTP-23.2.3.tar.gz    OTP-23.2.tar.gz      OTP-24.0.tar.gz      OTP_R16B03-1.tar.gz
> OTP-20.2.3.tar.gz    OTP-20.3.tar.gz      OTP-21.3.8.tar.gz    OTP-22.1.8.tar.gz    OTP-23.0.1.tar.gz    OTP-23.0.tar.gz      OTP-23.2.4.tar.gz    OTP-24.0.5.tar.gz    OTP-24.1.3.tar.gz
> 
> $ ./kerl cleanup all
> Cleaning up compilation products for ALL builds
> Cleaned up all compilation products under /Users/trevorbrown/.kerl/builds
> 
> $ ls  ~/.asdf/plugins/erlang/kerl-home/archives
> OTP-20.0.tar.gz      OTP-20.3.6.tar.gz    OTP-21.3.2.tar.gz    OTP-22.0.7.tar.gz    OTP-22.2.8.tar.gz    OTP-23.0.2.tar.gz    OTP-23.1.5.tar.gz    OTP-23.2.5.tar.gz    OTP-24.0.6.tar.gz    OTP-24.1.4.tar.gz
> OTP-20.1.tar.gz      OTP-20.3.8.22.tar.gz OTP-21.3.8.2.tar.gz  OTP-22.1.5.tar.gz    OTP-22.3.tar.gz      OTP-23.0.3.tar.gz    OTP-23.2.3.tar.gz    OTP-23.2.tar.gz      OTP-24.0.tar.gz      OTP_R16B03-1.tar.gz
> OTP-20.2.3.tar.gz    OTP-20.3.tar.gz      OTP-21.3.8.tar.gz    OTP-22.1.8.tar.gz    OTP-23.0.1.tar.gz    OTP-23.0.tar.gz      OTP-23.2.4.tar.gz    OTP-24.0.5.tar.gz    OTP-24.1.3.tar.gz
> ```
> 
> I am going to see if I can move this issue thread to the kerl repository because I think at the very least some documentation updates are needed there.

Questions:

* Can we safely delete the files in `KERL_DOWNLOAD_DIR` without causing any issues?
* Is there a kerl command to cleanup this directory or recommended way of cleaning up this directory manually?

**Comment by garazdawi** [comment]
`./kerl cleanup all` did not work because asdf runs kerl with `KERL_BASE_DIR` set to `~/.asdf/plugins/erlang/kerl-home/`. So if you run:

```sh
KERL_BASE_DIR=~/.asdf/plugins/erlang/kerl-home/ ./kerl cleanup all
```
the files should be removed.

**Comment by Stratus3D** [comment]
Thanks @garazdawi !
