### ISSUE TITLE
unable build opensuse

### ISSUE THREAD

**Issue by heiheshang** [kerl/kerl#393]
`Extracting source code
Building Erlang/OTP 23.3.4.7 (23.3.4.7), please wait...
WARNING: It appears a required development package 'openssl-devel' is not installed.
Build failed.
gmake[4]: x86_64-unknown-linux-gnu/Makefile: Нет такого файла или каталога
gmake[4]: *** No rule to make target 'x86_64-unknown-linux-gnu/Makefile'.  Stop.
gmake[4]: Leaving directory '/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/lib/crypto/c_src'
gmake[3]: *** [/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/lib/crypto/c_src'
gmake[2]: *** [/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/make/otp_subdir.mk:29: opt] Error 2
gmake[2]: Leaving directory '/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/lib/crypto'
gmake[1]: *** [/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/make/otp_subdir.mk:29: opt] Error 2
gmake[1]: Leaving directory '/home/oper/.kerl/builds/23.3.4.7/otp_src_23.3.4.7/lib'
gmake: *** [Makefile:505: libs] Error 2

Please see /home/oper/.kerl/builds/23.3.4.7/otp_build_23.3.4.7.log for full details.`

**Comment by crownedgrouse** [comment]
Just read the log ?
```
WARNING: It appears a required development package 'openssl-devel' is not installed.
Build failed.
```

**Comment by crownedgrouse** [comment]
Just read the log ?
```
WARNING: It appears a required development package 'openssl-devel' is not installed.
Build failed.
```

**Comment by crownedgrouse** [comment]
doubloon of #365

**Comment by crownedgrouse** [comment]
doubloon of #365

**Comment by heiheshang** [comment]
distro OpenSuse Tumblewed

**Comment by heiheshang** [comment]
> Just read the log ?
> 
> ```
> WARNING: It appears a required development package 'openssl-devel' is not installed.
> Build failed.
> ```

I read the logs, but in opensuse the package is called differently, and you have a binding to the package name

**Comment by jadeallenx** [comment]
It's a duplicate of an already open ticket, that's why it's closed.
