### ISSUE TITLE
KERL_ENABLE_PROMPT and RPROMPT

### ISSUE THREAD

**Issue by meangrape** [kerl/kerl#398]
Is there any way to switch kerl's version prompt to the right side? My left prompt is s bit busy, and the right side is where I keep my pyenv version so I'd like to be able to have them both on the right side.

I realize this isn't an issue of critical import nor one that many people care about.

**Comment by sanmiguel** [comment]
You can use the output of `kerl prompt` to insert anywhere you like in your prompt. Exactly how to do that will depend on which shell, how you've got it configured etc.
