### ISSUE TITLE
24.3 not available ?

### ISSUE THREAD

**Issue by crownedgrouse** [kerl/kerl#399]
Hi,
by doing `kerl update releases` I cannot see 24.3 .

Using version 1.8.6

**Comment by crownedgrouse** [comment]
By upgrading to last 2.2.4, it is OK.

Can we have somewhere abstract info of kerl versions vs otp version ?

**Comment by paulo-ferraz-oliveira** [comment]
Hi.

The list is generated automatically. So all the tags you find for OTP should be available from `kerl` after the `update releases`. Did you find a version that was not there?

Cheers.

**Comment by paulo-ferraz-oliveira** [comment]
There's one list for the `git` backend: https://github.com/kerl/kerl/blob/master/kerl#L220
There's one list for the `tarball` backend: https://github.com/kerl/kerl/blob/master/kerl#L310

**Comment by crownedgrouse** [comment]
I meant that kerl 1.8.6 didn't proposed me OTP 24.3 , but by upgrading kerl, it worked.
My question is : is there a table giving the minimum kerl version for an OTP version to be available ?

**Comment by paulo-ferraz-oliveira** [comment]
> My question is : is there a table giving the minimum kerl version for an OTP version to be available ?

I'm not sure, but I would assume (@jadeallenx can probably help here) the latest `kerl` version will always be able to fetch all the Erlang/OTP versions. I've never run into your particular issue, though.

**Comment by paulo-ferraz-oliveira** [comment]
> a kerl upgrade would be nice like make erlang-mkdoes for Erlang.mk Make script update, BTW.

I believe so, too. And when used it could even check the installed version and let you know of a potentially new one available. I love that `ohmyzsh` does this and I only have to say yes to self-upgrade.

Maybe create a new issue for tracking this particular request?

**Comment by crownedgrouse** [comment]
thanks for #400 . Closing .
