### ISSUE TITLE
--enable-hipe will silently not build with hipe if M4 is not available

### ISSUE THREAD

**Issue by jeremyong** [kerl/kerl#40]
Providing --enable-hipe as in `KERL_CONFIGURE_OPTIONS` will build the erlang release without hipe if M4 is not installed.

**Comment by mrallen1** [comment]
We need to determine if this is still a problem with recent OTP releases.  In general, I think kerl ought to warn users if they have unmet pre-requisites for a specific feature they requested.

**Comment by mrallen1** [comment]
Looking at #53 for this issue.

**Comment by mrallen1** [comment]
I think #148 resolves this issue. Please reopen if needed.
