### ISSUE TITLE
RFC: Deprecate and remove docsh

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#404]
@erszcz I have been thinking about removing the docsh support in a future release of kerl. Do you have any thoughts about that?

**Comment by erszcz** [comment]
Only one - it provides the functionality for versions of Erlang prior to 23 / 24 which bring `shell_docs` (the former just for OTP docs, the latter also for non-OTP / community projects). That's the only thing I can think of. Given OTP 25 is around the corner, I think it's reasonable to phase docsh out :+1:

**Comment by paulo-ferraz-oliveira** [comment]
I believe this is handled by https://github.com/kerl/kerl/pull/445, which I've just linked. Closing...
