### ISSUE TITLE
Clean up old documentation

### ISSUE THREAD

**Issue by jadeallenx** [kerl/kerl#405]
Some of the documentation about crypto support and Erlang is pretty old and misleading at this point. It should be removed.

The rest of the docs should probably get a once over since it's been a few years since we really worked on the docs much.

**Comment by paulo-ferraz-oliveira** [comment]
Apart from not mentioning more recent versions of macos in the README ("Compiling crypto on older macOS") I think most stuff should be up-to-date per #449. What do you think, @jadeallenx? Feel free to close if you think it's handled, or comment on a way I could improve the doc, if you feel it's important. 😄

**Comment by jadeallenx** [comment]
Yeah this is probably good for the moment. We can always improve the docs but... 449 was a good overhaul
