### ISSUE TITLE
Kerl Build Fails on Various MacOS Hosts and Various Releases

### ISSUE THREAD

**Issue by cogitaria-admin** [kerl/kerl#413]
Here are a couple of failures just trying to get a bare-bones Erlang development environment setup. on MacOS  I have Xcode and updated openssl and such.  This is my Erlang version: Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit] [dtrace]

I'm running this build on macOS Monterey (also fails on Catalina but did work on that host in the past)
-------------------------
> kerl build 24.0 24.0
-n Extracting source code
-n Building Erlang/OTP 24.0 (24.0), please wait...
Build failed.
  const wxBitmap * Result = &This->GetBitmap();
                            ^~~~~~~~~~~~~~~~~~
----------------------------------------------------------
On the same box building 25.0 you get a different result:
--------------------
kerl build 25.0 25.0
-n Extracting source code
-n Building Erlang/OTP 25.0 (25.0), please wait...
Build failed.
gmake[4]: x86_64-apple-darwin21.4.0/Makefile: No such file or directory
gmake[4]: *** No rule to make target 'x86_64-apple-darwin21.4.0/Makefile'.  Stop.

I'm trying to "adopt Erlang" and this site was super awesome: https://adoptingerlang.org/ if only it worked (kerl build fails so you cannot get past **go**). 

Thanks for helping!

**Comment by jadeallenx** [comment]
What version of kerl are you using? `kerl version` or `kerl status` should tell you.

**Comment by garazdawi** [comment]
The problem with building Erlang/OTP 24.0 on macOS Monterey is because the WxWidget library did a breaking change in their API. The problem has been fixed with [this patch](https://github.com/erlang/otp/pull/5912) in [Erlang/OTP 24.3.4](https://www.erlang.org/patches/otp-24.3.4#OTP-18064). It might be a good idea (tm) for kerl to apply that patch to all Erlang versions.

Regarding the second problem, there should have been a message such as "Please see /some/file/path for full details.". Can you attach that log file to this issue?

**Comment by cogitaria-admin** [comment]
Kerl version: 2.5.0

**Comment by cogitaria-admin** [comment]
[otp_build_25.0.log](https://github.com/kerl/kerl/files/8863991/otp_build_25.0.log)

Attached the build log for the 25.0 build

**Comment by garazdawi** [comment]
> [otp_build_25.0.log](https://github.com/kerl/kerl/files/8863991/otp_build_25.0.log)
> 
> Attached the build log for the 25.0 build

The log seems to be of a re-run of `kerl build 25.0`. Can you remove the build (`kerl delete build 25.0`) and then try again and attach the log after that build.

**Comment by cogitaria-admin** [comment]
[otp_build_25.0.log](https://github.com/kerl/kerl/files/8864300/otp_build_25.0.log)
 
Deleted and re-ran 25.0 build.

**Comment by garazdawi** [comment]
The crypto configure log shows this error:

> configure: error: Invalid path to option --with-ssl=PATH
> ERROR: /Users/cogitaria/.kerl/builds/25.0/otp_src_25.0/lib/crypto/configure failed!

That error only happens when the path given to `--with-ssl` does not exist. Could it be that openssl is installed in a different directory than `/usr/local/Cellar/openssl/1.0.2q/`? If you are using homebrew to install, you can find the path by calling `brew --prefix openssl` (or `brew --prefix openssl@1.0.2q` if you specifically want the 1.0.2q version of openssl).

I will see if I can provide a patch to kerl that will abort the build when the configure fails. That should give the user a better idea about what has happened.  Trying to build with a half-configured system will never work.

**Comment by cogitaria-admin** [comment]
So that missing openssl was a experiment gone wrong. I had set these vars as indicated in _Adopting Erlang_ and that's **not** what is in my cellar.  

```
SSL_PATH=/usr/local/Cellar/openssl/1.0.2q/
export KERL_BUILD_BACKEND="git"
export KERL_CONFIGURE_OPTIONS="--without-javac \
			       --with-dynamic-trace=dtrace \
			       --with-ssl=${SSL_PATH}"
```

I changed to /usr/local/Cellar/openssl@1.1 and now it's back to this:

```
Build failed.
gmake[4]: x86_64-apple-darwin21.4.0/Makefile: No such file or directory 	 
```   
I kerl deleted 25.0 then kerl build 25.0 again. Here's that log:

[otp_build_25.0.log](https://github.com/kerl/kerl/files/8865458/otp_build_25.0.log)

**Comment by garazdawi** [comment]
> checking for OpenSSL header in /usr/local/Cellar/openssl@1.1... configure: error: no OpenSSL header found in /usr/local/Cellar/openssl@1.1
> ERROR: /Users/cogitaria/.kerl/builds/25.0/otp_src_25.0/lib/crypto/configure failed!

There is still something wrong with the openssl configuration. There is supposed to be a file called `/usr/local/Cellar/openssl@1.1/include/openssl/opensslv.h` that the configure script cannot find.

[Others with similar issue](https://github.com/asdf-vm/asdf-erlang/issues/82#issuecomment-663936483) seems to have fixed it by re-installing openssl: `brew reinstall openssl@1.1` and then delete + build Erlang again.

**Comment by cogitaria-admin** [comment]
Turns out the default `/usr/local/Cellar/openssl/1.0.2q/` does not exist.   

Inspecting /usr/local/Cellar/openssl... on my two macOS host reveals these: 

**Catalina**: /usr/local/Cellar/openssl@1.1/1.1.1k/
**Monterey**: /usr/local/Cellar/openssl@1.1/1.1.1o/

Substituting the appropriate path to --with-ssl= results in a successful build of 24.0 on Catalina.  

The 24.0 build still **fails** with the wxBitmap issue (no surprise).  

Building 25.0 works on both Catalina and Monterey with the appropriate --with-ssl path. 

```
export KERL_CONFIGURE_OPTIONS="--without-javac --with-dynamic-trace=dtrace  --with-ssl=/usr/local/Cellar/openssl@1.1/1.1.1o/"
export KERL_BUILD_BACKEND="git"
```

**Comment by cogitaria-admin** [comment]
I should note for future reference that this arose because openssl on macOS releases points to a supposedly superior (more secure, removed obsolete code...) called LibreSSL and for whatever reason that causes kerl builds to fail. The fix as outlined in https://adoptingerlang.org/docs/development/setup/ is to install a recent version of openssl with brew, and set that KERL_CONFIGURE_OPTIONS variable to include --with-ssl.
