### ISSUE TITLE
kerl outputting result of uname | grep

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [kerl/kerl#416]
I think this might be a recent addition to the code...

```
Extracting source code
Building Erlang/OTP 24.3.4.4 (24.3.4.4), please wait...
21.6.0
^ this
```

It confused me, since I was installing 24.3.4.4 and there was an extra output stating 21.6.0. It appears this output comes from https://github.com/kerl/kerl/blob/master/kerl#L858, which is potentially possible to hide. At this moment I just wanted to report this, so I don't forget it, and maybe in the future I might tackle it, if time allows and I don't forget 😄.

**Comment by jadeallenx** [comment]
Thank you for reporting the issue

**Comment by paulo-ferraz-oliveira** [comment]
These changes seem to have been made by @garazdawi, so I'm inclined to say they're Ok, but in any case they still print out something that might be unwanted.
