### ISSUE TITLE
WARNING: It appears a required development package 'g++' is not installed.

### ISSUE THREAD

**Issue by steakknife** [kerl/kerl#430]
There is no such package as `g++`, it's `gcc-c++`, so I think I'll just install erlang myself because apparently no one uses or tests this.

**Comment by paulo-ferraz-oliveira** [comment]
@steakknife, I'm not sure what you're referring to when you write "apparently no one uses or tests this", but if it's "`kerl` as an Erlang installer", I believe you might be wrong.

As for the `g++` package, it [exists at least for Ubuntu](https://packages.ubuntu.com/bionic/g++), which is what we're using in CI.

It is possible you're on Fedora. I've never tested using that distro.

But if there are enough consumers for that, and `kerl` is a valid solution for them, pull requests are accepted. 😄

**Comment by paulo-ferraz-oliveira** [comment]
Using a Fedora container for `fedora:latest` when I do `yum install -g++`, I get

```
Installing:
 gcc-c++ ...
Installing dependencies:
 libstdc++-devel ...
```

**Comment by paulo-ferraz-oliveira** [comment]
Build on Fedora was successful by just installing a few packages as proposed by `kerl`.

**Comment by jadeallenx** [comment]
I suppose they have renamed the packages since we made that list of rpm’s so I guess we will have to check for both?

**Comment by paulo-ferraz-oliveira** [comment]
Yeah. I'm going to create an issue for this. Thanks.
