### ISSUE TITLE
Building Erlang 23 freezes on macOS 

### ISSUE THREAD

**Issue by eproxus** [kerl/kerl#434]
If I try to build 23.3.4.18 on macOS Ventura 13.2 it freezes when patching `configure.in` at this point: https://github.com/kerl/kerl/blob/master/kerl#L768

If I check the build log at `$KERL_HOME/builds/my_build_23.3.4.18/otp_build_23.3.4.18.log` it only shows this text:

```
patching file 'erts/configure.in'
Reversed (or previously applied) patch detected!  Assume -R? [y] 
```

As far as I can tell, that patch is already in OTP 23 (see the list of tags here https://github.com/erlang/otp/commit/4b0467c).

In fact, it even seems that the configure scripts are checked in for OTP 23 so maybe `KERL_USE_AUTOCONF=1` shouldn't be used at all?

**Comment by paulo-ferraz-oliveira** [comment]
Hey.

Yeah, I though about that in the past (that the configure scripts are checked in, and the option might be deprecated by this time around). Care to pull request removing the interesting bits 😄? CI should be able to tell us if stuff's as it should.

Cheers.

**Comment by eproxus** [comment]
If I look at the OTP commit it seems it is in 23.1+, but not e.g. 23.0. I guess there's no easy way to do that test for minor versions in kerl?

**Comment by paulo-ferraz-oliveira** [comment]
There's something similar [here](https://github.com/kerl/kerl/blob/master/kerl#L781). Does that help?

**Comment by electricshaman** [comment]
Hilariously, I just noticed I can get past the freeze by hitting enter at the prompt regarding the patch.  It's waiting for input, not doing anything.  Not ideal for an automated script, but at least the build moves forward.
