### ISSUE TITLE
support clone with depth 1

### ISSUE THREAD

**Issue by lafirest** [kerl/kerl#447]
most of the time, when we build from a repo that we don't need to clone all history of this repo, this repo is temporary, hence we could clone it only with depth 1 to speed up 
<img width="706" alt="bildo" src="https://github.com/kerl/kerl/assets/22971499/ec36628d-3614-43dd-9304-d67f767af284">
with depth 1, the size can reduce to half

**Comment by paulo-ferraz-oliveira** [comment]
From what I see we only do remote clones [here](https://github.com/kerl/kerl/blob/master/kerl#L623) (there's also another clone, but it's local).

I think it should be acceptable to have an option like `KERL_GIT_CLONE_DEPTH` to limit the clone (as you propose). By default, though, we need to keep behaviour as is.

Thoughts, @jadeallenx?

**Comment by jadeallenx** [comment]
I have no strong opinion one way or the other. It would be nice to support a shallower clone since it would save space, but I think the default behavior should remain as-is like @paulo-ferraz-oliveira suggested.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, @jadeallenx. @lafirest, it seems this is good to go, then. 👍

We can accept a pull request. Don't forget to update the README with the new env.var and an indication of the default, and also add at least one tests that validates implementation.
