### ISSUE TITLE
"CFLAGS for -O switch" configure error

### ISSUE THREAD

**Issue by Grimgrams** [kerl/kerl#450]
Hi,
I am trying to install a version of erlang but every time I try to build, I get this error.

```
Configure failed.
checking for a compiler that handles jumptables... clang
checking for kstat_open in -lkstat... (cached) no
checking for kvm_open in -lkvm... no
checking for log2... yes
checking CFLAGS for -O switch... configure: error:
	CFLAGS must contain a -O flag. If you need to edit the CFLAGS you probably
	also want to add the default CFLAGS. The default CFLAGS are "-O2 -g".
	If you want to build ERTS without any optimization, pass -O0 to CFLAGS.
ERROR: /Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts/configure failed!
./configure: line 366: kill: (-59851) - No such process
```

**Comment by garazdawi** [comment]
What does your CFLAGS environment variable say? Can you post the log of the build?

**Comment by paulo-ferraz-oliveira** [comment]
@garazdawi, is there such a thing as a "default" or "best" O flag? If so, `kerl` could probably apply it. Otherwise we can always leave it as-is and let Erlang complain as above (?)

**Comment by Grimgrams** [comment]
here's the build log.
[otp_build_25.0.log](https://github.com/kerl/kerl/files/12140070/otp_build_25.0.log)

**Comment by garazdawi** [comment]
`-O2` is default and probably best. `-O3` does a lot of fancy things, but normally have very minimal effect. I think that kerl should leave it alone and let the user and Erlang configure decide what to set it to.

**Comment by garazdawi** [comment]
@Grimgrams your CFLAGS is set to, `CFLAGS='-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include'`. You need to add a `-O` in there (just as the error message says).

**Comment by Grimgrams** [comment]
> @Grimgrams your CFLAGS is set to, `CFLAGS='-I/usr/local/opt/openssl/include/ -I/usr/local/include -I/usr/local/opt/expat/include'`. You need to add a `-O` in there (just as the error message says).

Thank You! This worked but now I am getting a **build** error this time

```APPLICATIONS DISABLED (See: /Users/grimgram/.kerl/builds/25.0/otp_build_25.0.log)
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /Users/grimgram/.kerl/builds/25.0/otp_build_25.0.log)
 * wx             : wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
 * Can not link wx program are all developer packages installed?

Build failed.
5 warnings and 2 errors generated.
gmake[4]: *** [aarch64-apple-darwin23.0.0/Makefile:909: obj/aarch64-apple-darwin23.0.0/opt/jit/inet_drv.o] Error 1
gmake[4]: Leaving directory '/Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts/emulator'
gmake[3]: *** [/Users/grimgram/.kerl/builds/25.0/otp_src_25.0/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts/emulator'
gmake[2]: *** [Makefile:45: opt] Error 2
gmake[2]: Leaving directory '/Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts'
gmake[1]: *** [Makefile:60: jit] Error 2
gmake[1]: Leaving directory '/Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts'
gmake: *** [Makefile:496: emulator] Error 2```

here is the build log for this one.
[otp_build_25.0.log](https://github.com/kerl/kerl/files/12153081/otp_build_25.0.log)

**Comment by garazdawi** [comment]
You seem to be running MacOS Sonoma? Apple seems to have changed some things that makes Erlang 25.0 not compile anymore. Try compiling Erlang 26.0.2 and see if that works.

**Comment by Grimgrams** [comment]
Yeah, I thought that might be the problem I wasn't sure though.

**Comment by Grimgrams** [comment]
I went back to macOS Ventura and I am now getting this error.

```
Configure failed.
checking for getrusage... yes
checking for sys/event.h... yes
checking for sys/epoll.h... no
checking for sys/devpoll.h... no
checking for sys/timerfd.h... no
checking for netpacket/packet.h... no
checking for netinet/sctp.h... no
configure: error: sctp support requested, but cannot be enabled since 'netinet/sctp.h' is missing
ERROR: /Users/grimgram/.kerl/builds/25.0/otp_src_25.0/erts/configure failed!
./configure: line 366: kill: (-86222) - No such process
```
I already installed libusrsctp with brew.

build log.
[otp_build_25.0.log](https://github.com/kerl/kerl/files/12223923/otp_build_25.0.log)

**Comment by garazdawi** [comment]
As noted in the [gen_sctp](https://www.erlang.org/doc/man/gen_sctp.html) manual, for sctp to work you need kernel support for sctp. Erlang cannot use a userspace sctp driver. 

I know there are people that have written nifs/linked in drivers around userspace sctp, though I’m unsure if any are released as opensource.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this as a non-`kerl` issue. Feel free to re-open if you feel otherwise.
