### ISSUE TITLE
Add 'kerl build source' to build from source

### ISSUE THREAD

**Issue by rlipscombe** [kerl/kerl#451]
When I'm hacking on Erlang/OTP, I like to have `use erlang source` in my `.envrc`; see https://blog.differentpla.net/blog/2019/01/30/integrating-kerl-direnv/ (though it's not strictly relevant to this issue).

At the moment, I have to "persuade" kerl to use my built-from-source; see https://blog.differentpla.net/blog/2023/01/10/erlang-source-with-direnv/

It would be nice if kerl had better support for building and (faking?) install from source.

Ideally, I'd just `kerl build source ~/Source/rlipscombe/otp source` and it would build in-place, and then `kerl install source ~/erlangs` would do the right thing.

**Comment by rlipscombe** [comment]
The main problem I have, it turns out, is that the `activate` script (which is what I actually want) is generated by `do_install`, so I have to jump through `kerl install` to get one generated.

If, instead, it was in its own function, I could `(source kerl && generate_activate_script STUFF)` maybe?

Or if the generated script set some variables at the top, rather than interpolating them in all over the place, I could just do a quick awk/sed on an existing copy of the script.

**Comment by rlipscombe** [comment]
> Would this be a new command?
Yes.

> Is it something like kerl build-source ~/Source/rlipscombe/otp <build_name> that you're "proposing"?
Also yes, though the first `source` in `kerl build source ...` is analogous to `kerl build git ...`, so `build source`, not `build-source`.

So it's `kerl build source <source_dir> <build_name>`.

> By "in-place" do you mean "where the (source) code resides"...?
I mean the ability to hack on the Erlang source code directly and then just run kerl commands to make it available to use. If I hack on the Erlang source code some more, those changes would ideally be reflected immediately in the kerl-installed copy, but I'm cool with running another kerl command if necessary.

The point being to streamline (and remove the errors from) my hacking-on-Erlang efforts.

**Comment by paulo-ferraz-oliveira** [comment]
> Also yes, though the first `source` in `kerl build source ...` is analogous to `kerl build git ...`, so `build source`, not `build-source`.

Got it. It is a pain to deal with both `git` and non-`git` in the current code base already, though, so adding a new variant would probably further complicate stuff <sup>(1)</sup>, but we could try to fit it.

> would ideally be reflected immediately in the kerl-installed copy

You mean after calling the proposed command, right? Or is it via some kind of "watch hook"? (I ask this because of you mentioning "immediately").

---

<sup>(1)</sup> but that's a detail for implementation, I guess - we could even go for `build`, `build-git` and `build-source`; not sure why `build` and `build git` were implemented as they were 🤷, removing `build git` from the documentation but supporting it for backward compatibility

**Comment by rlipscombe** [comment]
> You mean after calling the proposed command, right?

I mean that after I run `make` in the `otp` checkout (or `kerl build source ...`), ideally that's the version I'm using. But I realise that's probably kinda hard, so doing `kerl build source ... && kerl install source ...` would work too.

**Comment by jadeallenx** [comment]
Is the desire to just make kerl spit out an activation script (possibly with some parameters) rather than go through and build binaries?

**Comment by jadeallenx** [comment]
`kerl emit-activate param1 ... paramN` ?

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, if I got @rlipscombe right that'd be a potential work-around, yes, but there would still be the need for "tooling" around that (e.g. further scripts). Having an option to build the source "in-place" would ease hacking on Erlang itself.

"If it could just be a single command that'd be perfect," I believe is what @rlipscombe is looking for (?)

**Comment by rlipscombe** [comment]
I see the following levels of convenience:

1. Rewrite the activation script so that it has all of its parameters in one place, so that I can copy an existing one and edit it easily without needing to use `kerl install`. Currently the template has parameters spread all over the script, so it's hard to edit by hand.
2. Be able to spit out an activation script with the parameters directly. This could be a separate command, or could just be extracting the function that generates it from `do_install`, so that I could use a subshell to invoke it: `(source kerl ; do_emit_activate params)`
3. Make building Erlang from source first-class without needing to check it out from git. `kerl build git path/to/otp <build_name>` works, but I have to remember to commit my changes, and it's a clean build each time, which is slow. Having `kerl build source path/to/otp <build_name>` where it builds in place would be better. Another reason this is attractive is that the same kerl build options would work for building from git and for building from source.
4. _Not_ having to `kerl install` every time I make a change, somehow. Call it a stretch goal.

tbh, right now, being able to copy-paste an existing activate script and quickly change the configuration would be fine. That would require changing the activate script template.

**Comment by jadeallenx** [comment]
Refactoring activation script emission is a worthwhile goal. 

I guess I don't understand why you _don't_ want to use git to fetch Erlang source code? Like... don't you have your own fork of it? Anyway, the git handling is messy and duplicates a lot of stuff, so maybe it should be more generic so that the origin of the source we're building from doesn't really matter.

**Comment by rlipscombe** [comment]
> I guess I don't understand why you don't want to use git to fetch Erlang source code?

Because I'm literally hacking on it right at that moment. It's not committed anywhere (yet). I want to take advantage of incremental make, rather than build from clean. I mean: Apple M1 is _quick_, but it's still not instant :)

But I also want to use kerl's activation script so that when I change to the directory where my example/test code is, direnv can cleanly activate the OTP built from source

Though, now I think about it, I _could_ implement this with some direnv incantations, rather than kerl, I guess.

**Comment by jadeallenx** [comment]
OK - so is this a low key feature request or something we should try to get done soonish?

**Comment by paulo-ferraz-oliveira** [comment]
> Refactoring activation script emission is a worthwhile goal.

This I could probably tackle and it'd improve the code base, in any case, if it's worth it.

**Comment by jadeallenx** [comment]
I think it's a good goal, yes.

**Comment by paulo-ferraz-oliveira** [comment]
@rlipscombe, once #452 is "all CI Ok" could you possibly test it, and let us know what you think, so we could merge? Thanks.

**Comment by rlipscombe** [comment]
Sorry about not responding -- I was away for a week with limited access.

**Comment by paulo-ferraz-oliveira** [comment]
No prob at all, @rlipscombe. When/if you publish your method, eventually, do let me know (if you remember and want to reply to this). I'm also interested in understanding if we can simplify `kerl` even further to use for your use case (which is also mine, at times): hacking Erlang and compiling it. Or, if you have further ideas, do create an issue so we can discuss further 😄
