### ISSUE TITLE
Remove no-longer-supported OTP version-specific code

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [kerl/kerl#455]
Remove pre-24 -specific code, as per the [Erlang/OTP support policy](https://github.com/kerl/kerl#erlangotp-support-policy).

If 27, 28, etc. is out before this is handled pre-24 will become pre-25, pre-26, etc.

Examples of this:

* [maybe_patch_darwin](https://github.com/kerl/kerl/blob/17943479c00e53b5e17102119d4c371c55d737bc/kerl#L777C1-L777C19)
* [maybe_patch_catalina](https://github.com/kerl/kerl/blob/17943479c00e53b5e17102119d4c371c55d737bc/kerl#L792C1-L792C21)

**Comment by jadeallenx** [comment]
Nothing like a PR with only deletes :)

**Comment by jadeallenx** [comment]
there's also some ancient patches for Erlang R14 and R15 in there too. I always wanted the patching mechanism to be external (like in a directory but I could never quite work out how to make it convenient and self-contained in the context of "download one file and it has everything")

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, it'd probably take e.g. some templating, but then maintenance would suffer from it. Any way, I have code prepared for this, but I wanna push one pull request at a time 👍

**Comment by jadeallenx** [comment]
Right it’s probably not practical but it would be nice and clean and let people extend it in ways that are useful
