### ISSUE TITLE
Error at the end of the build

### ISSUE THREAD

**Issue by andrei-mihaila** [kerl/kerl#473]
#### The bug

Getting an error at the end of the build:
```log
error: improper list

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1)
```

This probably just affects the message displayed at the end of the build ('You can activate this installation running the following command:') - not displayed.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Gentoo & Fedora GNU/Linux (probably irrelevant)
* Erlang/OTP: 24, 25, 26 (irrelevant)
* `kerl`: latest, retrieved on 2023.10.05 from https://raw.githubusercontent.com/kerl/kerl/master/kerl
* other (where applicable): ps --version
ps from procps-ng 4.0.4

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build ...`
2. search for `error: improper list` in the error output

#### Expected behaviour

The error should not be happening and the right message should be displayed at the end of the build.

#### Additional context

I think the problem is on this line: [1462](https://github.com/kerl/kerl/blob/master/kerl#L1462).
The code is running `ps` to get the parent PID (used later to determine if the current terminal is bash or zsh or other). The result of that line can contain leading spaces, for example:
```sh
$ ps -p $$ -o ppid=
 2970
```
On the next line ps expects a list of comma separated PIDs (no spaces). For example:
```sh
$ ps -p " 2970" -o ucomm | tail -n 1
error: improper list

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
# it works with the spaces removed
$ ps -p " 2970" -o ucomm | tail -n 1
bash
```

Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for reporting. I can fix this based on your input, and using a Fedora image. I can't replicate it locally, but probably because my process id is already so high that no space is output.

**Comment by paulo-ferraz-oliveira** [comment]
Also, looking at that code, I feel having `|| exit` there is "somewhat off". 😄

**Comment by paulo-ferraz-oliveira** [comment]
Error was introduced by me, [here](https://github.com/kerl/kerl/pull/463/files#diff-2df8b125dc6a121ab2da71f2e0fe968fd2d8d710fbecfcb53e93fc2c6c05850bL1655).

**Comment by paulo-ferraz-oliveira** [comment]
@andrei-mihaila, I've pull requested to fix this. Would you care to check the proposed changes and let us know if they're effective for your use case: https://github.com/kerl/kerl/pull/474/files?

Thanks.

Ah, as a side note: I could just go back to the "old" code and add the `shellcheck disable`, but this way it's clearer as to what our intentions are. (the lack of comment there was what led me to believe we we're "just avoiding" ShellCheck).

**Comment by andrei-mihaila** [comment]
Tested and it works. Thank you!
