### ISSUE TITLE
/home/bengt/bin/kerl: eval: line 856: ./otp_build: not found

### ISSUE THREAD

**Issue by ebengt** [kerl/kerl#487]
#### The bug

`kerl build 26.1.2 erlang26`
gives the output
```
Colorization disabled as 'tput' (via 'ncurses') seems to be unavailable.
Extracting source code for normal build...
Building (normal) Erlang/OTP 26.1.2 (erlang26); please wait...
Initializing (build) log file at /home/bengt/.kerl/builds/erlang26/otp_build_26.1.2.log.
ERROR: configure failed.
[packages] Release ID found in /etc/os-release: alpine
[packages] Found package declarations for your Linux distro: alpine
[packages] Probe success for openssl-dev (distro: alpine)!
[packages] Probe success for make (distro: alpine)!
[packages] Probe success for automake (distro: alpine)!
[packages] Probe success for autoconf (distro: alpine)!
[packages] Probe success for ncurses-dev (distro: alpine)!
[packages] Probe success for gcc (distro: alpine)!
[packages] Probe success for g++ (distro: alpine)!
/home/bengt/bin/kerl: eval: line 856: ./otp_build: not found

```
#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Alpine 3.18
* Erlang/OTP: Not yet
* `kerl`: 4.0.0
* other (where applicable): ...

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build 26.1.2 erlang26`
2. search for `./otp_build: not found` in the error output

#### Expected behaviour

Expected Erlang 26 to be built.

#### Additional context

Alpine running in x86 VM on Mac Arm.

I am probably building it wrong, but do not know what to look for. Line 856 of kerl is
        CFLAGS="${CFLAGS:-}" "$@"                                       
Where does otp_build come from?

**Comment by paulo-ferraz-oliveira** [comment]
👋 `otp_build` comes from [Erlang/OTP itself](https://github.com/erlang/otp/blob/master/otp_build), but there's probably something that should be more explicit and isn't. I know we're testing 26 in our pipeline, but it's not using Alpine. I'll try to replicate this locally...

**Comment by paulo-ferraz-oliveira** [comment]
In your output, I see `Extracting source code for normal build...` but that is only available in the main branch. Maybe you can confirm your `kerl` version with `./kerl version` (if you're running from the repo) or `kerl version` (if you have `kerl` installed globally?) (?)

**Comment by paulo-ferraz-oliveira** [comment]
With `kerl` 4.0.0 I have no issues with the following instruction set:

```console
docker run -it alpine
apk add git
apk add curl
git clone https://github.com/kerl/kerl
cd kerl
git checkout tags/4.0.0
./kerl build 26.1.2 erlang26
# installed packages the probe system complained about: openssl-dev, make, ...
apk add openssl-dev make automake autoconf ncurses-dev gcc g++
./kerl build 26.1.2 erlang26
```

Output: `Erlang/OTP 26.1.2 (erlang26) has been successfully built`

**Comment by paulo-ferraz-oliveira** [comment]
Do you have any (shareable) output for `env | grep KERL_`?

And what about `"$HOME"/.kerlrc` (or otherwise the file `KERL_CONFIG` points to). Could you share that?

**Comment by paulo-ferraz-oliveira** [comment]
With `kerl` "main" I have no issues with the same (previous) instruction set.

Output:

```console
Colorization disabled as 'tput' (via 'ncurses') seems to be unavailable.
Extracting source code for normal build...
Building (normal) Erlang/OTP 26.1.2 (erlang26); please wait...
Initializing (build) log file at /root/.kerl/builds/erlang26/otp_build_26.1.2.log.
APPLICATIONS DISABLED (See: /root/.kerl/builds/erlang26/otp_build_26.1.2.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /root/.kerl/builds/erlang26/otp_build_26.1.2.log)
 * wx             : No OpenGL headers found, wx will NOT be usable
 * No GLU headers found, wx will NOT be usable
 * wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
 *         wxWidgets must be installed on your system.
 *         Please check that wx-config is in path, the directory
 *         where wxWidgets libraries are installed (returned by
 *         'wx-config --libs' or 'wx-config --static --libs' command)
 *         is in LD_LIBRARY_PATH or equivalent variable and
 *         wxWidgets version is 3.0.2 or above.

DOCUMENTATION INFORMATION (See: /root/.kerl/builds/erlang26/otp_build_26.1.2.log)
 * documentation  :
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  xmllint is missing.
 *                  The documentation cannot be built.

Erlang/OTP 26.1.2 (erlang26) has been successfully built.
```

**Comment by paulo-ferraz-oliveira** [comment]
Fwiw, the container I pulled is Alpine Linux 3.18.4, as per `/etc/os-release`.

**Comment by paulo-ferraz-oliveira** [comment]
As for

```bash
CFLAGS="${CFLAGS:-}" "$@"
```

`@` Expands to the positional parameters, starting from one. So where you see `_flags ./otp_build` it relates to that.

**Comment by ebengt** [comment]
Sorry about the delay.
```
alpine86:~$ kerl version
Colorization disabled as 'tput' (via 'ncurses') seems to be unavailable.
4.0.0

```
Alpine from alpine-extended-3.18.0-x86_64.iso, VERSION_ID=3.18.2
(many thanks for explaining about /etc/os-release)
 ```
alpine86:~$ env | grep KERL_
```
(nothing)
```
alpine86:~$ "$HOME"/.kerlrc
-ash: /home/bengt/.kerlrc: not found

```
I installed **kerl** by doing:
```
$ curl -O https://raw.githubusercontent.com/kerl/kerl/master/kerl
Then ensure it is executable
$ chmod a+x kerl
```

**Comment by ebengt** [comment]
Now I will remove kerl and Erlang, then follow your instructions above. Hopefully that will work.

**Comment by ebengt** [comment]
After trying again from the begining it worked.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I see why you assumed version 4.0.0, now. Because until we release a new one, the old one is picked by that command 😄 Glad everything worked out.
