### ISSUE TITLE
erlang_ls

### ISSUE THREAD

**Issue by halturin** [kerl/kerl#493]
couldnt see how erlang_ls can be used with kerl env. would be great to have a kind of manual

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @halturin.

I don't quite understand what you're asking for. In any case, I don't think `kerl` depends (or should depend) on `erlang_ls`, though the other way around might be true (?) 🤷 

I suggest you open a similar issue in that repository to get some more feedback.

**Comment by halturin** [comment]
You are right, it must be on the erlang_ls side.
