### ISSUE TITLE
kerl sets REBAR_CACHE_DIR and this changes the rebar3 template directory behavior

### ISSUE THREAD

**Issue by jj1bdx** [kerl/kerl#495]
#### The bug

kerl sets REBAR_CACHE_DIR when enabling an installation. This causes a side effect of moving default rebar3 template directory to `${REBAR_CACHE_DIR}/.config/rebar3/templates`, instead of default `${HOME}/.config/rebar3/templates`.

#### Software versions

* OS: macOS 14.1.1 / Ubuntu 22.04.3 LTS
* Erlang/OTP: 26.1.2
* kerl version: 4.0.0
* rebar3 versions: 
    - rebar 3.22.1+build.5323.ref7a27a26c on Erlang/OTP 26 Erts 14.1.1
    - rebar 3.22.1+build.5324.ref03dda735 on Erlang/OTP 26 Erts 14.1.1

#### How to replicate

* Install OTP 26.1.2 with kerl
* Build a rebar3 with installed kerl
* Invoke the `rebar3 new` command

#### Expected behaviour

* Placing template files under `${HOME}/.config/rebar3/templates` are not recognized
* Placing template files under `${REBAR_CACHE_DIR}/.config/rebar3/templates` are recognized
* A typical value of REBAR_CACHE_DIR: `${HOME}/otp/26.1.2/.cache/rebar3` on macOS

#### Additional context

* See the following issue and comment on rebar3 repository for this behavior:
  - [erlang/rebar3: REBAR_CACHE_DIR and global config clash #2762](https://github.com/erlang/rebar3/issues/2762)
  - https://github.com/erlang/rebar3/issues/2762#issuecomment-1820569427

**Comment by paulo-ferraz-oliveira** [comment]
Thank you for the report, @jj1bdx.

Should we wait for some change to `rebar3`? Or what would you propose `kerl` changes?

Fwiw, this is a rather recent change (https://github.com/kerl/kerl/pull/457) and we did check stuff around the use of that env. variable, but maybe not thoroughly enough (?)

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, any thoughts on this? It seems more like a `rebar3` issue to me, so it should/could be solved upstream, but the solution isn't easy, because it's backward-breaking. At the same time, I'm really out of ideas on what `kerl` can do to solve it.

**Comment by jadeallenx** [comment]
Upstream needs to address this

**Comment by paulo-ferraz-oliveira** [comment]
Then I'm closing this. @jj1bdx, feel free to re-open if you have an idea of how `kerl` can help, in this case.

**Comment by jj1bdx** [comment]
I agree that the upstream, aka rebar3, needs to address this first.
