### ISSUE TITLE
kerl cannot be build on FreeBSD14.

### ISSUE THREAD

**Issue by Toutzn** [kerl/kerl#500]
#### The bug

the kerl build fails on FreeBSD14 with the following error:
checking for 1-stage DTrace precompilation... dtrace: failed to compile script emulator/beam/erlang_dtrace.d: "/usr/lib/dtrace/ipfw.d", line 1: syntax error near "in_addr_t"

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: FreeBSD builder14 14.0-RELEASE-p3 FreeBSD 14.0-RELEASE-p3
* Erlang/OTP: 26.2
* `kerl`: 4.0.0

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build 26.2 26.2`

#### Expected behaviour

`
checking for sys/sdt.h... yes
checking for 1-stage DTrace precompilation... dtrace: failed to compile script emulator/beam/erlang_dtrace.d: "/usr/lib/dtrace/ipfw.d", line 1: syntax error near "in_addr_t"
configure: error: Could not precompile erlang_dtrace.d: dtrace -h failed
ERROR: /home/gitlab-runner/.kerl/builds/26.2/otp_src_26.2/erts/configure failed!
kill: -54204: No such process
`

#### Additional context

Other, earlier versions I got the same issue. Any idea?

**Comment by garazdawi** [comment]
If you don't need dtrace support I suggest you disable it and try again. If you do need dtrace, then check what is going on with `/usr/lib/dtrace/ipfw.d` and why it cannot be compiled by `dtrace -h`.

**Comment by Toutzn** [comment]
Ok. without dtrace it works

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @Toutzn, @garazdawi.

This does not seem like a `kerl`-specific issue, thus I'm closing it. Feel free to reopen it if you feel otherwise or the `kerl` project can help overcome this issue.
