### ISSUE TITLE
Add Perl5 to common_ALL_BUILD_BACKEND_git_pkgs or _KPP_alpine_pkgs

### ISSUE THREAD

**Issue by ebengt** [kerl/kerl#503]
#### Is your feature request related to a problem?

kerl build ...
will fail if Perl5 is missing, same as with automake/autoconf

#### Describe the feature you'd like

I think it is a good idea to add Perl5 to common_ALL_BUILD_BACKEND_git_pkgs, or
if Perl5 is included in other distros, add to _KPP_alpine_pkgs
That way kerl will display a warning, before building Erlang.

#### Describe alternatives you've considered

It is possible to let the Erlang configure step fail, like it does now, but that will also happen for automake, so this is as desirable. 

#### Additional context

Any other context about the feature request.

**Comment by paulo-ferraz-oliveira** [comment]
👋 

I see Erlang state it depends on Perl 5 during compilation (https://www.erlang.org/doc/installation_guide/install), but I've never actually seen it fail for lack of.

What OS is it you're using?

**Comment by ebengt** [comment]
Alpine linux. It starts with few default packages. Just enough to get you started.

**Comment by paulo-ferraz-oliveira** [comment]
👋 
The goal of the "package probe system" is to not have to know, beforehand, what is required and what is not (from the consumer - `kerl` does "need" to know"). We're open to pull requests 😄.
If you add it to all common packages, it's very possible it'll not complain in most cases but the one you mention, Alpine, which is good and expected.
On the other hand, to add it there, it'd be better to first verify if the package name is the same in all distros (maybe you already have?).

**Comment by ebengt** [comment]
I have not verified Perl package name in ''all'' distros. (How many are there?)
I will try to make pull request for Alpine.

**Comment by ebengt** [comment]
Sorry about the confusion. I started a new Alpine and installed kerl. The package warnings prompted me to install several missing packages. One of these, automake, installs perl. So perl is installed in Alpine. My mistake.

**Comment by paulo-ferraz-oliveira** [comment]
> How many are there?

In the wild, many hundreds; but `kerl` "knows" only a bunch (like 5 or 6).
