### ISSUE TITLE
Warning checking build packages on Pop OS

### ISSUE THREAD

**Issue by aschiavon91** [kerl/kerl#504]
#### The bug

When building some versions in PopOS system, it warns about the unknown system.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Pop!_OS 22.04 LTS
* Erlang/OTP: 26.2.2
* `kerl`: 4.0.0
* other (where applicable): (maybe all versions due to its an OS system issue)

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build 26.2.2 erlang_26.2.2`
2. search for `[packages] Unknown Linux distro pop; not checking build packages.` in the error output

#### Expected behaviour

Should not warn about the os and successfully validates the required build packages.

#### Additional context
![image](https://github.com/kerl/kerl/assets/3910403/b4766af7-23c8-4c5b-9678-d7e7de892752)

BTW, thanks for all the work!

**Comment by paulo-ferraz-oliveira** [comment]
This is not a bug 😄 This is `kerl` **warning** the consumer that it doesn't **know** about Pop!_OS, which means it can't expect a given number of packages (as it does for **known** systems). I think the pull request you did tries to address this issue (haven't looked at it yet), but I'm mostly writing here for reference.

**Comment by aschiavon91** [comment]
sorry man, I just picked the template that makes more sense to me, but I agree its not a bug
