### ISSUE TITLE
Cannot build R16B02 on Mac OS X 10.8.5

### ISSUE THREAD

**Issue by JohanVikman** [kerl/kerl#51]
Hi,

I have problems building R16B02 on Mac OS X 10.8.5.

Looking at the log I see pretty early on

...
can't open x86_64-apple-darwin12.5.0/opt/plain/erl_compile_flags.h for writing at utils/make_compiler_flags line 65.
...

And I have similar errors further down.

BUT, I have no problem installing R14B04 or R15B03, therefore I suspect there is something wrong with how kerl tries to build R16B02. It seems some path is bad, but I'm new to Kerl so I dont know where to look and change.

How come R14B04 works but not R16B02?

**Comment by mrallen1** [comment]
I think this will be solved by using the idea in #53
