### ISSUE TITLE
Ubuntu 24.04: kerl generates a warning for non-existing libncurses5-dev package

### ISSUE THREAD

**Issue by jj1bdx** [kerl/kerl#518]
#### The bug

kerl generates a warning for not having libncurses5-dev for Ubuntu, which is not in the apt library of Ubuntu 24.04

#### Software versions

* Operating System: Ubuntu 24.04 (not LTS yet, development version as of 12-APR-2024)
* Erlang/OTP: 26.2.3
* `kerl`: 4.1.0

#### How to replicate

Running a script of `otp-install-from-git-ubuntu.sh 26.2.3`

otp-install-from-git-ubuntu.sh source:

```sh
#!/bin/sh
# For Ubuntu with a local OpenSSL
OTP_VERSION=$1
OPENSSL_LOCAL="/opt/openssl/3.2.1"
INSTALL_DIR_PREFIX="/home/kenji/otp/"
INSTALL_NAME=${OTP_VERSION}
#
env \
    CC=/usr/bin/cc \
    CXX=/usr/bin/c++ \
    CFLAGS="-O3 -fstack-protector-strong" LDFLAGS="-fstack-protector-strong" \
    MAKEFLAGS="-j8" \
    KERL_BUILD_DOCS="yes" \
    KERL_DOC_TARGETS="chunks" \
    KERL_BUILD_PLT="yes" \
    KERL_CONFIGURE_OPTIONS="--disable-dynamic-ssl-lib --enable-kernel-poll --enable-dirty-schedulers --disable-sctp --disable-sharing-preserving --without-javac --without-odbc --with-ssl=${OPENSSL_LOCAL} --with-wx-config=/opt/wx-3.2/bin/wx-config" \
    sh -c "(kerl build git https://github.com/jj1bdx/otp/ OTP-${OTP_VERSION} ${INSTALL_NAME} && kerl install ${INSTALL_NAME} ${INSTALL_DIR_PREFIX}${INSTALL_NAME})"
```

#### Expected behaviour

kerl generates the following WARNING message:

```
Checking out Erlang/OTP git repository from https://github.com/jj1bdx/otp/...
Building (git) Erlang/OTP OTP-26.2.3; please wait...
Initializing (build) log file at /home/kenji/.kerl/builds/26.2.3/otp_build_git.log.
WARNING: [packages] Probe failed for libncurses5-dev (distro: ubuntu): probe "dpkg-query -Wf'${db:Status-abbrev}' "libncurses5-dev" 2>/dev/null | \grep -q '^i'" returned 1
```

#### Additional context

Installed libncurses-related packages searched by `sudo apt list | grep libncurses`:

```
libncurses-dev/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
libncurses5/now 6.3-2ubuntu0.1 amd64 [installed,local]
libncurses6/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
libncursesada-dev/noble 6.3.20211021-11build1 amd64
libncursesada6.2.4/noble 6.3.20211021-11build1 amd64
libncursesw5/now 6.3-2ubuntu0.1 amd64 [installed,local]
libncursesw6/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
```

I think for Ubuntu 24.04 kerl should accept libncurses-dev instead of libncurses5-dev (not in the apt list anymore).

**Comment by jj1bdx** [comment]
My understanding:

* Ubuntu 22.04 LTS has libncurses5-dev.
* Ubuntu 24.04 (to be LTS) has libncurses-dev.

**Comment by paulo-ferraz-oliveira** [comment]
I see. Yeah, I thought I'd tested this. We'll maybe think about having a fallback mechanism for the warning, since it's still valid for 22.04 (right?).

**Comment by jj1bdx** [comment]
[Ubuntu libncurses5-dev package search result](https://packages.ubuntu.com/search?keywords=libncurses5-dev&searchon=names&suite=all&section=all) shows it's available from 20.04 until 23.04 (as a transitional package).

OTOH [Ubuntu libncurses-dev search result](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libncurses-dev&searchon=names) shows it's available from 20.04 to 24.04 (noble).

Maybe changing libncurses5-dev to libncurses-dev will do, but that should be tested on an old Ubuntu.

Also, the current Ubuntu setting is inherited from that of Debian, so we also need to check out how this works on Debian.

https://github.com/kerl/kerl/blob/2ace9371dd6dd5575ae375ebd1edb3639d7e162d/kerl#L885

https://github.com/kerl/kerl/blob/2ace9371dd6dd5575ae375ebd1edb3639d7e162d/kerl#L911-L912

**Comment by 03juan** [comment]
For what it's worth, the [ncurses announcement page](https://invisible-island.net/ncurses/announce.html) for v6.5 says:

>These notes are for ncurses 6.5, released April 27, 2024.
>
>This release is designed to be source-compatible with ncurses 5.0 through 6.4; providing extensions to the application binary interface (ABI).

[Debian](https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=libncurses5-dev) and [Ubuntu](https://packages.ubuntu.com/search?keywords=libncurses5-dev&searchon=names&suite=all&section=all)'s `libncurses5-dev` packages all install versions that range between v6.1 and v6.4.

And then both Debian and Ubuntu's `libncurses-dev` support the same minimum OS release versions.

![image](https://github.com/kerl/kerl/assets/4416345/81853b12-fbe7-42d7-8992-bf1f3268d1f4)
![image](https://github.com/kerl/kerl/assets/4416345/dddba301-6284-4680-bb23-bc76d7b1e274)


![image](https://github.com/kerl/kerl/assets/4416345/404842b4-3424-4b3f-8da7-4aca83ba3095)
![image](https://github.com/kerl/kerl/assets/4416345/fcf0f7ce-d0f1-4782-9906-fcf83d49779a)


Alternatively the probe could just test with a more relaxed string.
```bash
❯ dpkg-query -l 'libncurses[^w]*dev' 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version               Architecture Description
+++-====================-=====================-============-=================================
ii  libncurses-dev:amd64 6.4+20240113-1ubuntu2 amd64        developer's libraries for ncurses
un  libncurses5-dev      <none>                <none>       (no description available)
```

**Comment by paulo-ferraz-oliveira** [comment]
@jj1bdx, if the probe's relaxed check seems like a good test we'd be Ok to be pull requested for the change.

**Comment by jj1bdx** [comment]
@paulo-ferraz-oliveira 
'libncurses[^w]*dev' looks good to me.

**Comment by paulo-ferraz-oliveira** [comment]
@jj1bdx, `libncurses[^w]*dev` was adopted as the solution in the linked pr.
