### ISSUE TITLE
kerl should not install in non empty directories

### ISSUE THREAD

**Issue by peerst** [kerl/kerl#52]
Currently kerl does a mkdir -p and checks if the target dir is a directory.

It should also check if the directory is empty and refuse to install in nonempty directories.

This avoids messing up and even overwriting directories that e.g. have been accidentially specified.

Since "delete installation" just does a rm -Rf after checking for activate this can get disastrous. E.g. installing by accident in ones home dir, noticing the error and deleting it again => home dir erased

**Comment by mrallen1** [comment]
@sanmiguel This is a great idea

**Comment by mrallen1** [comment]
Knocked this out with #127.
