### ISSUE TITLE
Over-optimized for happy path in "Probe failed for libncurses5-dev" warning.

### ISSUE THREAD

**Issue by 03juan** [kerl/kerl#522]
#### Is your feature request related to a problem?

I think I overoptimized PR #521 for #518, the real intent of the warning ends up looking messy for users:

![image](https://github.com/kerl/kerl/assets/4416345/3c68273e-04b0-4fc1-9bc4-f9023aea644c)

#### Describe the feature you'd like

I'd like to give the fix another go with a more sophisticated approach that tests for either package, and then warns if none are found by favoring `libncurses-dev`.

My proposal is to include both libraries individually in `common_debian_pkgs` and then extend the probe loop by special-casing the `*ncurses*` package tests, only warn if none are found, and ensure this works for all os releases, not just deb-based.

#### Describe alternatives you've considered

I've tried to use expansion to test for either package, which works in a bash/zsh shell:

![image](https://github.com/kerl/kerl/assets/4416345/714cdf9d-6514-45ea-9154-e66ce3eeff19)

But not in sh:

![image](https://github.com/kerl/kerl/assets/4416345/fc6da6ca-3988-413a-90ca-0fa650ad2e99)

#### Additional context

This will then encourage users to favor the "new" package, but not complain if the system only has "5" installed.

**Comment by paulo-ferraz-oliveira** [comment]
I don't think that we should complicate the probing mechanism more than it is. It's a rather "best effort" thing.

**Comment by leonardb** [comment]
@paulo-ferraz-oliveira 
Just commenting here since Ubuntu Noble (24.04) no longer has libncurses5-dev, but libncurses6-dev

**Comment by paulo-ferraz-oliveira** [comment]
We're using `libncurses-dev` in `kerl`'s CI, with Ubuntu 24.04, and it seems to work Ok. Is it an alias?

**Comment by leonardb** [comment]
The update on the issue I commented on resolved the issue. I was using an
out of date kerl it seems. Yes, Noble has alias for libncurses-dev
