### ISSUE TITLE
Unable to install man pages for OTP 27

### ISSUE THREAD

**Issue by ansd** [kerl/kerl#525]
#### The bug

https://github.com/kerl/kerl/issues/519 fixed building and installing man pages for OTP 26.
However, installing man pages for OTP 27 is broken.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Ubuntu 22.04
* Erlang/OTP: 27.0
* `kerl`: 4.1.1

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1.
```
/bin/cat ~/.kerlrc
export KERL_INSTALL_MANPAGES=yes
export KERL_DEFAULT_INSTALL_DIR="$HOME"/kerl
```
2.
```
kerl build-install 27.0
```
3.
```
. ~/kerl/27.0/activate
```
4.
```
erl -man erlang
No manual entry for erlang
No manual entry for --
```

#### Expected behaviour

```
erl -man erlang
```
displays man pages.

#### Additional context

Works neither on OSX nor on Ubuntu.

Note that as described in https://github.com/kerl/kerl?tab=readme-ov-file#kerl_doc_targets variable `KERL_DOC_TARGETS` won't work anymore:
```
man (dropped in OTP 27): install manpage docs.
```
Hence, I can't build the docs locally anymore and have to use `KERL_INSTALL_MANPAGES=yes` instead which is broken.

**Comment by garazdawi** [comment]
Erlang/OTP 27.0 does not have any man pages, so it is not strange that it cannot be installed.

We will re-introduce some man pages in Erlang/OTP 27.1, but that will only be for executables such as `erl`, `erlc` etc.

**Comment by ansd** [comment]
I see, thank you!
