### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by jacktang** [kerl/kerl#529]
Hello,

I try to build erlang 27.0 after upgrading macos, and come up some config errors:

```
*** Sat Jun 15 11:00:39 CST 2024 - kerl build 27.0 ***
Build options:
/Users/jacktang/.kerl/builds/27.0/otp_src_27.0/configure  --cache-file=/dev/null CC=clang --enable-darwin-64bit --with-ssl=/usr/local/opt/openssl@1.1
=== Running configure in /Users/jacktang/.kerl/builds/27.0/otp_src_27.0/erts ===
./configure 'CC=clang' '--enable-darwin-64bit' '--with-ssl=/usr/local/opt/openssl@1.1' --disable-option-checking --cache-file=/dev/null --srcdir="/Users/jacktang/.kerl/builds/27.0/otp_src_27.0/erts"
checking build system type... x86_64-apple-darwin21.6.0
checking host system type... x86_64-apple-darwin21.6.0
checking target system type... x86_64-apple-darwin21.6.0
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in '/Users/jacktang/.kerl/builds/27.0/otp_src_27.0/erts':
configure: error: C compiler cannot create executables
See 'config.log' for more details
ERROR: /Users/jacktang/.kerl/builds/27.0/otp_src_27.0/erts/configure failed!
./configure: line 370: kill: (-21169) - No such process
```
My macos is Monterey 12.7.5 and clang is 4.0.1

```
$ clang --version
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /usr/local/bin
```

How can I fix the build? Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
👋 

I haven't used macOS 14 yet, but I'll be sure to add it to our CI pipeline, to check if issues arise.

From your output (I'm sure you've seen that) we can see:

* `checking whether the C compiler works... no`, and
* `error: C compiler cannot create executables`

I'm not sure what would cause this, but if you create a simple C program and try to compile it (using `clang`), does it work?

**Comment by paulo-ferraz-oliveira** [comment]
As per https://github.com/kerl/kerl/pull/530's CI I can't see installation failing for OTP 27 on macOS 14. Did you search https://github.com/erlang/otp's issues (and/or pull requests) for something that might relate to your problem? (saying this as this does not seem `kerl`-related)

**Comment by paulo-ferraz-oliveira** [comment]
@jacktang, I'm closing this as non-`kerl`. Feel free to re-open if you feel otherwise.

**Comment by jacktang** [comment]
all right. I upgraded llvm and still did not solved the issue. I will add comments if I solved it

**Comment by jacktang** [comment]
I solved it by `brew uninstall llvm` since I found macos `gcc` is override `clang` by default, and `clang` homebrew package is not compatible in macos. 

```
(base) > $ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by sanjacob** [comment]
Facing this same issue
