### ISSUE TITLE
kerl hides the output of configure

### ISSUE THREAD

**Issue by sedrik** [kerl/kerl#53]
The end results of configure tells you if any applications in otp will be skipped due to missing dependencies. It would be nice if kerl could capture and present this information during building.

<pre>
*********************************************************************
**********************  APPLICATIONS DISABLED  **********************
*********************************************************************

jinterface     : No Java compiler found
odbc           : ODBC library - link check failed

*********************************************************************
*********************************************************************
**********************  APPLICATIONS INFORMATION  *******************
*********************************************************************

wx             : wxWidgets not found, wx will NOT be usable

*********************************************************************
*********************************************************************
**********************  DOCUMENTATION INFORMATION  ******************
*********************************************************************

documentation  : 
                 xsltproc is missing.
                 fop is missing.
                 xmllint is missing.
                 The documentation can not be built.

*********************************************************************
</pre>

**Comment by mrallen1** [comment]
This is really worthwhile. Good idea.

**Comment by mazenharake** [comment]
This is my proposal did last evening. Let me know if it looks good and I'll send a pull request.

https://github.com/mazenharake/kerl/commit/65123ce7bfa267677c5ae82e71c24270c424c613

**Comment by mrallen1** [comment]
Yes, please make a PR :) Thanks

**Comment by mrallen1** [comment]
Thanks! Going to close this issue since we merged #148
