### ISSUE TITLE
kerl upgrade always upgrading

### ISSUE THREAD

**Issue by Alberdi** [kerl/kerl#538]
#### The bug

`kerl upgrade` is always triggering an  upgrade, regardless of the current version.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: macOS 13.5
* `kerl`: 4.1.1

#### How to replicate

1. run `kerl upgrade`
2. run `kerl upgrade` again

#### Expected behaviour

At least the second step shouldn't trigger an upgrade.

#### Additional context

This is happening because the local version isn't properly placed. This was introduced in [8c3c7a31490678b88810d75368c7ad7782c604f](https://github.com/kerl/kerl/commit/f8c3c7a31490678b88810d75368c7ad7782c604f) when the output  of `kerl version` (and the other commands) was being sent to stderr, making the assignment `version=$(kerl version)` to be empty.

In https://github.com/Alberdi/kerl/commit/a3a1ef671188db155aa6b523e093d81f508ec1c2 I've tried a solution that seems to work, and I could create a PR or iterate over it (with my limited shell skills). I'm not sure if changing the `tip` call to an `echo` is the proper solution, but that would also help with external integrations that might want to parse the kerl version number.

**Comment by paulo-ferraz-oliveira** [comment]
👋, @Alberdi. Nice catch. It's possible that `tip`, as you mention, isn't properly coded. `echo` seems more appropriate in that case. If you pull request, try to add a test so this can go in "regression testing". Thanks.
