### ISSUE TITLE
Manage ELP as well (and maybe erlfmt)

### ISSUE THREAD

**Issue by i-am-linja** [kerl/kerl#545]
#### Is your feature request related to a problem?

Some Erlang tools are solely of use to the _developer_, and do not make sense to consider as part of the _project_ being developed: I think primarily of WhatsApp's Erlang Language Platform and erlfmt. rebar3 integrates with erlfmt, as it is _sort of_ a CI pass; but no such justification exists for ELP. Hence, a user of ELP must source their binary independently of the system that manages their OTP installations; in particular they must _manually_ synchronise their ELP version with the OTP version used _per project_, a tedious and brittle process.

#### Describe the feature you'd like

In addition to Erlang/OTP, kerl will optionally fetch and manage builds of the Erlang Language Platform, and potentially erlfmt as well. It will fetch the correct versions of these tools for each OTP version in use, and activate them when the corresponding version is activated.

#### Describe alternatives you've considered

I see no robust independent solution that does not involve recreating a significant part of kerl's functionality. As for alternatives within kerl itself, none come to mind.

**Comment by paulo-ferraz-oliveira** [comment]
Hello, and thanks for the feature request.

At this moment, `kerl` focus solely on installing Erlang/OTP (README: "Easy building and installing of [Erlang/OTP](https://www.erlang.org/) instances."). I think we should not move away from that single goal.

Tools like the ones you mention (ELP and `erlfmt`), for example, have not been around for long, and I'm not sure how ubiquitous they are; not to say they aren't important (`erlfmt` is easily achievable as a formatter when used as a `rebar3` plugin<sup>(1)</sup>, but so is `rebar3_format` and I'm not sure how `kerl` would give preference to one over the other, or if maintaining integration of several tools would be an easy path forward) and there's efforts to [turn ELP into a GitHub action](https://github.com/erlef/setup-elp), so they're definitely getting attention.

As for ELP, from what I could test/try when trying to [implement a basic version of an action](https://github.com/erlef/setup-elp), the installation process is yet complex. I'd much rather see an installer that plays well with several OTP versions at the same time (`erlang_ls`, for example, does that), then try to integrate that into `kerl`.

Another thing that makes me think this is not a good option is that you'd be integrating dependants of Erlang/OTP into the installation tool (`kerl`). I recently wanted to add Erlang/OTP 27 to Homebrew's packages and am fighting with dependants not being updated enough to allow doing that in an easy manner.

> in particular they must manually synchronise their ELP version with the OTP version used per project, a tedious and brittle process.

Some alternatives come to mind, that I've used in the past:

* asdf: https://asdf-vm.com/ (allows per folder package dependency management)
* direnv: https://direnv.net/ (allows per folder script execution)

___

<sup>(1)</sup> Installing a `rebar3`plugin -compatible formatter as a developer-only tool is typically easily achieved by installing the `rebar3` plugin as global.

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, thoughts?

I'm thinking (after I wrote the above) if it'd be possible/easy to implement a callback-like mechanism from the activation script, but a clear/easy solution does not come to mind.

**Comment by jadeallenx** [comment]
I'm ok with adding a hook to the activation script for the convenience of people who use ELP and erlfmt, but generally :-1: on managing installation of tools like erlfmt (and rebar3) and the language server. I feel like those are landmines for support we do not want.

Willing to entertain a rationale for taking on that support work, but kinda feel like it's a tar pit.

**Comment by i-am-linja** [comment]
The most compelling rationale I can offer is the sorry state of ELP packaging, and the economy of packaging it _once_ for every platform that might want it vs. packaging it per-platform. However, the only rationale for why kerl should be the place for this is a deficiency in ELP itself (one supported OTP version per build), which is pretty weak. Activation callbacks would be a separate issue.
