### ISSUE TITLE
tagged release?

### ISSUE THREAD

**Issue by asparagui** [kerl/kerl#62]
Homebrew (a mac package manager) would like a tagged release (all you need to do is push a version number).  Would this be possible?

https://github.com/Homebrew/homebrew/pull/26326
https://github.com/Homebrew/homebrew/pull/26307

**Comment by asabil** [comment]
:+1:

**Comment by radekg** [comment]
:+1:

**Comment by bfontaine** [comment]
Ping @yrashk?

**Comment by mrallen1** [comment]
This is a great idea. We have some co-maintainers around now and we're working on triaging PRs and open issues. I hope we will get a new release out in the next few weeks. When we do, we will tag it with a release number.

**Comment by sanmiguel** [comment]
Hi @asparagui !

We have now created 2 tags for `kerl`:
 - [0.8](https://github.com/yrashk/kerl/releases/tag/0.8) is as `kerl` stood before
 - [0.9](https://github.com/yrashk/kerl/releases/tag/0.9) is as `kerl` stands now that we've merged a couple of long-awaited PRs

How do we go about getting out of `homebrew-head-only` and back into `homebrew` proper?

**Comment by bfontaine** [comment]
Awesome, thank you @sanmiguel! :tada: 

Regarding `homebrew-head-only` I was going to submit a PR but if you want to do it let me know.

**Comment by sanmiguel** [comment]
Hi @bfontaine - I'm definitely in favour of you submitting the PR if you are up for doing so!

**Comment by bfontaine** [comment]
Done: https://github.com/Homebrew/homebrew-core/pull/296.

**Comment by sanmiguel** [comment]
Amazing, thank you @bfontaine !

**Comment by mrallen1** [comment]
Thanks :candy:

**Comment by mrallen1** [comment]
I'm also going to close this issue now. We will continue to tag new releases as we merge new PRs and resolve issues.
