### ISSUE TITLE
Compiling with --enable-native-libs

### ISSUE THREAD

**Issue by essen** [kerl/kerl#68]
Hello,

If you do the following with current kerl it fails to compile everything natively:

```
KERL_CONFIGURE_OPTIONS=--enable-native-libs kerl build 17.0 17.0_native
kerl install 17.0_native ~/erlang/17.0_native
. /home/essen/erlang/17.0_native/activate
% erl                                          
Erlang/OTP 17 [erts-6.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.0  (abort with ^G)
1> code:is_module_native(lists).
false
2> 
```

The reason for this is best explained in this email: http://erlang.org/pipermail/erlang-questions/2014-April/078460.html

Modifying kerl this way made it work as expected:

```
    if [ -n "$KERL_USE_AUTOCONF" ]; then
        ./otp_build autoconf $KERL_CONFIGURE_OPTIONS > "$LOGFILE" 2>&1 && \
            ./otp_build configure $KERL_CONFIGURE_OPTIONS > "$LOGFILE" 2>&1
        make clean
        ./otp_build configure $KERL_CONFIGURE_OPTIONS > "$LOGFILE" 2>&1
    else
        ./otp_build configure $KERL_CONFIGURE_OPTIONS > "$LOGFILE" 2>&1
        make clean
        ./otp_build configure $KERL_CONFIGURE_OPTIONS > "$LOGFILE" 2>&1
    fi
```

However this may or may not be something you guys want. AFAIK it's only needed for native libs so perhaps this can only be done then?

**Comment by mrallen1** [comment]
Good suggestion. Thanks.

**Comment by mrallen1** [comment]
I like the idea of removing the .beam files that come prepackaged with the tarball releases but I am wondering if it would be easier and simpler to have something like `find . -name *.beam -exec rm {}\;` to clean out the pre-existing beam files in the case when `--enable-native-libs` is turned on.

**Comment by essen** [comment]
Not sure, it's been a while. I've since switched to fetching directly from git tags, the problem might also exist there (due to https://github.com/erlang/otp/tree/maint/erts/preloaded/ebin) though it's also been a while and I don't have those builds anymore.

**Comment by mrallen1** [comment]
Should be fully addressed by building OTP from github tarballs, as merged in #122.

**Comment by essen** [comment]
Revisiting this, as this is not fully addressed. Kerl *should* be able to compile from a git checkout instead of having to switch to tarballs. For example one may have a local git mirror faster than downloading from the Internet, or their own patches not on github. Or both.

In my case the git method is just more convenient, so I'd love for it to work properly there too.

Can we reopen this? I will experiment a little with solutions.

**Comment by essen** [comment]
The find line fails. I don't think there's anything around running configure twice.

**Comment by essen** [comment]
Perhaps an option "KERL_CLEAN_CONFIGURE" or similar would work out.

**Comment by mrallen1** [comment]
I  don't understand. You have `KERL_BUILD_BACKEND=git` and the native lib building still fails?

**Comment by essen** [comment]
No I am using "kerl build git $URL $COMMIT $BUILD". I do not build from tarballs, and I don't (always) pull this from Github. But I suppose the result would be the same from Github's tarballs; they're the same source after all.

The problem is *not* that the build doesn't succeed. The problem is that the resulting build ends up having many files *not compiled natively* when they should. An example file that doesn't get built natively is the lists module.

The solution to make everything build as it should (from Kostis) is to configure, then clean, then configure with the native option. But it's probably not desirable in most cases, so I suggest adding an option to do the extra clean+configure when required. An alternative would be to detect --enable-native-libs and do the extra clean+configure in that case. Or a mix of both. Either is fine for me but I'm not sure how other people use kerl, I use very little of it.

**Comment by essen** [comment]
Whichever solution is picked up I can do the patch, I have about 50 or so more native builds to make.

**Comment by mrallen1** [comment]
I think I would prefer to do the extra clean+configure step if `--enable-native-libs` is in `KERL_CONFIGURE_OPTIONS`

**Comment by essen** [comment]
Alright. I will get it done during the week.

**Comment by mrallen1** [comment]
Thanks! Appreciate that a bunch.

**Comment by mrallen1** [comment]
Sorry for the necro-posting but I just noticed that recent (but maybe all??) versions of ./otp_build include an option called `remove_prebuilt_files` - so I'm wondering if that's better than a "configure, delete, configure" sequence.

**Comment by essen** [comment]
IIRC these are for the .beam files that come with OTP. Removing them will prevent compilation entirely without Erlang installed. Might be wrong though.

**Comment by mrallen1** [comment]
Hmm, ok. I tried to read the code but I don't truly understand what it does.
