### ISSUE TITLE
Simplify installation process

### ISSUE THREAD

**Issue by davidw** [kerl/kerl#79]
Hi,

I had a thought: the most common use case for kerl is to install various versions of Erlang, why not make that really simple to do by removing some of the 'extra' steps?  For example:

```
kerl build-install git https://github.com/erlang/otp.git OTP-17.1.2 17.1.2
```

Builds and installs in .kerl/installations/17.1.2/

**Comment by mrallen1** [comment]
I would definitely like an `install` command that implies a build if a release isn't already present. Thanks for the suggestion.

**Comment by fenollp** [comment]
@davidw Wanna takle this?
