### ISSUE TITLE
when you have no network and try and install things it's still saves them

### ISSUE THREAD

**Issue by nicferrier** [kerl/kerl#83]
I was on a train with no network. I re-installed a previous build to see if I could install the documentation:

```kerl install r16b02```

it failed (obviously) with curl failures.

But when that happened it didn't clean up the output, I had 2 files in my .kerl/archives that were artifacts of the attempt. 

You could use `curl -f` and detect failures and clean up files.

**Comment by mrallen1** [comment]
Seems like a good suggestion. Thanks!

**Comment by mrallen1** [comment]
When we start kerl and there's a purported artifact, `tar` needs to ensure the file its considering is a real file.
