### ISSUE TITLE
kerl prompt displays two versions

### ISSUE THREAD

**Issue by rlipscombe** [kerl/kerl#88]
I've got 17.3 and 17.3.4 installed using kerl. I'm using 17.3, and `kerl prompt` returns

```
 (17.3
17.3.4)
```

I was expecting it to return only ` (17.3)`

**Comment by mrallen1** [comment]
Currently triaging tickets. Is this still an issue?

**Comment by rlipscombe** [comment]
Confirmed: It's still happening. If I have two versions installed, one of which is a prefix of the other, and I'm using the shorter one, then `kerl prompt` returns both.

So, for example, I have 18.2.1 installed, and I just installed 18.2. If I activate 18.2, then it returns both; if I activate 18.2.1, it returns the expected one.

**Comment by mrallen1** [comment]
Thanks! Appreciate the confirmation.

**Comment by mrallen1** [comment]
kerl currently doesn't have *any* releases, but we're going to tag one pretty darn soon here.

**Comment by mrallen1** [comment]
OK, please reopen if this is still an issue after #150. Thanks.
