### ISSUE TITLE
Export GREP_OPTIONS

### ISSUE THREAD

**Issue by essen** [kerl/kerl#98]
Some users may have a value defined and that can make the build fail as per http://erlang.org/pipermail/erlang-questions/2014-April/078526.html and recent Twitter comments. Should probably set GREP_OPTIONS='' in kerl directly.

Putting this here so it's not forgotten as neither of us have time to work on it right now.

**Comment by mrallen1** [comment]
Thanks for the report. See also #99

**Comment by mrallen1** [comment]
This got merged.
